// packages/sfui/frameworks/vue/components/SfAccordionItem/SfAccordionItem.vue
<script lang="ts" setup>
import { ClassProp } from '@storefront-ui/vue';

defineProps({
  modelValue: {
    type: Boolean,
    default: false,
  },
  summaryClass: ClassProp,
});

defineEmits<{
  (event: 'update:modelValue', open: boolean): void;
}>();
</script>

<template>
  <details :open="modelValue" data-testid="accordion-item">
    <summary
      :class="[
        summaryClass,
        'list-none [&::-webkit-details-marker]:hidden cursor-pointer focus-visible:outline focus-visible:outline-offset focus-visible:rounded-sm',
      ]"
      @click.prevent="$emit('update:modelValue', !modelValue)"
    >
      <slot name="summary" />
    </summary>
    <slot />
  </details>
</template>

// packages/sfui/frameworks/qwik/src/components/SfAccordionItem/SfAccordionItem.tsx
import { $, Slot, component$ } from '@builder.io/qwik';
import { SfAccordionItemProps } from './types';

export const SfAccordionItem = component$<SfAccordionItemProps>(
  ({ ref, open, onToggle, summaryClass, ...attributes }) => {
    const handleClick = $(() => {
      onToggle?.(!open);
    });

    return (
      <details {...(ref ? { ref } : {})} open={open} {...attributes} data-testid="accordion-item">
        <summary
          preventdefault:click
          onClick$={handleClick}
          class={[
            summaryClass,
            'list-none [&::-webkit-details-marker]:hidden cursor-pointer focus-visible:outline focus-visible:outline-offset focus-visible:outline focus-visible:rounded-sm',
          ]}
        >
          <Slot />
        </summary>
        <Slot name="detail" />
      </details>
    );
  },
);

export default SfAccordionItem;
