// packages/sfui/frameworks/vue/components/VsfDropdownMenu/VsfDropdownMenu.vue
<script lang="ts" setup>
import VsfLoaderCircular from '../VsfLoaderCircular/VsfLoaderCircular.vue';

defineProps({
  loading: {
    type: Boolean,
    default: false,
  },
});
</script>

<template>
  <ul class="vsf-dropdown-menu" role="menu" data-testid="dropdown-menu">
    <slot v-if="loading" name="loader">
      <div class="vsf-dropdown-menu__loader" data-testid="dropdown-menu-loader">
        <VsfLoaderCircular />
      </div>
    </slot>
    <slot v-else data-testid="dropdown-menu-content" />
  </ul>
</template>

// packages/sfui/frameworks/react/components/VsfDropdownMenu/VsfDropdownMenu.tsx
import classNames from 'classnames';
import VsfLoaderCircular from '../VsfLoaderCircular/VsfLoaderCircular';
import type { VsfDropdownMenuProps } from './types';

export default function VsfDropdownMenu({
  className,
  loading,
  children,
  slotLoader,
  ...attributes
}: VsfDropdownMenuProps): JSX.Element {
  return (
    <ul className={classNames('vsf-dropdown-menu', className)} {...attributes} role="menu" data-testid="dropdown-menu">
      {(loading &&
        (slotLoader || (
          <div className="vsf-dropdown-menu__loader" data-testid="dropdown-menu-loader">
            <VsfLoaderCircular />
          </div>
        ))) ||
        children}
    </ul>
  );
}
