// packages/sfui/frameworks/qwik/src/components/SfDrawer/SfDrawer.tsx
import { $, Slot, component$, useSignal } from '@builder.io/qwik';
import { SfDrawerPlacement, SfDrawerProps } from './types';

const defaultDrawerTag = 'aside';

const placementClasses = (placementValue: SfDrawerProps['placement']) => `
  ${placementValue !== SfDrawerPlacement.right ? 'left-0' : ''}
  ${placementValue !== SfDrawerPlacement.left ? 'right-0' : ''}
  ${placementValue !== SfDrawerPlacement.bottom ? 'top-0' : ''}
  ${placementValue !== SfDrawerPlacement.top ? 'bottom-0' : ''}
`;

export const SfDrawer = component$<SfDrawerProps>(
  ({
    as,
    ref,
    open,
    placement = SfDrawerPlacement.left,
    disableClickAway,
    disableEsc,
    onClose$,
    class: _class,
    ...attributes
  }) => {
    const Tag = as || defaultDrawerTag;
    const drawerRef = useSignal<Element>();

    // TODO
    // useClickAway(drawerRef, () => {
    //   if (disableClickAway) return;
    //   onClose?.();
    // });

    const onKeyDown = $((event: KeyboardEvent) => {
      if (disableEsc) return;
      if (event.key === 'Escape') {
        onClose$?.();
      }
    });

    return open ? (
      <Tag
        ref={ref ? ref : drawerRef}
        className={`fixed ${placementClasses(placement)} ${_class}`}
        tabIndex="-1"
        data-testid="drawer"
        {...attributes}
        onKeyDown$={onKeyDown}
      >
        <Slot />
      </Tag>
    ) : null;
  },
);

// packages/sfui/frameworks/vue/components/SfDrawer/SfDrawer.vue
<script lang="ts" setup>
import { type PropType, ref, toRefs, computed } from 'vue';
import { onClickOutside } from '@vueuse/core';
import { SfDrawerPlacement } from '@storefront-ui/vue';

const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false,
  },
  placement: {
    type: String as PropType<`${SfDrawerPlacement}`>,
    default: SfDrawerPlacement.left,
  },
  tag: {
    type: String,
    default: '',
  },
  disableClickAway: {
    type: Boolean,
    default: false,
  },
  disableEsc: {
    type: Boolean,
    default: false,
  },
});

const { disableClickAway, disableEsc, placement } = toRefs(props);
const emit = defineEmits<{
  (event: 'update:modelValue', isOpen: boolean): void;
}>();

const drawerRef = ref();

onClickOutside(drawerRef, () => {
  if (disableClickAway.value) return;
  emit('update:modelValue', false);
});

const onEscKeyDown = () => {
  if (disableEsc.value) return;
  emit('update:modelValue', false);
};

const placementClasses = computed(() => ({
  'left-0': placement.value !== SfDrawerPlacement.right,
  'right-0': placement.value !== SfDrawerPlacement.left,
  'top-0': placement.value !== SfDrawerPlacement.bottom,
  'bottom-0': placement.value !== SfDrawerPlacement.top,
}));
</script>

<template>
  <component
    :is="tag || 'aside'"
    v-if="modelValue"
    ref="drawerRef"
    class="fixed"
    :class="placementClasses"
    data-testid="drawer"
    tabindex="-1"
    @keydown.esc="onEscKeyDown"
  >
    <slot />
  </component>
</template>
