// shared/src/components/SfCheckbox/SfCheckbox.vue
<template>
  <div class="grid max-w-xs grid-cols-[24px_1fr] gap-x-2.5">
    <input
      id="checkbox-left"
      v-focus
      :indeterminate="indeterminate"
      type="checkbox"
      :name="name"
      :value="value"
      :required="required"
      :disabled="disabled"
      class="peer w-[18px] h-[18px] border border-2 border-gray-500 rounded-sm appearance-none cursor-pointer hover:border-primary-500 checked:bg-checked-checkbox checked:border-primary-500 disabled:border-gray-500/50 disabled:cursor-not-allowed invalid:border-negative-600 outline-violet"
      :class="{'bg-indeterminate-checkbox border-primary-500': indeterminate}"
    >
    <label
      for="checkbox-left"
      class="text-gray-900 cursor-pointer font-body peer-required:after:content-['*'] peer-disabled:text-gray-900/40 peer-disabled:cursor-not-allowed"
    >Label</label>
    <span class="hidden col-start-2 mt-1 text-sm font-medium peer-invalid:block text-negative-600 font-body">Error message</span>
    <span class="col-start-2 mt-1 text-xs text-gray-500 peer-disabled:text-gray-500/50 font-body">Help text</span>
    <span class="hidden col-start-2 mt-1 text-xs text-gray-500 peer-required:block font-body">*Required</span>
  </div>
</template>
<script>
import { focus } from '../../utils/focus-directive.js'

export default {
  directives: {
    focus
  },
  props: {
    name: {
      type: String,
      required: true,
    },
    value: {
      type: [String, Boolean],
      default: "",
    },
    required: {
      type: Boolean,
      default: false,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    indeterminate: {
      type: Boolean,
      default: false,
    },
  }
}
</script>

// packages/sfui/frameworks/qwik/src/components/SfCheckbox/SfCheckbox.tsx
import { component$ } from '@builder.io/qwik';
import { SfCheckboxProps } from './types';

export const SfCheckbox = component$<SfCheckboxProps>(({ invalid, class: _class, ref, ...attributes }) => (
  <input
    {...(ref ? { ref } : {})}
    class={{
      'h-[18px] min-w-[18px] border-2 rounded-sm appearance-none cursor-pointer text-gray-500 enabled:hover:border-primary-800 enabled:active:border-primary-900 enabled:hover:checked:text-primary-800 enabled:hover:indeterminate:text-primary-800 enabled:active:checked:text-primary-900 enabled:checked:text-primary-700 checked:bg-checked-checkbox-current border-current indeterminate:bg-indeterminate-checkbox-current enabled:indeterminate:text-primary-700 disabled:text-gray-300 hover:text-gray-300 disabled:cursor-not-allowed enabled:focus-visible:outline enabled:focus-visible:outline-offset':
        true,
      'border-negative-700 enabled:hover:border-negative-800 enabled:active:border-negative-900': invalid,
      _class: true,
    }}
    type="checkbox"
    data-testid="checkbox"
    {...attributes}
  />
));
