// packages/sfui/frameworks/react/components/SfRatingButton/SfRatingButton.tsx
import { useState, type ChangeEvent } from 'react';
import {
  SfIconStar,
  SfIconStarFilled,
  SfIconSize,
  SfRatingButtonSize,
  type SfRatingButtonProps,
  type SfRatingButtonRenderProps,
} from '@storefront-ui/react';

function defaultLabelText(value: number) {
  return `${value} Star${value !== 1 ? 's' : ''}`;
}

const renderDefaultIcon = ({ isFilled, iconSize }: SfRatingButtonRenderProps) => {
  if (isFilled) {
    return (
      <SfIconStarFilled
        role="none"
        className="text-primary-700 cursor-pointer peer-disabled:cursor-default peer-disabled:text-disabled-500 peer-focus-visible:outline"
        size={iconSize}
      />
    );
  }
  return (
    <SfIconStar
      data-testid="ratingbutton-icon-empty"
      role="none"
      className="text-neutral-500 cursor-pointer peer-disabled:cursor-default peer-disabled:text-disabled-500 peer-focus-visible:outline"
      size={iconSize}
    />
  );
};

const iconSize: Record<SfRatingButtonSize, SfRatingButtonRenderProps['iconSize']> = {
  [SfRatingButtonSize.sm]: SfIconSize.base,
  [SfRatingButtonSize.base]: SfIconSize.lg,
  [SfRatingButtonSize.lg]: SfIconSize.xl,
};

export default function SfRatingButton({
  onChange,
  value = 0,
  disabled = false,
  max = 5,
  name = 'sf-rating-button',
  label = 'Rating',
  labelClassName,
  size = SfRatingButtonSize.base,
  getLabelText = defaultLabelText,
  children = renderDefaultIcon,
  ...attributes
}: SfRatingButtonProps): JSX.Element {
  const [hoverValue, setHoverValue] = useState(0);
  const icons = Array.from({ length: Math.floor(Math.abs(max)) }, (_, index) => index + 1);
  const isIconFilled = (ratingValue: number) => ratingValue <= hoverValue || (hoverValue === 0 && ratingValue <= value);

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    onChange?.(Number(event.target.value));
  };

  const handleHoverIn = (ratingValue: number) => () => {
    if (!disabled) {
      setHoverValue(ratingValue);
    }
  };

  const handleHoverOut = () => {
    if (!disabled) {
      setHoverValue(0);
    }
  };

  return (
    <fieldset disabled={disabled} data-testid="ratingbutton" {...attributes}>
      <legend className={labelClassName}>{label}</legend>
      <div className="flex">
        {icons.map((ratingValue) => (
          <label key={ratingValue} onMouseEnter={handleHoverIn(ratingValue)} onMouseLeave={handleHoverOut}>
            <input
              type="radio"
              name={name}
              value={ratingValue}
              checked={ratingValue === value}
              onChange={handleChange}
              disabled={disabled}
              aria-label={getLabelText(ratingValue)}
              className="sr-only peer"
            />
            {children({ isFilled: isIconFilled(ratingValue), max, iconSize: iconSize[size] })}
          </label>
        ))}
      </div>
    </fieldset>
  );
}

// packages/sfui/frameworks/vue/components/SfRatingButton/SfRatingButton.vue
<script lang="ts" setup>
import { type PropType, computed, ref, toRefs } from 'vue';
import {
  SfIconStar,
  SfIconStarFilled,
  SfIconSize,
  SfRatingButtonSize,
  type SfRatingButtonIconSize,
} from '@storefront-ui/vue';

const props = defineProps({
  modelValue: {
    type: Number,
    default: 0,
  },
  max: {
    type: Number,
    default: 5,
  },
  disabled: {
    type: Boolean,
    default: false,
  },
  name: {
    type: String,
    default: 'sf-rating-button',
  },
  label: {
    type: String,
    default: 'Rating',
  },
  labelClassName: {
    type: String,
    default: 'Rating',
  },
  size: {
    type: String as PropType<`${SfRatingButtonSize}`>,
    default: SfRatingButtonSize.base,
  },
  getLabelText: {
    type: Function as PropType<(value: number) => string>,
    default: (value: number) => `${value} Star${value !== 1 ? 's' : ''}`,
  },
});

const emit = defineEmits<{
  (e: 'update:modelValue', val: number): void;
}>();

const { max, disabled, modelValue } = toRefs(props);
const hoverModel = ref(0);
const icons = computed(() => Array.from({ length: Math.floor(Math.abs(max.value)) }, (_, index) => index + 1));
const isIconFilled = (ratingValue: number) =>
  ratingValue <= hoverModel.value || (hoverModel.value === 0 && ratingValue <= modelValue.value);
const iconSize: Record<SfRatingButtonSize, SfRatingButtonIconSize> = {
  [SfRatingButtonSize.sm]: SfIconSize.base,
  [SfRatingButtonSize.base]: SfIconSize.lg,
  [SfRatingButtonSize.lg]: SfIconSize.xl,
};

const handleChange = (event: Event) => {
  if (event?.target && event.target instanceof HTMLInputElement) {
    emit('update:modelValue', Number(event.target.value));
  }
};

const handleHoverIn = (ratingValue: number) => {
  if (!disabled.value) {
    hoverModel.value = ratingValue;
  }
};

const handleHoverOut = () => {
  if (!disabled.value) {
    hoverModel.value = 0;
  }
};
</script>

<template>
  <filedset class="flex" data-testid="ratingbutton">
    <legend :class="labelClassName">{{ label }}</legend>
    <label
      v-for="ratingValue in icons"
      :key="ratingValue"
      @mouseenter="handleHoverIn(ratingValue)"
      @mouseleave="handleHoverOut"
    >
      <input
        type="radio"
        class="sr-only peer"
        :name="name"
        :value="ratingValue"
        :checked="ratingValue === modelValue"
        :disabled="disabled"
        :aria-label="getLabelText(ratingValue)"
        @change="handleChange"
      />
      <slot :is-filled="isIconFilled(ratingValue)" :icon-size="iconSize[size]" :max="max">
        <SfIconStarFilled
          v-if="isIconFilled(ratingValue)"
          data-testid="ratingbutton-icon-filled"
          role="none"
          class="text-primary-700 cursor-pointer peer-disabled:cursor-default peer-disabled:text-disabled-500 peer-focus-visible:outline"
          :size="iconSize[size]"
        />
        <SfIconStar
          v-else
          data-testid="ratingbutton-icon-empty"
          role="none"
          class="text-neutral-500 cursor-pointer peer-disabled:cursor-default peer-disabled:text-disabled-500 peer-focus-visible:outline"
          :size="iconSize[size]"
        />
      </slot>
    </label>
  </filedset>
</template>
