// apps/preview/next/pages/showcases/Chip/Deletable.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { SfChip, SfThumbnail, SfIconCloseSm } from '@storefront-ui/react';
import { useState } from 'react';

const chipValues = [
  { label: 'Red', value: 'red' },
  { label: 'Blue', value: 'blue' },
  { label: 'Gray', value: 'gray' },
];

export default function DeletableChips() {
  const [chipList, setChipList] = useState(chipValues);
  const handleRemoveChip = (val: string) => {
    const newList = chipList.filter((item) => item.value !== val);

    setChipList(newList);
  };
  return (
    <ul className="flex flex-wrap gap-4 sm:flex-row">
      {chipList.map(({ label, value }) => (
        <li>
          <SfChip
            key={value}
            className="mr-2"
            inputProps={{ checked: true, onChange: () => handleRemoveChip(value) }}
            slotPrefix={<SfThumbnail className={`bg-${value}-500`} />}
            slotSuffix={
              <SfIconCloseSm className="text-neutral-500 hover:text-primary-800 active:text-primary-900 disabled:opacity-20" />
            }
          >
            {label}
          </SfChip>
        </li>
      ))}
    </ul>
  );
}

// #endregion source

DeletableChips.getLayout = ShowcasePageLayout;

// apps/preview/qwik-city/src/routes/showcases/Chip/Deletable/index.tsx
import { SfChip, SfIconCloseSm, SfThumbnail } from '@storefront-ui/qwik';
import { $, component$, useSignal } from '@builder.io/qwik';

export default component$(() => {
  const chipValues = [
    { label: 'Red', value: 'red' },
    { label: 'Blue', value: 'blue' },
    { label: 'Gray', value: 'gray' },
  ];
  const chipListSignal = useSignal(chipValues);
  const handleRemoveChip = $((val: string) => {
    chipListSignal.value = chipListSignal.value.filter((item) => item.value !== val);
  });

  return (
    <ul class="flex flex-wrap gap-4 sm:flex-row">
      {chipListSignal.value.map(({ label, value }) => (
        <li key={value}>
          <SfChip
            key={value}
            class="mr-2"
            inputProps={{ checked: true, onChange$: $(() => handleRemoveChip(value)) }}
            showSlotPrefix={true}
            showSlotSuffix={true}
          >
            <div q:slot="prefix">
              <SfThumbnail class={`bg-${value}-500`} />
            </div>
            {label}
            <div q:slot="suffix">
              <SfIconCloseSm class="text-neutral-500 hover:text-primary-800 active:text-primary-900 disabled:opacity-20" />
            </div>
          </SfChip>
        </li>
      ))}
    </ul>
  );
});
