// apps/preview/next/pages/showcases/Fieldset/RadioLeading.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { useState } from 'react';
import { SfFieldset, SfRadio, SfButton } from '@storefront-ui/react';

const radio = [
  {
    label: 'Label',
    hint: 'hint',
    value: 'value-1',
  },
  {
    label: 'Label',
    hint: 'hint',
    value: 'value-2',
  },
  {
    label: 'Label',
    hint: 'hint',
    value: 'value-3',
  },
  {
    label: 'Label',
    hint: 'hint',
    value: 'value-4',
  },
  {
    label: 'Label',
    hint: 'hint',
    value: 'value-5',
  },
];

export default function RadioLeading() {
  const [invalid, setInvalid] = useState(false);

  return (
    <div>
      <SfFieldset legend="Label" hintText="Hint" invalid={invalid} errorText="Error message">
        <span className="flex flex-wrap justify-between">
          {radio.map(({ label, hint, value }) => (
            <label key={value} className="typography-text-base flex flex-wrap mb-1 items-center cursor-pointer">
              <SfRadio value={value} className="m-0.5" invalid={invalid} />
              <span className="ml-1">{label}</span>
              <span className="block typography-text-xs ml-8 text-neutral-500 flex-[100%]">{hint}</span>
            </label>
          ))}
        </span>
      </SfFieldset>
      <SfButton onClick={() => setInvalid(!invalid)}>Invalid</SfButton>
    </div>
  );
}

// #endregion source
RadioLeading.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Group/RadioLeading.vue
<template>
  <SfGroup
    :invalid="invalid"
    hint="Main hint"
  >
    <span class="flex justify-between">
      <label
        v-for="({label, hint, value}, i) in checkboxes" :key="i"
        class="text-base text-gray-900 cursor-pointer font-body "
      >
        <SfRadio
        v-model="modelValue"
        :value="value"
        :array="checkboxes"
        :invalid="invalid"
        class="peer"/>
        {{ label }}
        <span class="block" >
          {{ hint }}
        </span>
      </label>
    </span>
  </SfGroup>
  <SfButton @click="invalid = !invalid">Invalid</SfButton>
</template>
<script lang="ts" setup>
import { SfRadio, SfGroup, SfButton } from '@storefront-ui/vue';
import { ref } from 'vue';

const checkboxes = [
  {
    label: 'Label',
    hint: 'hint',
    value: 'value-1'
  },
  {
    label: 'Label',
    hint: 'hint',
    value: 'value-2'
  },{
    label: 'Label',
    hint: 'hint',
    value: 'value-3'
  },{
    label: 'Label',
    hint: 'hint',
    value: 'value-4'
  },{
    label: 'Label',
    hint: 'hint',
    value: 'value-5'
  },
]

const modelValue = ref('');
const invalid = ref(false);


</script>
