// apps/preview/next/pages/showcases/Badge/BadgePlacement.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { SfBadge, SfButton, SfIconShoppingCart } from '@storefront-ui/react';

export default function BadgePlacement() {
  return (
    <div className="flex gap-3">
      <SfButton className="relative" square variant="tertiary">
        <SfIconShoppingCart />
        <SfBadge content={100} max={99} placement="top-right" />
      </SfButton>

      <SfButton className="relative" square variant="tertiary">
        <SfIconShoppingCart />
        <SfBadge content={100} max={99} placement="bottom-right" />
      </SfButton>

      <SfButton className="relative" square variant="tertiary">
        <SfIconShoppingCart />
        <SfBadge content={100} max={99} placement="top-left" />
      </SfButton>

      <SfButton className="relative" square variant="tertiary">
        <SfIconShoppingCart />
        <SfBadge content={100} max={99} placement="bottom-left" />
      </SfButton>
    </div>
  );
}

// #endregion source
BadgePlacement.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Badge/BadgePlacement.vue
<template>
  <div class="flex gap-3">
    <SfButton class="relative" square variant="tertiary">
      <SfIconShoppingCart />
      <SfBadge :content="content" :max="99" placement="top-right" />
    </SfButton>

    <SfButton class="relative" square variant="tertiary">
      <SfIconShoppingCart />
      <SfBadge :content="content" :max="99" placement="bottom-left" />
    </SfButton>

    <SfButton class="relative" square variant="tertiary">
      <SfIconShoppingCart />
      <SfBadge :content="content" :max="99" placement="top-left" />
    </SfButton>

    <SfButton class="relative" square variant="tertiary">
      <SfIconShoppingCart />
      <SfBadge :content="content" :max="99" placement="bottom-right" />
    </SfButton>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { SfBadge, SfButton, SfIconShoppingCart } from '@storefront-ui/vue';

const content = ref(100);
</script>
