// packages/sfui/frameworks/react/components/VsfFooter/VsfFooterColumn.tsx
import classNames from 'classnames';
import { VsfFooterColumnType } from '@sfui/sfui/shared/types';
import { VsfFooterColumnProps } from './types';

export default function VsfFooterColumn({ type = VsfFooterColumnType.top, children, className }: VsfFooterColumnProps) {
  return <div className={classNames(`vsf-footer__column--${type}`, className)}>{children}</div>;
}

// packages/sfui/frameworks/vue/components/VsfFooter/VsfFooterColumn.vue
<script setup lang="ts">
import { PropType } from 'vue';
import { VsfFooterColumnType } from '@sfui/shared/types';

defineProps({
  type: {
    type: String as PropType<VsfFooterColumnType>,
    default: VsfFooterColumnType.top,
  },
});
</script>

<template>
  <div :class="`vsf-footer__column--${type}`"><slot /></div>
</template>
