// packages/sfui/frameworks/vue/components/VsfRating/VsfRating.vue
<script lang="ts" setup>
import { computed, PropType, toRefs } from 'vue';
import { VsfRatingSizes, VsfRatingVariants } from './types';
import { VsfIconStar, VsfIconStarOutline, VsfIconStarPartiallyFilled } from '../../components/VsfIcons';
import { clamp, roundToNearest } from '@sfui/sfui/shared/utils/index';

const props = defineProps({
  size: {
    type: String as PropType<VsfRatingSizes>,
    default: VsfRatingSizes.base,
  },
  variant: {
    type: String as PropType<VsfRatingVariants>,
    default: VsfRatingVariants.base,
  },
  max: {
    type: Number,
    default: 5,
  },
  value: {
    type: Number,
    default: 0,
  },
  halfIncrement: {
    type: Boolean,
    default: false,
  },
});
const precision = computed(() => (props.halfIncrement ? 0.5 : 1));
const { value, max } = toRefs(props);

const ratingValue = computed(() => clamp(roundToNearest(value.value, precision.value), 0, max.value));
const partiallyFilled = computed(() => Number(!Number.isInteger(ratingValue.value)));
const filled = computed(() => Math.ceil(ratingValue.value - partiallyFilled.value));
const empty = computed(() => max.value - filled.value - partiallyFilled.value);

const classes = computed(() => [
  'vsf-rating',
  {
    'vsf-rating--xs': props.size === VsfRatingSizes.xs,
    'vsf-rating--sm': props.size === VsfRatingSizes.sm,
    'vsf-rating--base': props.size === VsfRatingSizes.base,
    'vsf-rating--lg': props.size === VsfRatingSizes.lg,
    'vsf-rating--xl': props.size === VsfRatingSizes.xl,
  },
]);
</script>

<template>
  <div role="img" :ariaLabel="`Rating: ${value} out of ${max} stars`" :class="classes">
    <template v-if="variant === 'withValue'">
      <VsfIconStar aria-hidden="true" class="vsf-rating__star-filled" />
      <span class="vsf-rating__value">{{ value }}</span>
    </template>
    <template v-else>
      <VsfIconStar v-for="index in filled" :key="index" aria-hidden="true" class="vsf-rating__star-filled" />
      <VsfIconStarPartiallyFilled v-if="partiallyFilled" aria-hidden="true" class="vsf-rating__star-partial" />
      <VsfIconStarOutline v-for="index in empty" :key="index" aria-hidden="true" class="vsf-rating__star-empty" />
    </template>
  </div>
</template>

// packages/sfui/frameworks/react/components/VsfRating/VsfRating.tsx
import { clamp, roundToNearest } from '@sfui/sfui/shared/utils';
import classNames from 'classnames';
import { VsfIconStar, VsfIconStarOutline, VsfIconStarPartiallyFilled } from '../VsfIcons';
import { VsfRatingSizes, VsfRatingVariants } from './types';
import type { VsfRatingProps } from './types';

export default function VsfRating({
  size = VsfRatingSizes.base,
  variant = VsfRatingVariants.base,
  max = 5,
  value = 0,
  halfIncrement,
  className,
  ...attributes
}: VsfRatingProps) {
  let precision = 1;
  // currently component supports only full/half stars, but this logic might be useful in more complex future cases
  if (halfIncrement) {
    precision = 0.5;
  }
  // round value to the nearest step value
  const ratingValue = clamp(roundToNearest(value, precision), 0, max);

  const partiallyFilled = Number(!Number.isInteger(ratingValue)); // 0 or 1

  const filled = Math.ceil(ratingValue - partiallyFilled);

  const empty = max - filled - partiallyFilled;

  const classes = classNames(
    'vsf-rating',
    {
      'vsf-rating--xs': size === VsfRatingSizes.xs,
      'vsf-rating--sm': size === VsfRatingSizes.sm,
      'vsf-rating--base': size === VsfRatingSizes.base,
      'vsf-rating--lg': size === VsfRatingSizes.lg,
      'vsf-rating--xl': size === VsfRatingSizes.xl,
    },
    className,
  );

  const label = `${value} out of ${max}`;

  return (
    <div role="img" className={classes} aria-label={label} {...attributes} title={label}>
      {variant === 'withValue' ? (
        <>
          <VsfIconStar aria-hidden="true" className="vsf-rating__star-filled" />
          <span className="vsf-rating__value">{value}</span>
        </>
      ) : (
        <>
          {[...Array(filled).keys()].map((key) => (
            <VsfIconStar aria-hidden="true" className="vsf-rating__star-filled" key={key} />
          ))}
          {Boolean(partiallyFilled) && (
            <VsfIconStarPartiallyFilled aria-hidden="true" className="vsf-rating__star-partial" />
          )}
          {[...Array(empty).keys()].map((key) => (
            <VsfIconStarOutline aria-hidden="true" className="vsf-rating__star-empty" key={key} />
          ))}
        </>
      )}
    </div>
  );
}
