// apps/preview/qwik-city/src/routes/showcases/Rating/RatingColors/index.tsx
import { component$ } from "@builder.io/qwik";
import { SfRating } from "@storefront-ui/qwik";

export default component$(() => {
  return (
    <div class="flex flex-col">
      <SfRating class="!text-red-600" value={4} />
      <SfRating class="!text-purple-500" value={4} />
      <SfRating class="!text-cyan-700" value={4} />
    </div>
  );
});

// apps/preview/nuxt/pages/showcases/Rating/RatingColors.vue
<template>
  <div class="flex flex-col">
    <VsfRating class="!text-red-600" :value="4" />
    <VsfRating class="!text-purple-500" :value="4" />
    <VsfRating class="!text-cyan-700" :value="4" />
  </div>
</template>

<script lang="ts" setup>
import { VsfRating } from '@storefront-ui/vue';
</script>
