// apps/preview/nuxt/pages/showcases/Button/ButtonAsLink.vue
<template>
  <div class="flex flex-col items-center space-y-4 extra-small:block extra-small:space-x-4">
    <VsfButton tag="a" href="/"> Link </VsfButton>

    <VsfButton :tag="NuxtLink" to="/"> NuxtLink </VsfButton>

    <VsfButton tag="router-link" to="/"> router-link </VsfButton>
  </div>
</template>

<script lang="ts" setup>
import { resolveComponent } from 'vue';
import { VsfButton } from '@storefront-ui/vue/components/VsfButton/index';

const NuxtLink = resolveComponent('NuxtLink');
</script>

// apps/preview/next/pages/showcases/Button/ButtonAsLink.tsx
import { VsfButton } from '@storefront-ui/react/components/VsfButton';
import Link from 'next/link';
import { ShowcasePageLayout } from '../../showcases';

export function Showcase() {
  return (
    <div className="flex flex-col items-center space-y-4 extra-small:block extra-small:space-x-4">
      <VsfButton as="a" href="/">
        Link
      </VsfButton>
      <Link href="/" passHref legacyBehavior>
        <VsfButton as="a">NextLink</VsfButton>
      </Link>
    </div>
  );
}

Showcase.getLayout = ShowcasePageLayout;
export default Showcase;
