// packages/sfui/frameworks/react/components/VsfListItemFilterCheckbox/VsfListItemFilterCheckbox.tsx
import { useState } from 'react';
import { VsfListItemMenu } from '../VsfListItemMenu';
import type { VsfListItemFilterCheckboxProps } from './types';
import { VsfListItemFilterCheckboxVariant } from './types';
import { VsfCheckbox } from '../VsfCheckbox';

export default function VsfListItemFilterCheckbox({
  label,
  counter,
  size,
  variant = VsfListItemFilterCheckboxVariant.left,
  secondaryText,
  disabled,
  className,
  truncate,
  value,
  name,
  children,
  checked,
  onChange = () => '',
  ...attributes
}: VsfListItemFilterCheckboxProps): JSX.Element {
  const [checkedState, setCheckedState] = useState(false);

  return (
    <li>
      <VsfListItemMenu
        tag="label"
        label={label}
        counter={counter}
        size={size}
        selected={checkedState}
        className={className}
        secondaryText={secondaryText}
        disabled={disabled}
        truncate={truncate}
        slotPrefix={
          variant === VsfListItemFilterCheckboxVariant.left ? (
            <VsfCheckbox
              labelTag="div"
              value={value}
              name={name}
              disabled={disabled}
              onChange={(event) => {
                setCheckedState(event.target.checked);
                onChange(event);
              }}
            />
          ) : null
        }
        slotSuffix={
          variant === VsfListItemFilterCheckboxVariant.right ? (
            <VsfCheckbox
              labelTag="div"
              value={value}
              name={name}
              disabled={disabled}
              onChange={(event) => {
                setCheckedState(event.target.checked);
                onChange(event);
              }}
            />
          ) : null
        }
        {...attributes}
      >
        {children}
      </VsfListItemMenu>
    </li>
  );
}

// packages/sfui/frameworks/vue/components/VsfListItemFilterCheckbox/VsfListItemFilterCheckbox.vue
<script lang="ts" setup>
import type { PropType } from 'vue';
import { computed, toRefs } from 'vue';
import { VsfListItemMenu } from '../VsfListItemMenu';
import { VsfCheckbox } from '../VsfCheckbox';
import { extractProps } from '../../shared/props';
import { VsfListItemFilterCheckboxVariant } from './types';

const props = defineProps({
  ...extractProps(VsfListItemMenu, ['label', 'counter', 'size', 'secondaryText', 'disabled', 'truncate'] as const),
  ...extractProps(VsfCheckbox, ['value', 'name', 'modelValue'] as const),
  variant: {
    type: String as PropType<VsfListItemFilterCheckboxVariant>,
    default: VsfListItemFilterCheckboxVariant.left,
  },
});

const { modelValue, value } = toRefs(props);

defineEmits<{
  (event: 'update:modelValue', value: boolean | string[]): void;
}>();

const isChecked = computed(() => {
  if (typeof modelValue.value === 'boolean') return modelValue.value;
  // TODO: add deep comparision for objects
  return modelValue.value.includes(value.value);
});
</script>

<template>
  <li>
    <VsfListItemMenu
      v-bind="{ label, secondaryText, counter, size, disabled, truncate }"
      tag="label"
      :selected="isChecked"
    >
      <template v-if="variant === VsfListItemFilterCheckboxVariant.left" #prefix>
        <VsfCheckbox
          label-tag="div"
          :value="value"
          :model-value="modelValue"
          @update:model-value="$emit('update:modelValue', $event)"
        />
      </template>
      <template v-if="variant === VsfListItemFilterCheckboxVariant.right" #suffix>
        <VsfCheckbox
          label-tag="div"
          :value="value"
          :model-value="modelValue"
          @update:model-value="$emit('update:modelValue', $event)"
        />
      </template>
      <slot />
      <template #secondaryText><slot name="secondaryText" /></template>
    </VsfListItemMenu>
  </li>
</template>
