// apps/preview/next/pages/showcases/Radio/RadioWithLabel.tsx
import { VsfRadio } from '@storefront-ui/react';
import { useState } from 'react';
import { ShowcasePageLayout } from '../../showcases';

const radioOptions = [
  {
    label: 'Label',
    value: 'value-1',
    name: 'radio-1',
  },
  {
    label: 'Label 2',
    value: 'value-2',
    name: 'radio-1',
  },
];
export function Showcase() {
  const [checkedState, setCheckedState] = useState('');
  return (
    <div>
      {radioOptions.map(({ label, value, name }) => (
        <label key={value} className="flex items-center mb-4 cursor-pointer">
          <VsfRadio
            name={name}
            value={value}
            checked={checkedState === value}
            onChange={(event) => {
              setCheckedState(event.target.value);
            }}
          />
          <span className="ml-2 text-base font-normal leading-6 font-body">{label}</span>
        </label>
      ))}
    </div>
  );
}

Showcase.getLayout = ShowcasePageLayout;
export default Showcase;

// apps/preview/nuxt/pages/showcases/Radio/RadioWithLabel.vue
<template>
  <label
    v-for="{ name, value, label } in radioOptions"
    :key="value"
    class="flex items-center mb-4 mr-6 rounded cursor-pointer"
  >
    <VsfRadio v-model="radioModel" :value="value" :name="name" />
    <span class="ml-2 text-base font-normal leading-6 font-body">{{ label }}</span>
  </label>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { VsfRadio } from '@storefront-ui/vue';

const radioModel = ref('');
const radioOptions = [
  {
    label: 'Label',
    value: 'value-1',
    name: 'radio-1',
  },
  {
    label: 'Label 2',
    value: 'value-2',
    name: 'radio-1',
  },
];
</script>
