// apps/preview/nuxt/pages/showcases/Textarea/TextareaDisabled.vue
<template>
  <label>
    <span class="typography-text-sm font-medium cursor-not-allowed text-disabled-900">Description</span>
    <SfTextarea
      disabled
      placeholder="Write something about yourself..."
      class="w-full !bg-disabled-100 !ring-disabled-300 !ring-1"
    />
  </label>
  <div class="flex justify-between mt-0.5">
    <div>
      <p class="typography-text-xs text-disabled-500">Do not include personal or financial information.</p>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { SfTextarea } from '@storefront-ui/vue';
</script>

// apps/preview/next/pages/showcases/Textarea/TextareaDisabled.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { SfTextarea } from '@storefront-ui/react';

export default function DisabledTextareaDemo() {
  return (
    <>
      <label>
        <span className="typography-text-sm font-medium cursor-not-allowed text-disabled-900">Description</span>
        <SfTextarea
          disabled
          placeholder="Write something about yourself..."
          className="w-full !bg-disabled-100 !ring-disabled-300 !ring-1"
        />
      </label>
      <div className="flex justify-between">
        <div>
          <p className="typography-text-xs text-disabled-500 mt-0.5">
            Do not include personal or financial information.
          </p>
        </div>
      </div>
    </>
  );
}

// #endregion source
DisabledTextareaDemo.getLayout = ShowcasePageLayout;
