// apps/preview/nuxt/pages/showcases/Textarea/TextareaCharacters.vue
<template>
  <label>
    <span class="typography-text-sm font-medium">Description</span>
    <SfTextarea
      v-model="textareaValue"
      :invalid="invalid"
      :disabled="disabled"
      :readonly="readonly"
      placeholder="Write something about yourself..."
      class="w-full block"
    />
  </label>
  <div class="flex justify-between mt-0.5">
    <div>
      <p v-if="invalid && !disabled" class="typography-text-sm text-negative-700 font-medium mt-0.5">{{ errorText }}</p>
      <p :class="'typography-hint-xs text-neutral-500'">
        {{ helpText }}
      </p>
    </div>
    <p
      v-if="characterLimit && !readonly"
      :class="[
        'typography-error-xs',
        disabled ? 'text-disabled-500' : isAboveLimit ? 'text-negative-700 font-medium' : 'text-neutral-500',
      ]"
    >
      {{ charsCount }}
    </p>
  </div>
</template>
<script lang="ts" setup>
import { ref, computed } from 'vue';
import { SfTextarea } from '@storefront-ui/vue';

const characterLimit = ref(25);
const textareaValue = ref('');
const disabled = false;
const readonly = false;
const invalid = false;
const helpText = 'Do not include personal or financial information.';
const errorText = 'Error';

const isAboveLimit = computed(() => textareaValue.value.length > characterLimit.value);
const charsCount = computed(() => characterLimit.value - textareaValue.value.length);
</script>

// apps/preview/next/pages/showcases/Textarea/TextareaCharacters.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { SfTextarea } from '@storefront-ui/react';
import classNames from 'classnames';
import { ChangeEvent, useState } from 'react';

export default function TextareaWithLimit() {
  const characterLimit = 25;
  const disabled = false;
  const readonly = false;
  const invalid = false;
  const helpText = 'Help text';
  const errorText = 'Error';

  const [value, setValue] = useState('');

  function onChange(event: ChangeEvent<HTMLTextAreaElement>) {
    setValue(event?.target.value);
  }
  const isAboveLimit = characterLimit ? value.length > characterLimit : false;
  const charsCount = characterLimit ? characterLimit - value.length : null;

  const getCharacterLimitClass = () => (isAboveLimit ? 'text-negative-700 font-medium' : 'text-neutral-500');

  return (
    <>
      <label>
        <span className="text-sm font-medium">Description</span>
        <SfTextarea
          value={value}
          placeholder="Write something about yourself..."
          invalid={invalid}
          disabled={disabled}
          onChange={onChange}
          className="w-full mt-0.5 block"
        />
      </label>
      <div className="flex justify-between mt-0.5">
        <div>
          {invalid && !disabled && (
            <p className="typography-text-sm text-negative-700 font-medium mt-0.5">{errorText}</p>
          )}
          {helpText && (
            <p className={classNames('typography-hint-xs', disabled ? 'text-disabled-500' : 'text-neutral-500')}>
              {helpText}
            </p>
          )}
        </div>
        {characterLimit && !readonly ? (
          <p className={classNames('typography-error-xs', disabled ? 'text-disabled-500' : getCharacterLimitClass())}>
            {charsCount}
          </p>
        ) : null}
      </div>
    </>
  );
}

// #endregion source
TextareaWithLimit.getLayout = ShowcasePageLayout;
