// packages/sfui/frameworks/react/components/VsfNavigationTop/VsfNavigationTop.tsx
import classNames from 'classnames';
import { useRef } from 'react';
import { useClickAway } from 'react-use';
import VsfButton, { VsfButtonVariants } from '../VsfButton';
import { VsfIconClose } from '../VsfIcons';
import { VsfNavigationTopVariant } from './types';
import type { VsfNavigationTopProps } from './types';

export default function VsfNavigationTop({
  open = false,
  onOpenChange = () => false,
  variant = VsfNavigationTopVariant.auto,
  children,
  ...attributes
}: VsfNavigationTopProps): JSX.Element {
  const navigationTopRef = useRef(null);

  useClickAway(navigationTopRef, () => {
    onOpenChange(!open);
  });

  return open ? (
    <nav className="vsf-navigation-top" ref={navigationTopRef} data-testid="navigation-top" {...attributes}>
      {/* TODO: use greyscale prop button variant */}
      <VsfButton
        icon
        variant={VsfButtonVariants.tertiary}
        className="vsf-navigation-top__close"
        data-testid="navigation-top-close-button"
        onClick={() => {
          onOpenChange(!open);
        }}
      >
        <VsfIconClose />
      </VsfButton>
      <div
        className={classNames(
          'vsf-navigation-top__wrapper',
          variant !== VsfNavigationTopVariant.none && `vsf-navigation-top__wrapper--${variant}`,
        )}
      >
        {children}
      </div>
    </nav>
  ) : (
    // eslint-disable-next-line react/jsx-no-useless-fragment
    <></>
  );
}

// packages/sfui/frameworks/vue/components/VsfNavigationTop/VsfNavigationTop.vue
<script lang="ts" setup>
import { PropType, toRefs } from 'vue';
import { ref } from 'vue';
import { onClickOutside } from '@vueuse/core';
import { VsfNavigationTopVariant } from './types';
import VsfButton, { VsfButtonVariants } from '../VsfButton';
import { VsfIconClose } from '../VsfIcons';

const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false,
  },
  variant: {
    type: String as PropType<VsfNavigationTopVariant>,
    default: VsfNavigationTopVariant.auto,
  },
});
const { modelValue } = toRefs(props);
const emit = defineEmits<{
  (e: 'update:modelValue', val: boolean): void;
}>();

const navigationTopRef = ref(null);
const onClose = () => emit('update:modelValue', !modelValue.value);

onClickOutside(navigationTopRef, onClose);
</script>

<template>
  <nav v-if="modelValue" ref="navigationTopRef" class="vsf-navigation-top" data-testid="navigation-top">
    <!-- TODO: use greyscale prop button variant -->
    <VsfButton
      icon
      :variant="VsfButtonVariants.tertiary"
      class="vsf-navigation-top__close"
      data-testid="navigation-top-close-button"
      @click="onClose"
    >
      <VsfIconClose />
    </VsfButton>
    <div
      :class="[
        'vsf-navigation-top__wrapper',
        variant !== VsfNavigationTopVariant.none && `vsf-navigation-top__wrapper--${variant}`,
      ]"
    >
      <slot />
    </div>
  </nav>
</template>
