// packages/sfui/frameworks/vue/components/SfTooltip/SfTooltip.vue
<script lang="ts" setup>
import { type PropType, toRefs } from 'vue';
import type { Middleware } from '@floating-ui/vue';
import { useTooltip, type SfPopoverPlacement, type SfPopoverStrategy } from '@storefront-ui/vue';

const props = defineProps({
  placement: {
    type: String as PropType<`${SfPopoverPlacement}` | undefined>,
    default: undefined,
  },
  middleware: {
    type: Array as PropType<Middleware[] | undefined>,
    default: undefined,
  },
  strategy: {
    type: String as PropType<`${SfPopoverStrategy}` | undefined>,
    default: undefined,
  },
  showArrow: {
    type: Boolean,
    default: false,
  },
  label: {
    type: String,
    required: true,
  },
});

const { placement, middleware, strategy } = toRefs(props);
const { isOpen, triggerProps, tooltipProps, arrowProps } = useTooltip({ placement, middleware, strategy });
</script>
<template>
  <span data-testid="tooltip" v-bind="triggerProps">
    <slot />
    <div
      v-if="label && isOpen"
      role="tooltip"
      class="bg-black px-2 py-1.5 rounded-md text-white text-xs w-max max-w-[360px] drop-shadow-sm
      v-bind="tooltipProps"
    >
      {{ label }}
      <span v-if="showArrow" v-bind="arrowProps" class="bg-black rotate-45" />
    </div>
  </span>
</template>

// packages/sfui/frameworks/react/components/SfTooltip/SfTooltip.tsx
import { useTooltip } from '@storefront-ui/react';
import type { SfTooltipProps } from '@storefront-ui/react';

export default function SfTooltip(props: SfTooltipProps) {
  const { children, label, className, style, showArrow, ...tooltipOptions } = props;
  const { isOpen, getTriggerProps, getTooltipProps, getArrowProps } = useTooltip(tooltipOptions);

  return (
    <span {...getTriggerProps({ className, style })} data-testid="tooltip">
      {children}
      {label && isOpen && (
        <div
          {...getTooltipProps({
            role: 'tooltip',
            className: 'bg-black px-2 py-1.5 rounded-md text-white text-xs w-max max-w-[360px] drop-shadow',
          })}
        >
          {label}
          {showArrow && <span {...getArrowProps({ className: 'bg-black rotate-45' })} />}
        </div>
      )}
    </span>
  );
}
