// apps/preview/nuxt/pages/showcases/Dropdown/BasicDropdown.vue
<template>
  <SfDropdown v-model="isOpen">
    <template #trigger>
      <SfButton @click="toggle()">Toggle</SfButton>
    </template>
    <ul class="p-2 rounded bg-gray-100">
      <li>More</li>
      <li>About</li>
      <li>Settings</li>
    </ul>
  </SfDropdown>
</template>

<script lang="ts" setup>
import { SfDropdown, useDisclosure, SfButton } from '@storefront-ui/vue';

const { isOpen, toggle } = useDisclosure();
</script>

// apps/preview/next/pages/showcases/Dropdown/BasicDropdown.tsx
import { ShowcasePageLayout } from '../../showcases';

// #region source
import { SfButton, SfDropdown, useDisclosure } from '@storefront-ui/react';

export default function BasicDropdown() {
  const { isOpen, toggle, close } = useDisclosure();
  return (
    <SfDropdown trigger={<SfButton onClick={toggle}>Toggle</SfButton>} open={isOpen} onClose={close}>
      <ul className="p-2 rounded-sm bg-gray-100">
        <li>More</li>
        <li>About</li>
        <li>Settings</li>
      </ul>
    </SfDropdown>
  );
}

// #endregion source
BasicDropdown.getLayout = ShowcasePageLayout;
