// packages/sfui/frameworks/react/components/VsfListItemFilterRadio/VsfListItemFilterRadio.tsx
import { VsfListItemMenu } from '../VsfListItemMenu';
import type { VsfListItemFilterRadioProps } from './types';
import { VsfListItemFilterRadioVariant } from './types';
import { VsfRadio } from '../VsfRadio';

export default function VsfListItemFilterRadio({
  label,
  counter,
  size,
  variant = VsfListItemFilterRadioVariant.left,
  secondaryText,
  disabled,
  className,
  truncate,
  selected,
  value,
  name,
  children,
  onChange = () => '',
  ...attributes
}: VsfListItemFilterRadioProps): JSX.Element {
  const toggle = (currentValue?: string, selectedValue?: string) =>
    onChange(selectedValue === currentValue ? '' : currentValue || '');

  return (
    <VsfListItemMenu
      tag="li"
      label={label}
      counter={counter}
      size={size}
      selected={selected === value}
      className={className}
      secondaryText={secondaryText}
      disabled={disabled}
      truncate={truncate}
      onClick={() => toggle(value, selected)}
      slotPrefix={
        variant === VsfListItemFilterRadioVariant.left ? (
          <VsfRadio
            checked={selected === value}
            value={value}
            name={name}
            onChange={(event) => toggle(event.target.value, selected)}
          />
        ) : null
      }
      slotSuffix={
        variant === VsfListItemFilterRadioVariant.right ? (
          <VsfRadio
            checked={selected === value}
            value={value}
            name={name}
            onChange={(event) => toggle(event.target.value, selected)}
          />
        ) : null
      }
      {...attributes}
    >
      {children}
    </VsfListItemMenu>
  );
}

// packages/sfui/frameworks/vue/components/VsfListItemFilterRadio/VsfListItemFilterRadio.vue
<script lang="ts" setup>
import VsfListItemMenu from '../VsfListItemMenu';
import VsfRadio from '../VsfRadio/VsfRadio.vue';
import { extractProps } from '../../shared/utils/props';
import { VsfListItemFilterRadioVariant } from './types';
import type { PropType } from 'vue';

const props = defineProps({
  ...extractProps(VsfListItemMenu, [
    'label',
    'counter',
    'size',
    'secondaryText',
    'disabled',
    'truncate',
    'selected',
  ] as const),
  ...extractProps(VsfRadio, ['value', 'name'] as const),
  modelValue: {
    type: String,
    default: '',
  },
  variant: {
    type: String as PropType<VsfListItemFilterRadioVariant>,
    default: VsfListItemFilterRadioVariant.left,
  },
});

defineEmits<{
  (event: 'update:modelValue', value: string): void;
}>();

const toggle = (value: string, modelValue: string) => {
  return modelValue === value ? '' : value;
};
</script>

<template>
  <VsfListItemMenu v-bind="props" tag="li" @click="$emit('update:modelValue', toggle(value, modelValue))">
    <template v-if="variant === VsfListItemFilterRadioVariant.left" #prefix>
      <VsfRadio
        :value="value"
        :model-value="modelValue"
        @click.stop="$emit('update:modelValue', toggle(value, modelValue))"
      />
    </template>
    <template v-if="variant === VsfListItemFilterRadioVariant.right" #suffix>
      <VsfRadio
        :value="value"
        :model-value="modelValue"
        @click.stop="$emit('update:modelValue', toggle(value, modelValue))"
      />
    </template>
  </VsfListItemMenu>
</template>
