// packages/sfui/frameworks/vue/components/SfScrollable/SfScrollable.vue
<script lang="ts">
export default {
  inheritAttrs: false,
};
</script>
<script lang="ts" setup>
import { computed, toRefs, type PropType, reactive } from 'vue';
import {
  SfScrollableDirection,
  SfScrollableButtonsPlacement,
  useScrollable,
  SfIconChevronLeft,
  SfIconChevronRight,
  SfButton,
  type SfScrollableOnDragChangeData,
  type SfScrollableOnScrollData,
  type SfScrollableOnPrevData,
  type SfScrollableOnNextData,
  ClassProp,
} from '@storefront-ui/vue';

const props = defineProps({
  tag: {
    type: String,
    default: 'div',
  },
  direction: {
    type: String as PropType<`${SfScrollableDirection}`>,
    default: SfScrollableDirection.horizontal,
  },
  buttonsPlacement: {
    type: String as PropType<`${SfScrollableButtonsPlacement}`>,
    default: SfScrollableButtonsPlacement.block,
  },
  wrapperClass: ClassProp,
  activeIndex: {
    type: Number,
    default: undefined,
  },
  reduceMotion: {
    type: Boolean,
    default: undefined,
  },
  drag: {
    type: Boolean,
    default: undefined,
  },
  previousDisabled: {
    type: Boolean,
    default: undefined,
  },
  nextDisabled: {
    type: Boolean,
    default: undefined,
  },
});
const emit = defineEmits<{
  (e: 'onDragChange', data: SfScrollableOnDragChangeData): void;
  (e: 'onScroll', data: SfScrollableOnScrollData): void;
  (e: 'onPrev', data: SfScrollableOnPrevData): void;
  (e: 'onNext', data: SfScrollableOnNextData): void;
}>();
const { direction, activeIndex, reduceMotion, drag } = toRefs(props);

const { getContainerRef, state, getNextButtonProps, getPrevButtonProps } = useScrollable(
  computed(() => ({
    ...reactive({
      direction,
      activeIndex,
      reduceMotion,
      drag,
    }),
    onDragChange: (data) => emit('onDragChange', data),
    onScroll: (data) => emit('onScroll', data),
    onPrev: (data) => emit('onPrev', data),
    onNext: (data) => emit('onNext', data),
  })),
);

const changeDisabledClass = (isDisabled: boolean) =>
  isDisabled ? '!ring-disabled-300 !text-disabled-500' : '!ring-neutral-500 !text-neutral-500';
const isHorizontal = computed(() => props.direction === SfScrollableDirection.horizontal);
</script>

<template>
  <div :class="['items-center', 'relative', isHorizontal ? 'flex' : 'flex-col h-full inline-flex', wrapperClass]">
    <div v-if="$slots.previousButton" v-bind="getPrevButtonProps"><slot name="previousButton" /></div>
    <SfButton
      v-else-if="buttonsPlacement"
      variant="secondary"
      size="lg"
      square
      :class="[
        '!rounded-full bg-white hidden md:block',
        isHorizontal ? 'mr-4' : 'mb-4 rotate-90',
        isHorizontal && SfScrollableButtonsPlacement.floating ? 'left-4' : 'top-4 rotate-90',
        { 'absolute z-10': SfScrollableButtonsPlacement.floating },
        changeDisabledClass(typeof previousDisabled === 'boolean' ? previousDisabled : getPrevButtonProps.disabled),
      ]"
      v-bind="getPrevButtonProps"
      :disabled="previousDisabled"
    >
      <SfIconChevronLeft />
    </SfButton>
    <component
      :is="tag"
      ref="getContainerRef"
      :class="[
        'motion-safe:scroll-smooth',
        {
          'overflow-x-auto flex gap-4': isHorizontal,
          'overflow-y-auto flex flex-col gap-4': !isHorizontal,
          'cursor-grab': state.isDragged,
        },
      ]"
      v-bind="{ ...$attrs, ...props }"
      :disabled="previousDisabled"
    >
      <slot />
    </component>
    <div v-if="$slots.nextButton" v-bind="getNextButtonProps"><slot name="nextButton" /></div>
    <SfButton
      v-else-if="buttonsPlacement"
      variant="secondary"
      size="lg"
      square
      :class="[
        '!rounded-full bg-white hidden md:block',
        isHorizontal && SfScrollableButtonsPlacement.block ? 'ml-4' : 'mt-4 rotate-90',
        isHorizontal && SfScrollableButtonsPlacement.floating ? 'right-4' : 'bottom-4 rotate-90',
        { 'absolute z-10': SfScrollableButtonsPlacement.floating },
        changeDisabledClass(typeof nextDisabled === 'boolean' ? nextDisabled : getNextButtonProps.disabled),
      ]"
      v-bind="getNextButtonProps"
      :disabled="nextDisabled"
    >
      <SfIconChevronRight />
    </SfButton>
  </div>
</template>

// packages/sfui/frameworks/qwik/src/components/SfScrollable/SfScrollable.tsx
// import { component$ } from "@builder.io/qwik";
// import { SfScrollableProps } from "./types";


// const defaultScrollableTag = 'div';

// export const SfScrollable = component$<SfScrollableProps>((
//     {
//       as,
//       direction = SfScrollableDirection.horizontal,
//       buttonsPlacement = SfScrollableButtonsPlacement.block,
//       activeIndex,
//       reduceMotion,
//       drag,
//       onDragChange,
//       onScroll,
//       onPrev,
//       onNext,
//       className,
//       wrapperClassNames,
//       previousDisabled,
//       nextDisabled,
//       style,
//       children,
//       slotPreviousButton,
//       slotNextButton,
//       ...attributes
//     }
//   ) => {
//     const Tag = as || defaultScrollableTag;

//     const sliderOptions = useMemo(
//       () => ({
//         direction,
//         activeIndex,
//         reduceMotion,
//         drag,
//         onDragChange,
//         onScroll,
//         onPrev,
//         onNext,
//       }),
//       [direction, activeIndex, reduceMotion, drag, onDragChange, onScroll, onPrev, onNext],
//     );

//     const { getContainerProps, state, getNextButtonProps, getPrevButtonProps } = useScrollable(sliderOptions);

//     const changeDisabledClass = (isDisabled: boolean) =>
//       isDisabled ? '!ring-disabled-300 !text-disabled-500' : '!ring-neutral-500 !text-neutral-500';
//     const previousButton = (...buttonClassName: Parameters<typeof classNames>) =>
//       (slotPreviousButton && cloneElement(slotPreviousButton, getPrevButtonProps())) || (
//         <SfButton
//           variant="secondary"
//           size="lg"
//           className={classNames(
//             'hidden md:block',
//             buttonClassName,
//             changeDisabledClass(
//               typeof previousDisabled === 'boolean' ? previousDisabled : getPrevButtonProps().disabled,
//             ),
//           )}
//           square
//           slotPrefix={<SfIconChevronLeft />}
//           {...getPrevButtonProps()}
//           disabled={previousDisabled}
//         />
//       );

//     const nextButton = (...buttonClassName: Parameters<typeof classNames>) =>
//       (slotNextButton && cloneElement(slotNextButton, getNextButtonProps())) || (
//         <SfButton
//           variant="secondary"
//           size="lg"
//           square
//           className={classNames(
//             'hidden md:block',
//             buttonClassName,
//             changeDisabledClass(typeof nextDisabled === 'boolean' ? nextDisabled : getNextButtonProps().disabled),
//           )}
//           slotPrefix={<SfIconChevronRight />}
//           {...getNextButtonProps()}
//           disabled={nextDisabled}
//         />
//       );

//     const isHorizontal = direction === SfScrollableDirection.horizontal;

//     return (
//       <div
//         className={classNames(
//           'items-center relative',
//           isHorizontal ? 'flex' : 'flex-col h-full inline-flex',
//           wrapperClassNames,
//         )}
//       >
//         {buttonsPlacement === SfScrollableButtonsPlacement.block &&
//           previousButton('!rounded-full bg-white', isHorizontal ? 'mr-4' : 'mb-4 rotate-90')}
//         <Tag
//           {...getContainerProps({
//             className: classNames(className, 'motion-safe:scroll-smooth', {
//               'overflow-x-auto flex gap-4': isHorizontal,
//               'overflow-y-auto flex flex-col gap-4': !isHorizontal,
//               'cursor-grab': state.isDragged,
//             }),
//           })}
//           {...attributes}
//         >
//           {buttonsPlacement === SfScrollableButtonsPlacement.floating &&
//             previousButton('absolute !rounded-full bg-white z-10', isHorizontal ? 'left-4' : 'top-4 rotate-90')}
//           {children}
//           {buttonsPlacement === SfScrollableButtonsPlacement.floating &&
//             nextButton('absolute !rounded-full bg-white z-10', isHorizontal ? 'right-4' : 'bottom-4 rotate-90')}
//         </Tag>
//         {buttonsPlacement === SfScrollableButtonsPlacement.block &&
//           nextButton('!rounded-full bg-white', isHorizontal ? 'ml-4' : 'mt-4 rotate-90')}
//       </div>
//     );
//   },
// );
