// apps/preview/nuxt/pages/examples/SfDropdown.vue
<template>
  <ComponentExample :controls-attrs="controlsAttrs">
    <SfDropdown v-bind="state" v-model="state.modelValue">
      <template #trigger>
        <SfButton @click="state.modelValue = !state.modelValue">Toggle</SfButton>
      </template>
      <ul class="p-2 rounded bg-gray-100">
        <li>More</li>
        <li>About</li>
        <li>Settings</li>
      </ul>
    </SfDropdown>
  </ComponentExample>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { SfDropdown, SfButton, SfPopoverPlacement, SfPopoverStrategy } from '@storefront-ui/vue';
import { prepareControls } from '../../components/utils/Controls.vue';
import ComponentExample from '../../components/utils/ComponentExample.vue';

const { controlsAttrs, state } = prepareControls(
  [
    {
      type: 'boolean',
      modelName: 'modelValue',
      propType: 'boolean',
      isRequired: true,
      description: 'Controls floating content visibility',
    },
    {
      type: 'select',
      modelName: 'placement',
      propType: 'SfPopoverPlacement',
      propDefaultValue: SfPopoverPlacement.bottom,
      options: Object.values(SfPopoverPlacement),
      description:
        'Dropdown default placement - may be automatically shifted or flipped based on screen size and dropdown position',
    },
    {
      type: 'select',
      modelName: 'strategy',
      propType: 'SfPopoverStrategy',
      propDefaultValue: SfPopoverStrategy.absolute,
      options: Object.values(SfPopoverStrategy),
      description: 'Dropdown positioning strategy',
    },
  ],
  {
    modelValue: ref(false),
    placement: ref(SfPopoverPlacement.bottom),
    strategy: ref(SfPopoverStrategy.absolute),
  },
);
</script>

// apps/preview/next/pages/examples/SfDropdown.tsx
import { SfButton, SfDropdown, SfPopoverPlacement, SfPopoverStrategy } from '@storefront-ui/react';
import { prepareControls } from '../../components/utils/Controls';
import ComponentExample from '../../components/utils/ComponentExample';
import { ExamplePageLayout } from '../examples';

function Example() {
  const { state, controls } = prepareControls(
    [
      {
        type: 'boolean',
        modelName: 'open',
        propType: 'boolean',
        isRequired: true,
        description: 'Controls floating content visibility',
      },
      {
        type: 'select',
        modelName: 'placement',
        propType: 'SfPopoverPlacement',
        propDefaultValue: SfPopoverPlacement.bottom,
        options: Object.values(SfPopoverPlacement),
        description:
          'Dropdown default placement - may be automatically shifted or flipped based on screen size and dropdown position',
      },
      {
        type: 'select',
        modelName: 'strategy',
        propType: 'SfPopoverStrategy',
        propDefaultValue: SfPopoverStrategy.absolute,
        options: Object.values(SfPopoverStrategy),
        description: 'Dropdown positioning strategy',
      },
    ],
    {
      open: false,
      placement: SfPopoverPlacement.bottom,
      strategy: SfPopoverStrategy.absolute,
    },
  );

  const close = () => state.set({ open: false });
  const toggle = () => state.set((currentState) => ({ ...currentState, open: !currentState.open }));

  return (
    <ComponentExample controls={{ state, controls }}>
      <SfDropdown
        trigger={<SfButton onClick={toggle}>Toggle</SfButton>}
        open={state.get.open}
        strategy={state.get.strategy}
        placement={state.get.placement}
        onClose={close}
      >
        <ul className="p-2 rounded-sm bg-gray-100">
          <li>More</li>
          <li>About</li>
          <li>Settings</li>
        </ul>
      </SfDropdown>
    </ComponentExample>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;
