// apps/preview/qwik-city/src/routes/examples/SfThumbnail/index.tsx
import { component$, useContext, useTask$ } from '@builder.io/qwik';
import { ComponentExample } from '~/components/utils/ComponentExample';
import { ControlsType } from '~/components/utils/types';
import { EXAMPLES_STATE } from '../layout';
import { SfThumbnail, SfThumbnailSize } from '@storefront-ui/qwik';

export default component$(() => {
  const examplesState = useContext(EXAMPLES_STATE);

  useTask$(() => {
    examplesState.data = {
      controls: [
        {
          type: 'select',
          modelName: 'size',
          options: Object.keys(SfThumbnailSize),
          propDefaultValue: SfThumbnailSize.base,
          description: 'Component size',
          propType: 'SfThumbnailSize',
        },
      ] satisfies ControlsType,
      state: {
        size: SfThumbnailSize.base,
      },
    };
  });

  return (
    <ComponentExample>
      <SfThumbnail {...examplesState.data.state} class="bg-gradient-to-tr from-[#4ADE80] to-[#A78BFA]" />
    </ComponentExample>
  );
});

// apps/preview/next/pages/examples/SfThumbnail.tsx
import { SfThumbnail, SfThumbnailSize } from '@storefront-ui/react';
import { prepareControls } from '../../components/utils/Controls';
import ComponentExample from '../../components/utils/ComponentExample';
import { ExamplePageLayout } from '../examples';

function Example() {
  const { state, controls } = prepareControls(
    [
      {
        type: 'select',
        modelName: 'size',
        options: Object.keys(SfThumbnailSize),
        propDefaultValue: SfThumbnailSize.base,
        description: 'Component size',
        propType: 'SfThumbnailSize',
      },
    ],
    {
      size: SfThumbnailSize.base,
    },
  );

  return (
    <ComponentExample controls={{ state, controls }}>
      <SfThumbnail {...state.get} className="bg-gradient-to-tr from-[#4ADE80] to-[#A78BFA]" />
    </ComponentExample>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;
