// apps/preview/nuxt/pages/examples/VsfDropdownMenu.vue
<template>
  <div class="e-page">
    <div class="e-page-component">
      <VsfDropdownMenu :loading="loading" class="w-80" role="listbox" aria-label="Items choice">
        <VsfListItemMenu v-for="item of items" :key="`item-${item}`" :secondary-text="item.secondaryText" role="option">
          {{ item.label }}
          <template #prefix>
            <VsfIconCircle />
          </template>
        </VsfListItemMenu>
        <VsfDivider />
        <VsfListItemMenu v-for="item of items" :key="`item-${item}`" :secondary-text="item.secondaryText" role="option">
          {{ item.label }}
          <template #prefix>
            <VsfIconCircle />
          </template>
        </VsfListItemMenu>
      </VsfDropdownMenu>
    </div>
    <div class="e-page-controls">
      <Controls v-bind="controlsAttrs" />
    </div>
  </div>
</template>

<script lang="ts">
import { ref, onMounted } from 'vue';
import VsfDropdownMenu from '@storefront-ui/vue/components/VsfDropdownMenu/VsfDropdownMenu.vue';
import VsfListItemMenu from '@storefront-ui/vue/components/VsfListItemMenu/VsfListItemMenu.vue';
import VsfIconCircle from '@storefront-ui/vue/components/VsfIcons/VsfIconCircle.vue';
import VsfDivider from '@storefront-ui/vue/components/VsfDivider/VsfDivider.vue';
import Controls, { prepareControls } from '../../components/utils/Controls.vue';

export default {
  name: 'VsfDropdownMenuExample',
  components: {
    Controls,
    VsfDropdownMenu,
    VsfListItemMenu,
    VsfIconCircle,
    VsfDivider,
  },
  setup() {
    const items = [
      {
        label: 'item1',
        secondaryText: 'item description',
      },
      {
        label: 'item2',
        secondaryText: 'item description',
      },
      {
        label: 'item3',
        secondaryText: 'item description',
      },
      {
        label: 'item4',
        secondaryText: 'item description',
      },
      {
        label: 'item5',
        secondaryText: 'item description',
      },
    ];
    let loadingState = ref(true);
    onMounted(() => {
      setTimeout(() => {
        loadingState.value = false;
      }, 3000);
    });
    return {
      ...prepareControls(
        [
          {
            type: 'boolean',
            modelName: 'loading',
            description: 'sets displaying loader when loading content',
            propDefaultValue: 'false',
          },
        ],
        {
          loading: loadingState,
          items: items,
        },
      ),
    };
  },
};
</script>

// apps/preview/next/pages/examples/VsfDropdownMenu.tsx
import VsfDropdownMenu from '@storefront-ui/react/components/VsfDropdownMenu/VsfDropdownMenu';
import VsfListItemMenu from '@storefront-ui/react/components/VsfListItemMenu/VsfListItemMenu';
import VsfIconCircle from '@storefront-ui/react/components/VsfIcons/VsfIconCircle';
import VsfDivider from '@storefront-ui/react/components/VsfDivider/VsfDivider';
import { useEffect, useState } from 'react';
import Controls, { prepareControls } from '../../components/utils/Controls';
import { ExamplePageLayout } from '../examples';

function Example() {
  const items = [
    {
      label: 'item1',
      secondaryText: 'item description 1',
    },
    {
      label: 'item2',
      secondaryText: 'item description 2',
    },
    {
      label: 'item3',
      secondaryText: 'item description 3',
    },
    {
      label: 'item4',
      secondaryText: 'item description 4',
    },
    {
      label: 'item5',
      secondaryText: 'item description 5',
    },
  ];

  const { state, controls } = prepareControls(
    [
      {
        type: 'boolean',
        modelName: 'loading',
        description: 'sets displaying loader when loading content',
        propDefaultValue: 'false',
      },
    ],
    {
      loading: false,
    },
  );

  const [loadingState, setLoadingState] = useState(true);
  useEffect(() => {
    setTimeout(() => {
      setLoadingState(state.get.loading);
    }, 3000);
  }, []);

  return (
    <div className="e-page">
      <div className="e-page-component">
        <VsfDropdownMenu
          loading={loadingState || state.get.loading}
          className="w-80"
          role="listbox"
          aria-label="Items choice"
        >
          {items.map((item) => (
            <VsfListItemMenu key={item.label} slotPrefix={<VsfIconCircle />} role="option">
              {item.label}
            </VsfListItemMenu>
          ))}
          <VsfDivider />
          {items.map((item) => (
            <VsfListItemMenu key={item.label} slotPrefix={<VsfIconCircle />} role="option">
              {item.label}
            </VsfListItemMenu>
          ))}
        </VsfDropdownMenu>
      </div>
      <div className="e-page-controls">
        <Controls {...{ state, controls }} />
      </div>
    </div>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;
