// apps/preview/nuxt/pages/examples/VsfDivider.vue
<template>
  <div class="e-page">
    <div class="e-page-component">
      <VsfDivider />
    </div>
    <div class="e-page-controls">
      <Controls v-bind="controlsAttrs" />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import Controls, { prepareControls } from '../../components/utils/Controls.vue';
import VsfDivider from '@sfui/sfui/frameworks/vue/components/VsfDivider/VsfDivider.vue';

export default defineComponent({
  name: 'VsfDividerExample',
  components: {
    VsfDivider,
    Controls,
  },
  setup() {
    return {
      ...prepareControls([], {}),
    };
  },
});
</script>

// apps/preview/next/pages/examples/VsfDivider.tsx
import VsfDivider from '@sfui/sfui/frameworks/react/components/VsfDivider';
import Controls, { prepareControls } from '../../components/utils/Controls';
import { ExamplePageLayout } from '../examples';

const Example = () => {
  const { state, controls } = prepareControls([], {});
  return (
    <div className="e-page">
      <div className="e-page-component">
        <VsfDivider />
      </div>
      <div className="e-page-controls">
        <Controls {...{ state, controls }} />
      </div>
    </div>
  );
};

Example.getLayout = ExamplePageLayout;
export default Example;
