// apps/preview/nuxt/pages/examples/VsfFooter.vue
<template>
  <div class="e-page">
    <div class="e-page-component">
      <VsfFooter :company-name="companyNameModel">
        <template #categories>
          <template v-for="category in categoriesModel" :key="category.label">
            <VsfFooterColumn>
              <VsfFooterLabel :type="VsfFooterLabelType.category">{{ category.label }}</VsfFooterLabel>
              <template v-for="subcategory in category?.subcategories" :key="subcategory.label">
                <VsfFooterLabel :type="VsfFooterLabelType.subcategory">
                  <component :is="linkTag(subcategory.linkTag)" v-bind="subcategory.bindings">
                    {{ subcategory.label }}
                  </component>
                </VsfFooterLabel>
              </template>
            </VsfFooterColumn>
          </template>
        </template>
        <template #contact>
          <template v-for="contactOption in contactOptionsModel" :key="contactOption.label">
            <VsfFooterColumn :type="VsfFooterColumnType.middle">
              <VsfIconHelp v-if="contactOption.iconName === 'help'" size="lg" />
              <VsfIconChat v-if="contactOption.iconName === 'chat'" size="lg" />
              <VsfIconPhone v-if="contactOption.iconName === 'phone'" size="lg" />
              <VsfFooterLabel :type="VsfFooterLabelType.contact">
                <component :is="linkTag(contactOption.linkTag)" v-bind="contactOption.bindings">
                  {{ contactOption.label }}
                </component>
              </VsfFooterLabel>
              <template v-for="detail in contactOption.details" :key="detail">
                <VsfFooterLabel :type="VsfFooterLabelType.contactDescription">{{ detail }}</VsfFooterLabel>
              </template>
            </VsfFooterColumn>
          </template>
        </template>
        <template #socialMedia>
          <template v-for="social in socialMediaModel" :key="social.label">
            <VsfFooterSocialMedia>
              <VsfFooterLabel :type="VsfFooterLabelType.socialMedia">
                <component :is="linkTag(social.linkTag)" v-bind="social.bindings">
                  <VsfIconFacebook v-if="social.label === 'Facebook'" />
                  <VsfIconTwitter v-if="social.label === 'Twitter'" />
                  <VsfIconInstagram v-if="social.label === 'Instagram'" />
                  <VsfIconPinterest v-if="social.label === 'Pinterest'" />
                  <VsfIconYoutube v-if="social.label === 'Youtube'" />
                </component>
              </VsfFooterLabel>
            </VsfFooterSocialMedia>
          </template>
        </template>
        <template #bottomLinks>
          <template v-for="bottomLink in bottomLinksModel" :key="bottomLink.label">
            <VsfFooterLabel :type="VsfFooterLabelType.bottomLinks">
              <component :is="linkTag(bottomLink.linkTag)" v-bind="bottomLink.bindings">
                {{ bottomLink.label }}
              </component>
            </VsfFooterLabel>
          </template>
        </template>
        <template #companyName>
          {{ companyNameModel }}
        </template>
      </VsfFooter>
    </div>
    <div class="e-page-controls">
      <Controls v-bind="controlsAttrs" />
    </div>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, ref, resolveComponent } from 'vue';
import VsfFooter, {
  VsfFooterColumn,
  VsfFooterSocialMedia,
  VsfFooterLabel,
} from '@sfui/sfui/frameworks/vue/components/VsfFooter/index';
import {
  VsfIconHelp,
  VsfIconChat,
  VsfIconPhone,
  VsfIconFacebook,
  VsfIconTwitter,
  VsfIconPinterest,
  VsfIconYoutube,
  VsfIconInstagram,
} from '@sfui/sfui/frameworks/vue/components/VsfIcons/index';
import type { TagOrComponent } from '@sfui/sfui/frameworks/vue/utils/types';
import { VsfFooterLabelType, VsfFooterColumnType } from '@sfui/sfui/shared/types/index';
import Controls, { prepareControls } from '../../components/utils/Controls.vue';

export default defineComponent({
  name: 'VsfFooterExample',
  components: {
    VsfFooter,
    VsfFooterColumn,
    VsfFooterLabel,
    VsfFooterSocialMedia,
    Controls,
    VsfIconHelp,
    VsfIconChat,
    VsfIconPhone,
    VsfIconFacebook,
    VsfIconTwitter,
    VsfIconPinterest,
    VsfIconYoutube,
    VsfIconInstagram,
    VsfFooterLabelType,
    VsfFooterColumnType,
  },
  setup() {
    const componentToShow = computed(() => {
      return resolveComponent('NuxtLink');
    });
    const linkTag = (tag: TagOrComponent | undefined) => tag ?? 'a';
    const categories = [
      {
        label: 'How to buy',
        subcategories: [
          {
            label: 'Payment methods',
            linkTag: componentToShow,
            bindings: { to: '/payment' },
          },
          {
            label: 'Order pickup',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
          {
            label: 'Purchase status',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
          {
            label: 'Track orders',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
          {
            label: 'Returns',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
        ],
      },
      {
        label: 'Help',
        subcategories: [
          {
            label: 'Help centers',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
          {
            label: 'Security & fraud',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
          {
            label: 'Feedback',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
          {
            label: 'Contact',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
        ],
      },
      {
        label: 'Services',
        subcategories: [
          {
            label: 'Gift cards',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
          {
            label: 'Order pickup',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
          {
            label: 'Purchase status',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
          {
            label: 'Track orders',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
        ],
      },
      {
        label: 'About',
        subcategories: [
          {
            label: 'About us',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
          {
            label: 'Order pickup',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
          {
            label: 'Purchase status',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
          {
            label: 'Track orders',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
          {
            label: 'Returns',
            linkTag: componentToShow,
            bindings: { to: '/' },
          },
        ],
      },
    ];
    const socialMedia = [
      {
        label: 'Facebook',
        bindings: { href: '/' },
      },
      {
        label: 'Twitter',
        bindings: { href: '/' },
      },
      {
        label: 'Instagram',
        bindings: { href: '/' },
      },
      {
        label: 'Pinterest',
        bindings: { href: '/' },
      },
      {
        label: 'Youtube',
        bindings: { href: '/' },
      },
    ];
    const contactOptions = [
      {
        label: 'Help center',
        bindings: { href: '/' },
        details: ['Find answers online anytime'],
        iconName: 'help',
      },
      {
        label: 'Live chat',
        bindings: { href: '/' },
        details: ['Mon–Fri, 5am–10pm PT', 'Sat–Sun, 6am–9pm PT'],
        iconName: 'chat',
      },
      {
        label: '1 234 567 8901',
        bindings: { href: '/' },
        details: ['Mon–Fri, 5am–10pm PT', 'Sat–Sun, 6am–9pm PT'],
        iconName: 'phone',
      },
    ];
    const bottomLinks = [
      {
        label: 'Terms',
        linkTag: componentToShow,
        bindings: { to: '/' },
      },
      {
        label: 'Privacy policy',
        linkTag: componentToShow,
        bindings: { to: '/' },
      },
    ];
    return {
      linkTag,
      VsfFooterLabelType,
      VsfFooterColumnType,
      ...prepareControls(
        [
          {
            type: 'json',
            modelName: 'categoriesModel',
            propType: '[]',
            propDefaultValue: '[]',
          },
          {
            type: 'json',
            modelName: 'socialMediaModel',
            propType: '[]',
            propDefaultValue: '[]',
          },
          {
            type: 'json',
            modelName: 'contactOptionsModel',
            propType: '[]',
            propDefaultValue: '[]',
          },
          {
            type: 'json',
            modelName: 'bottomLinksModel',
            propType: '[]',
            propDefaultValue: '[]',
          },
          {
            type: 'text',
            modelName: 'companyNameModel',
            propDefaultValue: '',
            propType: 'string',
          },
        ],
        {
          categoriesModel: ref(categories),
          socialMediaModel: ref(socialMedia),
          companyNameModel: ref('© 2022 Vue Storefront'),
          bottomLinksModel: ref(bottomLinks),
          contactOptionsModel: ref(contactOptions),
        },
      ),
    };
  },
});
</script>

// apps/preview/next/pages/examples/VsfFooter.tsx
import VsfFooter, {
  VsfFooterBottomLinks,
  VsfFooterColumn,
  VsfFooterSection,
  VsfFooterSocialMedia,
  VsfFooterLabel,
} from '@sfui/sfui/frameworks/react/components/VsfFooter';
import {
  VsfIconChat,
  VsfIconFacebook,
  VsfIconHelp,
  VsfIconInstagram,
  VsfIconPhone,
  VsfIconPinterest,
  VsfIconTwitter,
  VsfIconYoutube,
} from '@sfui/sfui/frameworks/react/components/VsfIcons';
import { VsfIconSizeEnum } from '@sfui/sfui/frameworks/react/components/VsfIconBase/types';
import { VsfFooterColumnType, VsfFooterLabelType, VsfFooterSectionType } from '@sfui/shared/types/index';
import Link from 'next/link';
import Controls, { prepareControls } from '../../components/utils/Controls';
import { ExamplePageLayout } from '../examples';

const iconsMap: {
  [key: string]: any;
} = {
  VsfIconFacebook,
  VsfIconTwitter,
  VsfIconInstagram,
  VsfIconPinterest,
  VsfIconYoutube,
  VsfIconHelp,
  VsfIconChat,
  VsfIconPhone,
};

function Example() {
  const categories = [
    {
      label: 'How to buy',
      subcategories: [
        {
          label: 'Payment methods',
          link: '/payment',
        },
        {
          label: 'Order pickup',
          link: '/',
        },
        {
          label: 'Purchase status',
          link: '/',
        },
        {
          label: 'Track orders',
          link: '/',
        },
        {
          label: 'Returns',
          link: '/',
        },
      ],
    },
    {
      label: 'Help',
      subcategories: [
        {
          label: 'Help centers',
          link: '/',
        },
        {
          label: 'Security & fraud',
          link: '/',
        },
        {
          label: 'Feedback',
          link: '/',
        },
        {
          label: 'Contact',
          link: '/',
        },
      ],
    },
    {
      label: 'Services',
      subcategories: [
        {
          label: 'Gift cards',
          link: '/',
        },
        {
          label: 'Order pickup',
          link: '/',
        },
        {
          label: 'Purchase status',
          link: '/',
        },
        {
          label: 'Track orders',
          link: '/',
        },
      ],
    },
    {
      label: 'About',
      subcategories: [
        {
          label: 'About us',
          link: '/',
        },
        {
          label: 'Order pickup',
          link: '/',
        },
        {
          label: 'Purchase status',
          link: '/',
        },
        {
          label: 'Track orders',
          link: '/',
        },
        {
          label: 'Returns',
          link: '/',
        },
      ],
    },
  ];
  const socialMedia = [
    {
      label: 'Facebook',
      link: '/',
      icon: 'VsfIconFacebook',
    },
    {
      label: 'Twitter',
      link: '/',
      icon: 'VsfIconTwitter',
    },
    {
      label: 'Instagram',
      link: '/',
      icon: 'VsfIconInstagram',
    },
    {
      label: 'Pinterest',
      link: '/',
      icon: 'VsfIconPinterest',
    },
    {
      label: 'Youtube',
      link: '/',
      icon: 'VsfIconYoutube',
    },
  ];
  const contactOptions = [
    {
      label: 'Help center',
      link: '/',
      details: ['Find answers online anytime'],
      icon: 'VsfIconHelp',
    },
    {
      label: 'Live chat',
      link: '/',
      details: ['Mon–Fri, 5am–10pm PT', 'Sat–Sun, 6am–9pm PT'],
      icon: 'VsfIconChat',
    },
    {
      label: '1 234 567 8901',
      link: '/',
      details: ['Mon–Fri, 5am–10pm PT', 'Sat–Sun, 6am–9pm PT'],
      icon: 'VsfIconPhone',
    },
  ];
  const bottomLinks = [
    {
      label: 'Terms',
      link: '/',
    },
    {
      label: 'Privacy policy',
      link: '/',
    },
  ];
  const { state, controls } = prepareControls(
    [
      {
        type: 'json',
        modelName: 'categoriesModel',
        propType: '[]',
        propDefaultValue: '[]',
      },
      {
        type: 'json',
        modelName: 'socialMediaModel',
        propType: '[]',
        propDefaultValue: '[]',
      },
      {
        type: 'json',
        modelName: 'contactOptionsModel',
        propType: '[]',
        propDefaultValue: '[]',
      },
      {
        type: 'json',
        modelName: 'bottomLinksModel',
        propType: '[]',
        propDefaultValue: '[]',
      },
      {
        type: 'text',
        modelName: 'companyNameModel',
        propDefaultValue: '',
        propType: 'string',
      },
    ],
    {
      categoriesModel: categories,
      socialMediaModel: socialMedia,
      companyNameModel: '© 2022 Vue Storefront',
      contactOptionsModel: contactOptions,
      bottomLinksModel: bottomLinks,
    },
  );

  return (
    <div className="e-page">
      <div className="e-page-component">
        <VsfFooter>
          <VsfFooterSection type={VsfFooterSectionType.top}>
            {state.get.categoriesModel.map((category) => (
              <VsfFooterColumn key={category.label}>
                <VsfFooterLabel type={VsfFooterLabelType.category}>{category.label}</VsfFooterLabel>
                {category.subcategories?.map((subcategory) => (
                  <VsfFooterLabel key={subcategory.label}>
                    <Link href={subcategory.link}>
                      <a>{subcategory.label}</a>
                    </Link>
                  </VsfFooterLabel>
                ))}
              </VsfFooterColumn>
            ))}
          </VsfFooterSection>
          <VsfFooterSection type={VsfFooterSectionType.middle}>
            {state.get.contactOptionsModel.map((contactOption) => {
              const Icon = iconsMap[contactOption.icon];
              return (
                <VsfFooterColumn type={VsfFooterColumnType.middle} key={contactOption.label}>
                  <Icon size={VsfIconSizeEnum.lg} />
                  <VsfFooterLabel type={VsfFooterLabelType.contact}>
                    <Link href={contactOption.link}>
                      <a>{contactOption.label}</a>
                    </Link>
                  </VsfFooterLabel>
                  {contactOption.details?.map((option) => (
                    <VsfFooterLabel type={VsfFooterLabelType.contactDescription} key={option}>
                      {option}
                    </VsfFooterLabel>
                  ))}
                </VsfFooterColumn>
              );
            })}
          </VsfFooterSection>
          <VsfFooterSection type={VsfFooterSectionType.bottom}>
            <VsfFooterSocialMedia>
              {state.get.socialMediaModel.map((social) => {
                const Icon = iconsMap[social.icon];
                return (
                  <VsfFooterLabel type={VsfFooterLabelType.socialMedia} key={social.label}>
                    <Link href={social.link}>
                      <a aria-label={`Go to ${social.label} page`}>
                        <Icon />
                      </a>
                    </Link>
                  </VsfFooterLabel>
                );
              })}
            </VsfFooterSocialMedia>
            <VsfFooterBottomLinks>
              {state.get.bottomLinksModel.map((bottomLink) => (
                <VsfFooterLabel type={VsfFooterLabelType.bottomLinks} key={bottomLink.label}>
                  <Link href={bottomLink.link}>
                    <a>{bottomLink.label}</a>
                  </Link>
                </VsfFooterLabel>
              ))}
            </VsfFooterBottomLinks>
            <VsfFooterLabel type={VsfFooterLabelType.companyName}>{state.get.companyNameModel}</VsfFooterLabel>
          </VsfFooterSection>
        </VsfFooter>
      </div>
      <div className="e-page-controls">
        <Controls {...{ state, controls }} />
      </div>
    </div>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;
