// apps/preview/nuxt/pages/examples/VsfListItemFilterCheckbox.vue
<template>
  <div class="e-page">
    <div class="e-page-component">
      <ul class="max-w-sm">
        <VsfListItemFilterCheckbox
          v-model="modelValue"
          :counter="Number(counter)"
          :label="label"
          :size="size"
          :variant="variant"
          :secondary-text="secondaryText"
          :disabled="disabled"
          :truncate="truncate"
          :value="value"
        />

        <VsfListItemFilterCheckbox
          v-model="modelValue"
          :counter="Number(counter)"
          :label="`${label}-2`"
          :size="size"
          :variant="variant"
          :secondary-text="secondaryText"
          :disabled="disabled"
          :truncate="truncate"
          :value="`${value}-2`"
        />
      </ul>
    </div>
    <div class="e-page-controls">
      <Controls v-bind="controlsAttrs" />
    </div>
  </div>
</template>

<script>
import { ref } from 'vue';
import VsfListItemFilterCheckbox from '@sfui/sfui/frameworks/vue/components/VsfListItemFilterCheckbox/VsfListItemFilterCheckbox.vue';
import {
  VsfListItemFilterCheckboxSize,
  VsfListItemFilterCheckboxVariant,
} from '@sfui/sfui/frameworks/vue/components/VsfListItemFilterCheckbox/types';
import Controls, { prepareControls } from '../../components/utils/Controls.vue';

export default {
  name: 'VsfListItemFilterCheckboxExample',
  components: {
    Controls,
    VsfListItemFilterCheckbox,
  },
  setup() {
    return {
      ...prepareControls(
        [
          {
            type: 'text',
            modelName: 'modelValue',
            propType: 'string',
            propDefaultValue: '',
            description: 'Selected value',
          },
          {
            type: 'text',
            modelName: 'label',
            propType: 'string',
            description: 'Set label value',
          },
          {
            type: 'text',
            modelName: 'secondaryText',
            propType: 'string',
            description: 'Set secondary text',
          },
          {
            type: 'text',
            modelName: 'counter',
            propType: 'string',
            description: 'Set counter value',
          },
          {
            type: 'select',
            modelName: 'size',
            options: Object.keys(VsfListItemFilterCheckboxSize),
            description: 'Set size variant',
          },
          {
            type: 'select',
            modelName: 'variant',
            options: Object.keys(VsfListItemFilterCheckboxVariant),
            description: 'Set size variant',
          },
          {
            type: 'boolean',
            modelName: 'disabled',
            description: 'Show disabled state of component',
          },
          {
            type: 'boolean',
            modelName: 'truncate',
            description: 'Show truncated version of secondary text',
          },
          {
            type: 'text',
            modelName: 'value',
            propType: 'string',
            propDefaultValue: '',
          },
        ],
        {
          label: ref('Label'),
          size: ref(VsfListItemFilterCheckboxSize.base),
          variant: ref(VsfListItemFilterCheckboxVariant.left),
          counter: ref(123),
          secondaryText: ref('Secondary text'),
          disabled: ref(false),
          truncate: ref(false),
          modelValue: ref([]),
          value: ref('Value'),
        },
      ),
    };
  },
};
</script>

// apps/preview/next/pages/examples/VsfListItemFilterCheckbox.tsx
import VsfListItemFilterCheckbox, {
  VsfListItemFilterCheckboxVariant,
  VsfListItemFilterCheckboxSize,
  VsfListItemFilterCheckboxProps,
} from '@sfui/sfui/frameworks/react/components/VsfListItemFilterCheckbox';
import Controls, { prepareControls } from '../../components/utils/Controls';
import { ExamplePageLayout } from '../examples';

function Example() {
  const { state, controls } = prepareControls<
    Omit<VsfListItemFilterCheckboxProps, 'onChange'> & { checkedValue: string[] }
  >(
    [
      {
        type: 'text',
        modelName: 'checkedValue',
        propType: 'string',
        description: 'Example of getting values from group of checkboxes',
      },
      {
        type: 'text',
        modelName: 'label',
        propType: 'string',
        description: 'Set label value',
      },
      {
        type: 'text',
        modelName: 'secondaryText',
        propType: 'string',
        description: 'Set secondary text',
      },
      {
        type: 'text',
        modelName: 'counter',
        propType: 'string',
        description: 'Set counter value',
      },
      {
        type: 'select',
        modelName: 'size',
        options: Object.keys(VsfListItemFilterCheckboxSize),
        description: 'Set size variant',
      },
      {
        type: 'select',
        modelName: 'variant',
        options: Object.keys(VsfListItemFilterCheckboxVariant),
        description: 'Set size variant',
      },
      {
        type: 'boolean',
        modelName: 'disabled',
        description: 'Show disabled state of component',
      },
      {
        type: 'boolean',
        modelName: 'truncate',
        description: 'Show truncated version of secondary text',
      },
      {
        type: 'text',
        modelName: 'value',
        description: 'Value of radio input',
      },
      {
        type: 'text',
        modelName: 'name',
        description: 'Name for form input group',
      },
    ],
    {
      label: 'Label',
      size: VsfListItemFilterCheckboxSize.base,
      variant: VsfListItemFilterCheckboxVariant.left,
      counter: 123,
      secondaryText: 'Secondary text',
      disabled: false,
      truncate: false,
      value: 'value',
      name: 'name',
      checkedValue: [],
    },
  );

  function onChange(event: Parameters<NonNullable<VsfListItemFilterCheckboxProps['onChange']>>[0]) {
    const { value } = event.target;
    if (state.get.checkedValue.indexOf(value) > -1) {
      state.set({ ...state.get, checkedValue: state.get.checkedValue.filter((val) => val !== value) });
    } else {
      state.set({ ...state.get, checkedValue: [...state.get.checkedValue, value] });
    }
  }

  return (
    <div className="e-page">
      <div className="e-page-component">
        <ul className="max-w-sm">
          <VsfListItemFilterCheckbox
            size={state.get.size}
            variant={state.get.variant}
            label={state.get.label}
            counter={Number(state.get.counter)}
            secondaryText={state.get.secondaryText}
            disabled={state.get.disabled}
            truncate={state.get.truncate}
            value={state.get.value}
            name={state.get.name}
            onChange={onChange}
          />
          <VsfListItemFilterCheckbox
            size={state.get.size}
            variant={state.get.variant}
            label={`${state.get.label}-2`}
            counter={Number(state.get.counter)}
            secondaryText={state.get.secondaryText}
            disabled={state.get.disabled}
            truncate={state.get.truncate}
            value={`${state.get.value}-2`}
            name={state.get.name}
            onChange={onChange}
          />
        </ul>
      </div>
      <div className="e-page-controls">
        <Controls {...{ state, controls }} />
      </div>
    </div>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;
