// apps/preview/nuxt/pages/examples/VsfNavbarTop.vue
<!-- eslint-disable vue/one-component-per-file -->
<template>
  <div class="e-page">
    <div class="relative e-page-component">
      <VsfNavbarTop :filled="filled">
        <a
          href="/"
          aria-label="VSF Homepage"
          :class="[filled ? 'text-white' : 'text-brand', 'flex items-center h-8 md:h-10 lg:h-7']"
        >
          <VsfIconLogo viewBox="0 0 205 28" class="!hidden large:!block !w-[12.5rem] !h-[1.75rem]" />
          <VsfIconLogoSmall
            :size="VsfIconSizeEnum.xl"
            viewBox="0 0 40 40"
            class="!hidden medium:!block large:!hidden"
          />
          <VsfIconLogoSmall :size="VsfIconSizeEnum.lg" viewBox="0 0 40 40" class="block medium:!hidden" />
        </a>
        <VsfNavbarTopActionGroup class="hidden lg:block">
          <VsfNavbarTopAction v-for="(menuItem, i) in menuItems" :key="i" :link="menuItem.link">{{
            menuItem.label
          }}</VsfNavbarTopAction>
        </VsfNavbarTopActionGroup>
        <VsfNavbarTopAction class="block lg:hidden">
          <template #icon>
            <VsfIconMenu />
          </template>
          Menu</VsfNavbarTopAction
        >
        <VsfSpacer class="block md:hidden" />
        <VsfSearch placeholder="Search" class="flex-1 hidden md:block" />
        <VsfNavbarTopActionGroup>
          <VsfNavbarTopAction icon>
            <VsfBadge dot bordered value="10" :class="[filled ? 'bg-white' : 'bg-secondary-500']">
              <VsfIconBasket />
            </VsfBadge>
          </VsfNavbarTopAction>
          <VsfNavbarTopAction icon>
            <VsfBadge
              dot
              bordered
              value="10"
              :class="[filled ? 'bg-white text-gray-900' : 'bg-secondary-600 text-white']"
            >
              <VsfIconFavoritesOutline />
            </VsfBadge>
          </VsfNavbarTopAction>
          <VsfNavbarTopAction icon>
            <VsfIconPerson />
          </VsfNavbarTopAction>
        </VsfNavbarTopActionGroup>
      </VsfNavbarTop>
    </div>
    <div class="e-page-controls">
      <Controls v-bind="controlsAttrs" />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import Controls, { prepareControls } from '../../components/utils/Controls.vue';
import VsfNavbarTop from '@sfui/sfui/frameworks/vue/components/VsfNavbarTop/VsfNavbarTop.vue';
import VsfNavbarTopAction from '@sfui/sfui/frameworks/vue/components/VsfNavbarTop/VsfNavbarTopAction.vue';
import VsfNavbarTopActionGroup from '@sfui/sfui/frameworks/vue/components/VsfNavbarTop/VsfNavbarTopActionGroup.vue';
import VsfSpacer from '@sfui/sfui/frameworks/vue/components/VsfNavbarTop/VsfSpacer.vue';
import VsfBadge from '@sfui/sfui/frameworks/vue/components/VsfBadge/VsfBadge.vue';
import VsfSearch from '@sfui/sfui/frameworks/vue/components/VsfSearch/VsfSearch.vue';
import {
  VsfIconBasket,
  VsfIconFavoritesOutline,
  VsfIconPerson,
  VsfIconMenu,
  VsfIconLogo,
  VsfIconLogoSmall,
} from '@sfui/sfui/frameworks/vue/components/VsfIcons/index';
import { VsfIconSizeEnum } from '@sfui/sfui/frameworks/vue/components/VsfIconBase/types';
export default defineComponent({
  name: 'VsfNavbarTopExample',
  components: {
    VsfNavbarTop,
    VsfNavbarTopAction,
    VsfNavbarTopActionGroup,
    VsfSpacer,
    VsfIconLogo,
    VsfIconLogoSmall,
    VsfIconBasket,
    VsfIconFavoritesOutline,
    VsfIconPerson,
    VsfIconMenu,
    VsfBadge,
    VsfSearch,
    Controls,
  },
  setup() {
    return {
      VsfIconSizeEnum,
      ...prepareControls(
        [
          {
            type: 'boolean',
            modelName: 'filled',
            propType: 'boolean',
          },
          {
            type: 'json',
            modelName: 'menuItems',
            propType: 'Array',
            propDefaultValue: '[]',
          },
        ],
        {
          filled: ref(false),
          menuItems: ref([
            {
              label: 'Men',
              link: '/men',
            },
            {
              label: 'Women',
              link: '/women',
            },
            {
              label: 'Kids',
              link: '/women',
            },
          ]),
        },
      ),
    };
  },
});
</script>

// apps/preview/next/pages/examples/VsfNavbarTop.tsx
import VsfNavbarTop from '@sfui/sfui/frameworks/react/components/VsfNavbarTop/VsfNavbarTop';
import VsfNavbarTopActionGroup from '@sfui/sfui/frameworks/react/components/VsfNavbarTop/VsfNavbarTopActionGroup';
import VsfNavbarTopAction from '@sfui/sfui/frameworks/react/components/VsfNavbarTop/VsfNavbarTopAction';
import VsfSpacer from '@sfui/sfui/frameworks/react/components/VsfNavbarTop/VsfSpacer';
import VsfSearch from '@sfui/sfui/frameworks/react/components/VsfSearch';
import VsfBadge from '@sfui/sfui/frameworks/react/components/VsfBadge';
import {
  VsfIconBasket,
  VsfIconFavoritesOutline,
  VsfIconPerson,
  VsfIconMenu,
  VsfIconLogo,
  VsfIconLogoSmall,
} from '@sfui/sfui/frameworks/react/components/VsfIcons';
import Link from 'next/link';
import { VsfIconSizeEnum } from '@sfui/sfui/frameworks/react/components/VsfIconBase/types';
import classNames from 'classnames';
import Controls, { prepareControls } from '../../components/utils/Controls';
import { ExamplePageLayout } from '../examples';

function Example() {
  const { state, controls } = prepareControls(
    [
      {
        type: 'boolean',
        modelName: 'filled',
        propType: 'boolean',
      },
      {
        type: 'json',
        modelName: 'menuItems',
        propType: 'Array',
        propDefaultValue: '[]',
        description: 'VsfNavbarTopMenuItem prop',
      },
    ],
    {
      filled: false,
      menuItems: [
        {
          label: 'Men',
          link: '/men',
        },
        {
          label: 'Women',
          link: '/women',
        },
        {
          label: 'Kids',
          link: '/women',
        },
      ],
    },
  );
  const actionItems = [
    {
      icon: <VsfIconBasket />,
      ariaLabel: 'Cart',
    },
    {
      icon: <VsfIconFavoritesOutline />,
      ariaLabel: 'Wishlist',
    },
    {
      label: 'Log in',
      icon: <VsfIconPerson />,
      ariaLabel: 'Log in',
    },
  ];

  return (
    <div className="e-page">
      <div className="e-page-component">
        <VsfNavbarTop filled={state.get.filled}>
          <Link href="/">
            <a
              aria-label="VSF Homepage"
              className={classNames(
                'inline-block h-8 text-white md:h-10 lg:h-7',
                state.get.filled ? 'text-white' : 'text-brand',
              )}
            >
              <VsfIconLogo viewBox="0 0 205 28" className="!hidden large:!block !w-[12.5rem] !h-[1.75rem]" />
              <VsfIconLogoSmall
                size={VsfIconSizeEnum.xl}
                viewBox="0 0 40 40"
                className="!hidden medium:!block large:!hidden"
              />
              <VsfIconLogoSmall size={VsfIconSizeEnum.lg} viewBox="0 0 40 40" className="block medium:!hidden" />
            </a>
          </Link>
          <VsfNavbarTopActionGroup className="hidden lg:block">
            {state.get.menuItems.map((menuItem) => (
              <Link href={menuItem.link} key={menuItem.label}>
                <VsfNavbarTopAction tag="a">{menuItem.label}</VsfNavbarTopAction>
              </Link>
            ))}
          </VsfNavbarTopActionGroup>
          <VsfNavbarTopAction tag="a" slotIcon={<VsfIconMenu />} className="block lg:hidden">
            Menu
          </VsfNavbarTopAction>
          <VsfSpacer className="block md:hidden" />
          <VsfSearch placeholder="Search" className="flex-1 hidden md:block" />
          <VsfNavbarTopActionGroup>
            {actionItems.map((actionItem) =>
              actionItem.label !== 'Log in' ? (
                <VsfNavbarTopAction key={actionItem.ariaLabel} icon>
                  <VsfBadge dot value={1} className={state.get.filled ? 'bg-white' : 'bg-secondary-500'}>
                    {actionItem.icon}
                  </VsfBadge>
                </VsfNavbarTopAction>
              ) : (
                <VsfNavbarTopAction key={actionItem.ariaLabel} icon>
                  {actionItem.icon}
                </VsfNavbarTopAction>
              ),
            )}
          </VsfNavbarTopActionGroup>
        </VsfNavbarTop>
      </div>
      <div className="e-page-controls">
        <Controls {...{ state, controls }} />
      </div>
    </div>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;
