// apps/preview/remix/app/components/utils/Controls.tsx
import { ChangeEvent, useState } from "react";

type ControlOptionBind = {
  bind?: {};
  label?: string;
  value?: string | number;
};
type Controls = {
  title: string;
  type: 'range' | 'radio' | 'checkbox' | 'text' | 'select' | 'boolean' | 'number' | 'json';
  modelName: string;
  description?: string;
  propDefaultValue?: string | number | boolean;
  propType?: string;
  isRequired?: boolean;
  options?: (ControlOptionBind | string)[]
}[];

type Model = string | boolean | number | string[];
export type ControlsProps = {
  controls?: Controls;
  state: {
    get: Record<string, Model>,
    set: React.Dispatch<React.SetStateAction<Record<string, Model>>>
  }
}
export const prepareControls = (controls: Controls, models: Record<string, Model>): ControlsProps => {
  const [formData, setFormData] = useState(models);
  controls.map(control => {
    control.isRequired = false;
    return control;
  });
  return {
    controls,
    state: {
      set: setFormData,
      get: formData
    }
  }
}

export default function Controls(props: ControlsProps) {
  function setState(newState = {}) {
    props.state.set({
      ...props.state.get,
      ...newState
    })
  }

  function handleOnChangeValue<T = HTMLFormElement>(e: ChangeEvent<T>, name: string) {
    setState({ [name]: (e.target as unknown as HTMLFormElement).value });
  };

  function handleJsonOnChangeValue<T = HTMLFormElement>(e: ChangeEvent<T>, name: string) {
    setState({ [name]: JSON.parse((e.target as unknown as HTMLFormElement).value) });
  };

  function handleCheckbox(
    e: ChangeEvent<HTMLInputElement>,
    name: string,
    currentValue: string | boolean | []
  ) {
    let value = e.target.value;
    if (Array.isArray(currentValue)) {
      let newValue: string[] = [...currentValue];
      const valueItemIndex = newValue.indexOf(value);
      if (valueItemIndex === -1) {
        newValue.push(value);
      } else {
        newValue.splice(valueItemIndex, 1);
      }
      setState({ [name]: newValue });
    } else {
      setState({
        [name]: typeof currentValue === 'string' ? currentValue === value : !currentValue
      });
    }
  };

  function checkboxValue(option: ControlOptionBind | string) {
    return typeof option === 'string' ? option as string : (option as ControlOptionBind).value || (option as ControlOptionBind).label;
  }

  return (
    <div className="controls">
      <div className="heading-wrapper">
        <h1 className="heading">
          Controls
        </h1>
      </div>
      <table>
        <thead>
          <tr>
            <td>PropName</td>
            <td>Value</td>
            <td>Type</td>
            <td>DefaultValue</td>
            <td>Required</td>
            <td>Description</td>
          </tr>
        </thead>
        <tbody>
          {props.controls?.map((control, index) =>
            <tr key={index} className="props">
              <td className={`${control.type !== 'checkbox' && control.type !== 'radio' ? 'align-middle' : 'align-top'}`}>
                {control.title}
              </td>
              <td className="value" >
                {(() => {
                  switch (control.type) {
                    case "select":
                      return <select
                        onChange={(e) =>
                          handleOnChangeValue<HTMLSelectElement>(e, control.modelName)
                        }>
                        {(control?.options || [{}] as NonNullable<Controls[number]['options']>).map((option, optionIndex) => <option
                          key={`${control.title}-${index}-${optionIndex}`}
                          value={(option as ControlOptionBind).value || (option as ControlOptionBind).label || option as string}
                        >
                          {(option as ControlOptionBind).label || option}
                        </option>
                        )}
                      </select>;
                    case "boolean": return <div className="switch-wrapper">
                      <label className="switch">
                        <input
                          value={props.state.get[control.modelName] as string}
                          onChange={(e) => props.state.set({ ...props.state.get, [control.modelName]: !props.state.get[control.modelName] })}
                          type="checkbox"
                        />
                        <span className="slider" />
                      </label>
                      <span className="ml-2">{props.state.get[control.modelName].toString()}</span>
                    </div>;
                    default:
                      return (control?.options || [{}] as NonNullable<Controls[number]['options']>).map(
                        (option, optionIndex) =>
                          <div
                            key={`${control.title}-${index}-${optionIndex}`}
                            className="flex items-center"
                          >
                            <label className="flex items-center">
                              {control.type === "json" 
                                ? <textarea 
                                  rows={10}
                                  {...(option as ControlOptionBind).bind}
                                  className="border rounded-md"
                                  value={JSON.stringify(props.state.get[control.modelName], undefined, 2) as string}
                                  onChange={(e) => handleJsonOnChangeValue(e, control.modelName)}
                                  >
                                  </textarea>:
                              control.type === 'range' || control.type === 'text'
                                ? <input
                                  {...(option as ControlOptionBind).bind}
                                  value={props.state.get[control.modelName] as number | string}
                                  className="border rounded-md"
                                  type={control.type}
                                  onChange={(e) => handleOnChangeValue(e, control.modelName)}
                                />
                                : <input
                                  {...(option as ControlOptionBind).bind}
                                  value={checkboxValue(option)}
                                  type={control.type}
                                  onChange={(e) => {
                                    control.type === 'checkbox'
                                      && handleCheckbox(e, control.modelName, props.state.get[control.modelName] as string | [])
                                    control.type === 'radio'
                                      && handleOnChangeValue(e, control.modelName)
                                  }}
                                  name={`${control.title}-${index}`}
                                />
                              }
                              {option.hasOwnProperty('label') &&
                                <span className={`pl-2`}>{(option as ControlOptionBind).label}</span>}
                              {typeof option === 'string' &&
                                <span className="pl-2">{option}</span>}
                            </label>
                          </div>
                      )
                  }
                })()}
              </td>
              <td className="propType"><span>{control.propType}</span></td>
              <td className="propDefaultValue">{control.propDefaultValue}</td>
              <td className="required">{control?.isRequired?.toString()}</td>
              <td className="description">{control.description}</td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}

// apps/preview/nuxt/components/utils/Controls.vue
<template>
  <div class="controls">
    <div class="heading-wrapper">
      <h1 class="heading">
        Controls
      </h1>
    </div>
    <table>
      <thead>
        <tr>
          <td>PropName</td>
          <td>Value</td>
          <td>Type</td>
          <td>DefaultValue</td>
          <td>Required</td>
          <td>Description</td>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(control, index) in controls" :key="index" class="props">
          <td :class="[control.type === 'text' && 'align-middle']">
            {{ control.title }}
          </td>
          <td class="value" >
            <template v-if="control.type === 'select'">
              <select
                v-model="proxyModels[control.modelName]"
              >
                <option
                  v-for="(options, optionIndex) in control.options || [{}]"
                  :key="`${control.title}-${index}-${optionIndex}`"
                  :value="options.value || options.label || options"
                >
                  {{ options.label || options }}
                </option>
              </select>
            </template>
            <template v-else-if="control.type === 'boolean'">
              <div class="switch-wrapper">
                <label class="switch">
                  <input
                    v-model="proxyModels[control.modelName]"
                    type="checkbox"
                  >
                  <span class="slider" />
                </label>
                <span class="ml-2">{{ proxyModels[control.modelName] }}</span>
              </div>
            </template>
            <template v-else>
              <div
                v-for="(options, optionIndex) in control.options || [{}]"
                :key="`${control.title}-${index}-${optionIndex}`"
                class="flex items-center"
              >
                <label class="flex items-center">
                  <textarea
                    v-if="control.type === 'json'"
                    rows="10"
                    v-bind="options.bind"
                    :value="JSON.stringify(proxyModels[control.modelName], undefined, 2)"
                    @input="proxyModels[control.modelName] = JSON.parse($event.target.value)"
                    :name="`${control.title}-${index}`"
                  >
                  </textarea>
                  <input
                    v-else-if="control.type === 'range'"
                    v-bind="options.bind"
                    v-model="proxyModels[control.modelName]"
                    :type="control.type"
                    :name="`${control.title}-${index}`"
                  />
                  <input
                    v-else-if="control.type === 'text'"
                    v-bind="options.bind"
                    v-model="proxyModels[control.modelName]"
                    class="border rounded-md"
                    :type="control.type"
                    :name="`${control.title}-${index}`"
                  />
                  <input
                    v-else
                    v-bind="options.bind"
                    v-model="proxyModels[control.modelName]"
                    :value="options.value || options.label || (typeof options === 'string' && options)"
                    :type="control.type"
                    :name="`${control.title}-${index}`"
                  />
                  <span v-if="options.hasOwnProperty('label')" class="pl-2">{{ options.label }}</span>
                  <span v-else-if="typeof options === 'string'" class="pl-2">{{ options }}</span>
                </label>
              </div>
            </template>
          </td>
          <td class="propType"><span>{{control.propType}}</span></td>
          <td class="propDefaultValue">{{control.propDefaultValue}}</td>
          <td class="required">{{control?.isRequired?.toString()}}</td>
          <td class="description">{{control.description}}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script lang="ts">
import { toRefs, computed, reactive, Ref, defineComponent, PropType } from 'vue';

type RefValueUnknown = Ref<unknown>;
type Controls = {
  title: string;
  type: 'range' | 'radio' | 'checkbox' | 'text' | 'select' | 'boolean' | 'json';
  modelName: string;
  model?: RefValueUnknown,
  description?: string;
  propDefaultValue?: string | number | boolean;
  propType?: string;
  isRequired?: boolean;
  options?: ({
    bind?: unknown;
    label?: string;
    value?: string | undefined
  } | string)[]
}[];
export const prepareControls = (
  controlsObject: Controls,
  models: Record<string, RefValueUnknown>
) => {
  const on: Record<string, (e: KeyboardEvent) => void> = {};
  const controls = controlsObject.map((control) => {
    control.isRequired = false;
    on[`onUpdate:${control.modelName}`] = (e: KeyboardEvent) => {
      models[control.modelName].value = e;
    };
    return { ...control, model: models[control.modelName] };
  });

  return {
    controlsAttrs: {
      controls,
      ...on
    },
    ...models,
  };
};

export default defineComponent({
  name: 'Controls',
  props: {
    controls: {
      type: Array as PropType<Controls>,
      default: () => ([]),
    },
  },
  inheritAttrs: false,
  setup(props, { emit }) {
    const { controls } = toRefs(props);
    const proxyModels = reactive<Record<string, Ref<unknown>>>({});
    controls.value.forEach((control) => {
      proxyModels[control.modelName] = reactive(computed({
        get: () => control?.model?.value,
        set: (value) => emit(`update:${control.modelName}`, value),
      }));
    });

    return {
      proxyModels,
    };
  },
});
</script>
