// packages/sfui/frameworks/react/components/VsfSelect/VsfSelect.tsx
import classNames from 'classnames';
import { ChangeEvent } from 'react';
import { VsfSelectSizes } from './types';

import type { VsfSelectProps } from './types';

export default function VsfSelect({
  className,
  label,
  disabled,
  required,
  size = VsfSelectSizes.base,
  children,
  slotPlaceholder,
  placeholder,
  errorText,
  helpText,
  requiredText,
  invalid,
  onChange,
}: VsfSelectProps) {
  function changedValue(event: ChangeEvent<HTMLSelectElement>) {
    const selectedValue = (event.target as HTMLSelectElement).value;
    onChange(selectedValue);
  }
  return (
    <div className={classNames('vsf-select', { 'vsf-select--disabled': disabled }, className)}>
      <div className="vsf-select__wrapper">
        <div
          className={classNames('vsf-select__wrapper-input', {
            'vsf-select__wrapper-input--with-label': label,
          })}
        >
          <select
            id={label}
            required={required}
            disabled={disabled}
            className={classNames('vsf-select__input peer', {
              'vsf-select__input--base': size === 'base',
              'vsf-select__input--small': size === 'sm',
              'vsf-select__input--large': size === 'lg',
              'vsf-select__input--invalid': invalid,
            })}
            onChange={changedValue}
          >
            <option
              value=""
              className={classNames('vsf-select__placeholder', {
                'vsf-select__placeholder--base': size === 'base',
                'vsf-select__placeholder--small': size === 'sm',
                'vsf-select__placeholder--large': size === 'lg',
              })}
            >
              {placeholder || slotPlaceholder}
            </option>
            {children}
          </select>
          <label htmlFor={label} className="vsf-select__label">
            {label}
          </label>
        </div>
      </div>
      <div>
        {invalid ? (
          <span className="vsf-select__error-text" aria-live={invalid ? 'assertive' : 'off'}>
            {errorText}
          </span>
        ) : null}
        {helpText ? <span className="vsf-select__help-text">{helpText}</span> : null}
        {required ? <span className="vsf-select__required">{requiredText}</span> : null}
      </div>
    </div>
  );
}

// packages/sfui/frameworks/vue/components/VsfSelect/VsfSelect.vue
<script lang="ts" setup>
import { ref } from 'vue';
import { VsfSelectSizes } from './types';

const props = defineProps({
  size: {
    type: String,
    default: VsfSelectSizes.base,
  },
  placeholder: {
    type: String,
    default: '',
  },
  required: {
    type: Boolean,
    default: false,
  },
  disabled: {
    type: Boolean,
    default: false,
  },
  invalid: {
    type: Boolean,
    default: false,
  },
  value: {
    type: String,
    default: '',
  },
  label: {
    type: String,
    default: '',
  },
  helpText: {
    type: String,
    default: '',
  },
  errorText: {
    type: String,
    default: '',
  },
  requiredText: {
    type: String,
    default: '*Required',
  },
});
const selected = ref(props.value);
const emit = defineEmits<{
  (event: 'update:modelValue', param: string): void;
}>();

const changedValue = (event: Event) => {
  selected.value = (event.target as HTMLSelectElement).value;
  emit('update:modelValue', (event.target as HTMLSelectElement).value);
};
</script>

<template>
  <div class="vsf-select" :class="{ 'vsf-select--disabled': disabled }">
    <div class="vsf-select__wrapper">
      <div class="vsf-select__wrapper-input" :class="{ 'vsf-select__wrapper-input--with-label': label }">
        <select
          :id="label"
          :required="required"
          :disabled="disabled"
          class="vsf-select__input peer"
          :class="
            (size === VsfSelectSizes.base
              ? null
              : size === VsfSelectSizes.sm
              ? 'vsf-select__input--small'
              : 'vsf-select__input--large',
            { 'vsf-select__input--invalid': invalid })
          "
          @change="changedValue"
        >
          <slot name="placeholder">
            <option
              v-if="placeholder"
              :selected="!!placeholder"
              class="vsf-select__placeholder"
              value=""
              :class="
                size === VsfSelectSizes.base
                  ? null
                  : size === VsfSelectSizes.sm
                  ? 'vsf-select__placeholder--small'
                  : 'vsf-select__placeholder--large'
              "
            >
              {{ placeholder }}
            </option>
          </slot>
          <slot />
        </select>
        <slot name="label">
          <label :for="label" class="vsf-select__label">{{ label }}</label>
        </slot>
      </div>
    </div>
    <slot name="errorText">
      <span v-if="invalid" class="vsf-select__error-text" :aria-live="invalid ? 'assertive' : 'off'">
        {{ errorText }}
      </span>
    </slot>
    <slot name="helpText">
      <span v-if="helpText" class="vsf-select__help-text">{{ helpText }}</span>
    </slot>
    <slot name="requiredText">
      <span v-if="required" class="vsf-select__required">{{ requiredText }}</span>
    </slot>
  </div>
</template>
