// apps/preview/remix/app/routes/examples/VsfSheet.tsx
import VsfSheet from '../../output/blocks/VsfSheet/VsfSheet.lite';
import Controls, { prepareControls } from '../../components/utils/Controls';

export default function VsfSheetExample() {
  const { state, controls } = prepareControls([
    {
      title: 'defaultSlot',
      type: 'text',
      modelName: 'defaultSlot',
      description: 'Default slot',
      propDefaultValue: 'false',
      propType: 'string',
    }
  ], {
    defaultSlot: ''
  });
  
  return (
    <div className="e-page">
      <div className="e-page-component">
        <VsfSheet>
          {state.get.defaultSlot}
        </VsfSheet>
      </div>
      <div className="e-page-controls">
        <Controls {...{ state, controls }} />
      </div>
    </div>
  );
}

// apps/preview/nuxt/legacy/examplesOld/VsfSheet.vue
<template>
  <div class="e-page">
    <div class="e-page-component">
      <VsfSheet>
        {{ defaultSlot }}
      </VsfSheet>
    </div>
    <div class="e-page-controls">
      <Controls v-bind="controlsAttrs" />
    </div>
  </div>
</template>

<script>
import { ref } from 'vue';
import VsfSheet from '../../output/blocks/VsfSheet/VsfSheet.vue';
import Controls, { prepareControls } from '../../components/utils/Controls.vue';

export default {
  name: 'VsfSheetExample',
  components: {
    Controls,
    VsfSheet,
  },
  setup() {
    return prepareControls(
      [
        {
          title: 'defaultSlot',
          type: 'text',
          modelName: 'defaultSlot',
          description: 'Default slot',
          propDefaultValue: false,
          propType: 'string',
        },
      ],
      {
        defaultSlot: ref(),
      },
    );
  },
};
</script>
