// apps/preview/remix/app/routes/examples/VsfSlider.tsx
import VsfSlider from '../../output/blocks/VsfSlider/VsfSlider.lite';
import Controls, { prepareControls } from '../../components/utils/Controls';

export default function VsfSliderExample() {
  const { state, controls } = prepareControls([
    {
      title: 'hasChevrons',
      type: 'boolean',
      modelName: 'hasChevronsModel',
      propDefaultValue: 'true',
      propType: 'boolean',
    },
    {
      title: 'hasScrollbar',
      type: 'boolean',
      modelName: 'hasScrollbarModel',
      propDefaultValue: 'true',
      propType: 'boolean',
    },
  ], {
    hasChevronsModel: true,
    hasScrollbarModel: true,
  });
  
  return (
    <div className="e-page">
      <div className="e-page-component">
        <VsfSlider
          hasChevrons={state.get.hasChevronsModel}
          hasScrollbar={state.get.hasScrollbarModel}
        >
          {Array.from(Array(10).keys()).map(item =>
            <div
              key={item}
              className="bg-gray-300 w-[148px] h-[148px] flex justify-center items-center"
            >
              {item + 1}
            </div>
          )}
        </VsfSlider>
      </div>
      <div className="e-page-controls">
        <Controls {...{ state, controls }} />
      </div>
    </div>
  );
}

// apps/preview/nuxt/legacy/examplesOld/VsfSlider.vue
<template>
  <div class="e-page">
    <div class="e-page-component">
      <VsfSlider :has-chevrons="hasChevronsModel" :has-scrollbar="hasScrollbarModel">
        <div v-for="index in 10" :key="index" class="bg-gray-300 w-[148px] h-[148px] flex justify-center items-center">
          {{ index }}
        </div>
      </VsfSlider>
    </div>
    <div class="e-page-controls">
      <Controls v-bind="controlsAttrs" />
    </div>
  </div>
</template>

<script>
import { ref } from 'vue';
import VsfSlider from '../../output/blocks/VsfSlider/VsfSlider.vue';
import Controls, { prepareControls } from '../../components/utils/Controls.vue';

export default {
  name: 'VsfSliderExample',
  components: {
    Controls,
    VsfSlider,
  },
  setup() {
    return {
      ...prepareControls(
        [
          {
            title: 'hasChevrons',
            type: 'boolean',
            modelName: 'hasChevronsModel',
            propDefaultValue: 'true',
            propType: 'boolean',
          },
          {
            title: 'hasScrollbar',
            type: 'boolean',
            modelName: 'hasScrollbarModel',
            propDefaultValue: 'true',
            propType: 'boolean',
          },
        ],
        {
          hasChevronsModel: ref(true),
          hasScrollbarModel: ref(true),
        },
      ),
    };
  },
};
</script>
