// apps/mitosis/output/react/src/blocks/VsfRating/VsfRating.js
import * as React from "react";
import VsfIconStar from "../VsfIcons/VsfIconStar.js";
import VsfIconStarOutline from "../VsfIcons/VsfIconStarOutline.js";
import VsfIconStarPartiallyFilled from "../VsfIcons/VsfIconStarPartiallyFilled.js";
import VsfCounter from "../VsfCounter/VsfCounter.js";
const VsfRatingVariants = Object.freeze({
  xs: "xs",
  sm: "sm",
  base: "base",
  lg: "lg",
  xl: "xl"
});
const VsfRatingTypes = Object.freeze({
  base: "base",
  withValue: "withValue"
});
const DEFAULT_VALUES = {
  value: 0,
  max: 5,
  size: VsfRatingVariants.base,
  type: VsfRatingTypes.base
};
function VsfRating(props) {
  var _a, _b;
  function useValueProp() {
    return Math.max(0, Math.min(Number(props.value) || DEFAULT_VALUES.value, useMaxProp()));
  }
  function useMaxProp() {
    return Number(props.max) || DEFAULT_VALUES.max;
  }
  function useSizeProp() {
    return props.size || DEFAULT_VALUES.size;
  }
  function useTypeProp() {
    return props.type || DEFAULT_VALUES.type;
  }
  function isPartiallyFilled() {
    return useValueProp() % 1 > 0.25 && useValueProp() % 1 < 0.75;
  }
  function filled() {
    return Math.floor(useValueProp()) + (useValueProp() % 1 > 0.75);
  }
  function empty() {
    return useMaxProp() - filled() - Number(isPartiallyFilled());
  }
  function ratingValue() {
    return Math.min(useValueProp(), useMaxProp());
  }
  function ratingSize() {
    return {
      xs: "base",
      sm: "base",
      base: "lg",
      lg: "xl",
      xl: "2xl"
    }[useSizeProp()];
  }
  function textClass() {
    return {
      xs: "text-xs",
      sm: "text-sm",
      base: "text-base",
      lg: "text-lg",
      xl: "text-lg",
      "2xl": "text-lg"
    }[useSizeProp()];
  }
  function isBaseType() {
    return useTypeProp() === VsfRatingTypes.base;
  }
  return /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement("div", {
    role: "img",
    className: `flex items-center h-6 font-normal pointer-events-none font-body ${textClass()}`,
    "aria-label": `Rating: ${useValueProp()} out of ${useMaxProp()} stars`
  }, isBaseType() ? /* @__PURE__ */ React.createElement(React.Fragment, null, (_a = [...Array(filled())]) == null ? void 0 : _a.map((_, index) => /* @__PURE__ */ React.createElement(VsfIconStar, {
    "aria-hidden": "true",
    className: "text-warning-500",
    key: index,
    size: useSizeProp()
  })), isPartiallyFilled() ? /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(VsfIconStarPartiallyFilled, {
    "aria-hidden": "true",
    className: "text-warning-500",
    size: useSizeProp()
  })) : null, (_b = [...Array(empty())]) == null ? void 0 : _b.map((_, index) => /* @__PURE__ */ React.createElement(VsfIconStarOutline, {
    "aria-hidden": "true",
    className: "text-gray-500 opacity-50",
    key: index,
    size: useSizeProp()
  }))) : /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(VsfIconStar, {
    "aria-hidden": "true",
    className: "text-warning-500",
    size: useSizeProp()
  }), /* @__PURE__ */ React.createElement("span", {
    className: "ml-1"
  }, ratingValue())), props.reviews ? /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(VsfCounter, {
    className: "ml-1",
    size: ratingSize()
  }, props.reviews)) : null));
}
export {
  VsfRatingTypes,
  VsfRatingVariants,
  VsfRating as default
};

// apps/mitosis/output/vue/vue2/src/blocks/VsfRating/VsfRating.vue
<template>
  <div
    role="img"
    :class="
      _classStringToObject(
        `flex items-center h-6 font-normal pointer-events-none font-body ${textClass}`
      )
    "
    :aria-label="`Rating: ${useValueProp} out of ${useMaxProp} stars`"
  >
    <vsf-icon-star
      aria-hidden="true"
      class="text-warning-500"
      v-for="(_, index) in [...Array(filled)]"
      v-if="isBaseType"
      :size="useSizeProp"
      :key="index"
    ></vsf-icon-star>

    <vsf-icon-star
      aria-hidden="true"
      class="text-warning-500"
      :size="useSizeProp"
    ></vsf-icon-star>

    <span class="ml-1">{{ ratingValue }}</span>

    <vsf-counter class="ml-1" v-if="reviews" :size="ratingSize">{{
      reviews
    }}</vsf-counter>
  </div>
</template>

<script>
import VsfIconStar from "../VsfIcons/VsfIconStar.vue";
import VsfIconStarOutline from "../VsfIcons/VsfIconStarOutline.vue";
import VsfIconStarPartiallyFilled from "../VsfIcons/VsfIconStarPartiallyFilled.vue";
import VsfCounter from "../VsfCounter/VsfCounter.vue";
export const VsfRatingVariants = Object.freeze({
  xs: "xs",
  sm: "sm",
  base: "base",
  lg: "lg",
  xl: "xl",
});
export const VsfRatingTypes = Object.freeze({
  base: "base",
  withValue: "withValue",
});
const DEFAULT_VALUES = {
  value: 0,
  max: 5,
  size: VsfRatingVariants.base,
  type: VsfRatingTypes.base,
};

export default {
  name: "vsf-rating",
  components: {
    "vsf-icon-star": VsfIconStar,
    "vsf-icon-star-partially-filled": VsfIconStarPartiallyFilled,
    "vsf-icon-star-outline": VsfIconStarOutline,
    "vsf-counter": VsfCounter,
  },
  props: ["value", "max", "size", "type", "reviews"],

  computed: {
    useValueProp() {
      return Math.max(
        0,
        Math.min(Number(this.value) || DEFAULT_VALUES.value, this.useMaxProp)
      );
    },
    useMaxProp() {
      return Number(this.max) || DEFAULT_VALUES.max;
    },
    useSizeProp() {
      return this.size || DEFAULT_VALUES.size;
    },
    useTypeProp() {
      return this.type || DEFAULT_VALUES.type;
    },
    isPartiallyFilled() {
      return this.useValueProp % 1 > 0.25 && this.useValueProp % 1 < 0.75;
    },
    filled() {
      return Math.floor(this.useValueProp) + (this.useValueProp % 1 > 0.75);
    },
    empty() {
      return this.useMaxProp - this.filled - Number(this.isPartiallyFilled);
    },
    ratingValue() {
      return Math.min(this.useValueProp, this.useMaxProp);
    },
    ratingSize() {
      return {
        xs: "base",
        sm: "base",
        base: "lg",
        lg: "xl",
        xl: "2xl",
      }[this.useSizeProp];
    },
    textClass() {
      return {
        xs: "text-xs",
        sm: "text-sm",
        base: "text-base",
        lg: "text-lg",
        xl: "text-lg",
        "2xl": "text-lg",
      }[this.useSizeProp];
    },
    isBaseType() {
      return this.useTypeProp === VsfRatingTypes.base;
    },
  },

  methods: {
    _classStringToObject(str) {
      const obj = {};
      if (typeof str !== "string") {
        return obj;
      }
      const classNames = str.trim().split(/\s+/);
      for (const name of classNames) {
        obj[name] = true;
      }
      return obj;
    },
  },
};
</script>
