// apps/preview/nuxt/pages/showcases/Thumbnail/Sizes.vue
<template>
  <div className="flex items-center justify-around max-w-sm">
    <VsfThumbnail size="sm" class="bg-primary-500 mr-2" />
    <VsfThumbnail size="base" class="bg-primary-500 mr-2" />
    <VsfThumbnail size="lg" class="bg-primary-500 mr-2" />
    <VsfThumbnail size="xl" class="bg-primary-500" />
  </div>
</template>

<script lang="ts" setup>
import { VsfThumbnail } from '@storefront-ui/vue';
</script>

// apps/preview/next/pages/showcases/Thumbnail/Sizes.tsx
import { VsfThumbnail } from '@storefront-ui/react';
import { ShowcasePageLayout } from '../../showcases';

export function Showcase() {
  return (
    <div className="flex items-center justify-around max-w-sm">
      <VsfThumbnail size="sm" className="bg-primary-500 mr-2" />
      <VsfThumbnail size="base" className="bg-primary-500 mr-2" />
      <VsfThumbnail size="lg" className="bg-primary-500 mr-2" />
      <VsfThumbnail size="xl" className="bg-primary-500" />
    </div>
  );
}

Showcase.getLayout = ShowcasePageLayout;
export default Showcase;
