// apps/preview/nuxt/pages/showcases/LoaderLinear/LoaderLinearColors.vue
<template>
  <div class="flex gap-4 flex-wrap">
    <VsfLoaderLinear class="w-12 !text-cyan-700" size="lg" />
    <VsfLoaderLinear class="w-12" size="lg" />
    <VsfLoaderLinear class="w-12 !bg-yellow-200" size="lg" />
  </div>
</template>

<script lang="ts" setup>
import { VsfLoaderLinear } from '@storefront-ui/vue/components/VsfLoaderLinear/index';
</script>

// apps/preview/next/pages/showcases/LoaderLinear/LoaderLinearColors.tsx
import { VsfLoaderLinear } from '@storefront-ui/react/components/VsfLoaderLinear/index';
import { ShowcasePageLayout } from '../../showcases';

export function Showcase() {
  return (
    <div className="flex gap-4 flex-wrap">
      <VsfLoaderLinear className="w-12 !text-cyan-700" size="lg" />
      <VsfLoaderLinear className="w-12" size="lg" />
      <VsfLoaderLinear className="w-12 !bg-yellow-200" size="lg" />
    </div>
  );
}

Showcase.getLayout = ShowcasePageLayout;
export default Showcase;
