// packages/sfui/frameworks/qwik/src/components/SfDropdown/SfDropdown.tsx
import { Slot, component$ } from '@builder.io/qwik';
import { SfDropdownProps } from './types';

export const SfDropdown = component$<SfDropdownProps>((props) => {
  const { ref, open: isOpen = false, class: _class, style: containerStyle, ...dropdownOptions } = props;

  //TODO
  // const { refs, style: dropdownStyle } = useDropdown({ isOpen, ...dropdownOptions });
  const dropdownStyle = '';

  return (
    <div {...(ref ? { ref } : {})} class={['w-max', _class]} style={containerStyle} data-testid="dropdown">
      <Slot name="trigger" />
      {isOpen && (
        <div {...(ref ? { ref } : {})} style={dropdownStyle} aria-hidden={!isOpen} data-testid="dropdown-content">
          <Slot />
        </div>
      )}
    </div>
  );
});

// packages/sfui/frameworks/react/components/SfDropdown/SfDropdown.tsx
import classNames from 'classnames';
import { useDropdown } from '@storefront-ui/react';
import type { SfDropdownProps } from '@storefront-ui/react';

export default function SfDropdown(props: SfDropdownProps) {
  const { children, trigger, open: isOpen = false, className, style: containerStyle, ...dropdownOptions } = props;
  const { refs, style: dropdownStyle } = useDropdown({ isOpen, ...dropdownOptions });

  return (
    <div
      ref={refs.setReference}
      className={classNames('w-max', className)}
      style={containerStyle}
      data-testid="dropdown"
    >
      {trigger}
      {isOpen && (
        <div ref={refs.setFloating} style={dropdownStyle} aria-hidden={!isOpen} data-testid="dropdown-content">
          {children}
        </div>
      )}
    </div>
  );
}
