// apps/mitosis/output/vue/vue2/src/blocks/VsfSlider/VsfSlider.vue
<template>
  <div class="grid grid-flow-col w-fit items-center gap-4">
    <vsf-button
      variant="secondary"
      v-if="useHasChevronsProp"
      :classes="
        classStringFromArray([
          'slider-button w-12 h-12',
          !prevChevronVisibility && 'invisible',
        ])
      "
      :isRoundedFull="true"
      @click="go('prev')"
    >
      <span class="w-6 h-6">
        <vsf-icon-chevron-left class="slider-chevron"></vsf-icon-chevron-left>
      </span>
    </vsf-button>

    <div
      ref="sliderRef"
      @scroll="setChevrons($event)"
      :class="
        _classStringToObject(
          classStringFromArray([
            'slider-items-container grid grid-flow-col overflow-x-auto overscroll-contain scroll-smooth snap-x gap-4 pb-3',
            !useHasScrollbarProp && 'no-scrollbar',
          ])
        )
      "
    >
      <slot />
    </div>

    <vsf-button
      variant="secondary"
      v-if="useHasChevronsProp"
      :classes="
        classStringFromArray([
          'slider-button w-12-h12',
          !nextChevronVisibility && 'invisible',
        ])
      "
      :isRoundedFull="true"
      @click="go('next')"
    >
      <span class="w-6 h-6">
        <vsf-icon-chevron-right class="slider-chevron"></vsf-icon-chevron-right>
      </span>
    </vsf-button>
  </div>
</template>

<script>
import { classStringFromArray } from "../../functions/domUtils";
import VsfButton from "../VsfButton/VsfButton.vue";
import VsfIconChevronLeft from "../VsfIcons/VsfIconChevronLeft.vue";
import VsfIconChevronRight from "../VsfIcons/VsfIconChevronRight.vue";
const DEFAULT_VALUES: Required<VsfSliderProps> = {
  children: "",
  hasChevrons: true,
  hasScrollbar: true,
};

export default {
  name: "vsf-slider",
  components: {
    "vsf-button": VsfButton,
    "vsf-icon-chevron-left": VsfIconChevronLeft,
    "vsf-icon-chevron-right": VsfIconChevronRight,
  },
  props: ["hasChevrons", "hasScrollbar"],

  data: () => ({
    prevChevronVisibility: false,
    nextChevronVisibility: true,
    classStringFromArray,
  }),

  computed: {
    useHasChevronsProp() {
      return this.hasChevrons ?? DEFAULT_VALUES.hasChevrons;
    },
    useHasScrollbarProp() {
      return this.hasScrollbar ?? DEFAULT_VALUES.hasScrollbar;
    },
  },

  methods: {
    go(direct) {
      if (direct === "next") {
        this.$refs.sliderRef.scrollLeft +=
          this.$refs.sliderRef?.children[0]?.getBoundingClientRect()?.width;
      } else {
        this.$refs.sliderRef.scrollLeft -=
          this.$refs.sliderRef?.children[0]?.getBoundingClientRect()?.width;
      }
    },
    setChevrons(e) {
      const maxScrollLeft = e.target.scrollWidth - e.target.clientWidth;
      this.prevChevronVisibility = e.target.scrollLeft !== 0;
      this.nextChevronVisibility = e.target.scrollLeft !== maxScrollLeft;
    },
    _classStringToObject(str) {
      const obj = {};
      if (typeof str !== "string") {
        return obj;
      }
      const classNames = str.trim().split(/\s+/);
      for (const name of classNames) {
        obj[name] = true;
      }
      return obj;
    },
  },
};
</script>

// apps/mitosis/output/react/src/blocks/VsfSlider/VsfSlider.js
import * as React from "react";
import { useState, useRef } from "react";
import { classStringFromArray } from "../../functions/domUtils";
import VsfButton from "../VsfButton/VsfButton.js";
import VsfIconChevronLeft from "../VsfIcons/VsfIconChevronLeft.js";
import VsfIconChevronRight from "../VsfIcons/VsfIconChevronRight.js";
const DEFAULT_VALUES = {
  children: "",
  hasChevrons: true,
  hasScrollbar: true
};
function VsfSlider(props) {
  const sliderRef = useRef(null);
  const [prevChevronVisibility, setPrevChevronVisibility] = useState(() => false);
  const [nextChevronVisibility, setNextChevronVisibility] = useState(() => true);
  function useHasChevronsProp() {
    var _a;
    return (_a = props.hasChevrons) != null ? _a : DEFAULT_VALUES.hasChevrons;
  }
  function useHasScrollbarProp() {
    var _a;
    return (_a = props.hasScrollbar) != null ? _a : DEFAULT_VALUES.hasScrollbar;
  }
  function go(direct) {
    var _a, _b, _c, _d, _e, _f;
    if (direct === "next") {
      sliderRef.current.scrollLeft += (_c = (_b = (_a = sliderRef.current) == null ? void 0 : _a.children[0]) == null ? void 0 : _b.getBoundingClientRect()) == null ? void 0 : _c.width;
    } else {
      sliderRef.current.scrollLeft -= (_f = (_e = (_d = sliderRef.current) == null ? void 0 : _d.children[0]) == null ? void 0 : _e.getBoundingClientRect()) == null ? void 0 : _f.width;
    }
  }
  function setChevrons(e) {
    const maxScrollLeft = e.target.scrollWidth - e.target.clientWidth;
    setPrevChevronVisibility(e.target.scrollLeft !== 0);
    setNextChevronVisibility(e.target.scrollLeft !== maxScrollLeft);
  }
  return /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement("div", {
    className: "grid grid-flow-col w-fit items-center gap-4"
  }, useHasChevronsProp() ? /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(VsfButton, {
    variant: "secondary",
    classes: classStringFromArray([
      "slider-button w-12 h-12",
      !prevChevronVisibility && "invisible"
    ]),
    isRoundedFull: true,
    onClick: (event) => go("prev")
  }, /* @__PURE__ */ React.createElement("span", {
    className: "w-6 h-6"
  }, /* @__PURE__ */ React.createElement(VsfIconChevronLeft, {
    className: "slider-chevron"
  })))) : null, /* @__PURE__ */ React.createElement("div", {
    ref: sliderRef,
    onScroll: (e) => setChevrons(e),
    className: classStringFromArray([
      "slider-items-container grid grid-flow-col overflow-x-auto overscroll-contain scroll-smooth snap-x gap-4 pb-3",
      !useHasScrollbarProp() && "no-scrollbar"
    ])
  }, props.children), useHasChevronsProp() ? /* @__PURE__ */ React.createElement(React.Fragment, null, /* @__PURE__ */ React.createElement(VsfButton, {
    variant: "secondary",
    classes: classStringFromArray([
      "slider-button w-12-h12",
      !nextChevronVisibility && "invisible"
    ]),
    isRoundedFull: true,
    onClick: (event) => go("next")
  }, /* @__PURE__ */ React.createElement("span", {
    className: "w-6 h-6"
  }, /* @__PURE__ */ React.createElement(VsfIconChevronRight, {
    className: "slider-chevron"
  })))) : null));
}
export {
  VsfSlider as default
};
