// apps/preview/nuxt/pages/showcases/Chip/ChipSizes.vue
<template>
  <SfChip v-model="chipSmallActive" size="sm" class="mr-2"> Small </SfChip>
  <SfChip v-model="chipBaseActive" size="base" class="mr-2"> Base </SfChip>
  <SfChip v-model="chipDefaultActive" size="base"> Default </SfChip>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { SfChip } from '@storefront-ui/vue';

const chipSmallActive = ref();
const chipBaseActive = ref();
const chipDefaultActive = ref();
</script>

// apps/preview/qwik-city/src/routes/showcases/Chip/ChipSizes/index.tsx
import { SfChip } from '@storefront-ui/qwik';
import { component$ } from '@builder.io/qwik';

export default component$(() => {
  return (
    <div>
      <SfChip size="sm" class="mr-2">
        Small
      </SfChip>
      <SfChip size="base" class="mr-2">
        Base
      </SfChip>
      <SfChip>Default</SfChip>
    </div>
  );
});
