// packages/sfui/frameworks/vue/components/SfCounter/SfCounter.vue
<script setup lang="ts">
import type { PropType } from 'vue';
import { computed, toRefs } from 'vue';
import { SfCounterSize } from '@storefront-ui/vue';

const props = defineProps({
  size: {
    type: String as PropType<`${SfCounterSize}`>,
    default: SfCounterSize.base,
  },
  pill: {
    type: Boolean,
    default: false,
  },
});
const { size, pill } = toRefs(props);

const sizeClasses = computed(() => {
  switch (size?.value) {
    case SfCounterSize['3xs']:
      return ['text-3xs', { 'px-1': pill.value }];
    case SfCounterSize['2xs']:
      return ['text-2xs', { 'px-1.5': pill.value }];
    case SfCounterSize.xs:
      return ['text-xs', { 'px-2': pill.value }];
    case SfCounterSize.sm:
      return ['text-sm', { 'px-2.5': pill.value }];
    case SfCounterSize.lg:
      return ['text-lg', { 'px-3.5': pill.value }];
    default:
      return ['text-base', { 'px-3': pill.value }];
  }
});
</script>

<template>
  <span
    class="inline-flex items-center before:content-['('] after:content-[')'] text-neutral-500"
    :class="[
      sizeClasses,
      {
        'rounded-full py-0.5 font-medium ring-1 ring-neutral-200 ring-inset before:content-none after:content-none':
          pill,
      },
    ]"
    data-testid="counter"
  >
    <slot />
  </span>
</template>

// packages/sfui/frameworks/qwik/src/components/SfCounter/SfCounter.tsx
import { Slot, component$ } from '@builder.io/qwik';
import { SfCounterProps, SfCounterSize } from './types';

export const SfCounter = component$<SfCounterProps>(
  ({ size = SfCounterSize.base, pill = false, class: _class, ...attributes }) => {
    const sizeClasses: Record<SfCounterSize, string> = {
      [SfCounterSize['3xs']]: `text-3xs ${pill ? 'px-1' : ''}`,
      [SfCounterSize['2xs']]: `text-2xs ${pill ? 'px-1.5' : ''}`,
      [SfCounterSize.xs]: `text-xs ${pill ? 'px-2' : ''}`,
      [SfCounterSize.sm]: `text-sm ${pill ? 'px-2.5' : ''}`,
      [SfCounterSize.base]: `text-base ${pill ? 'px-3' : ''}`,
      [SfCounterSize.lg]: `text-lg ${pill ? 'px-3.5' : ''}`,
    };
    const classes = [
      "inline-flex items-center before:content-['('] after:content-[')'] text-neutral-500",
      sizeClasses[size],
      pill
        ? 'rounded-full py-0.5 font-medium ring-1 ring-neutral-200 ring-inset before:content-none after:content-none'
        : '',
      _class,
    ];
    return (
      <span class={classes} data-testid="counter" {...attributes}>
        <Slot />
      </span>
    );
  },
);
