// apps/preview/nuxt/pages/showcases/Tooltip/BasicTooltip.vue
<template>
  <div class="mt-12">
    <SfTooltip label="This is a tooltip!" :id="tooltipId">
      <span :aria-describedby="tooltipId"> Hover me! </span>
    </SfTooltip>
  </div>
</template>

<script setup lang="ts">
import { useId } from 'vue';
import { SfTooltip } from '@storefront-ui/vue';

const id = useId();
const tooltipId = `${id}-tooltip`;
</script>

// apps/preview/next/pages/showcases/Tooltip/BasicTooltip.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { useId } from 'react';
import { SfTooltip } from '@storefront-ui/react';

export default function BasicTooltip() {
  const id = useId();
  const tooltipId = `${id}-tooltip`;

  return (
    <SfTooltip label="This is a tooltip!" id={tooltipId}>
      <span aria-describedby={tooltipId}>Hover me!</span>
    </SfTooltip>
  );
}

// #endregion source
BasicTooltip.getLayout = ShowcasePageLayout;
