// apps/preview/next/pages/showcases/ProgressLinear/ProgressLinearColors.tsx
import { VsfProgressLinear } from '@storefront-ui/react/components/VsfProgressLinear/index';
import { ShowcasePageLayout } from '../../showcases';

export function Showcase() {
  return (
    <div className="flex gap-4 flex-wrap">
      <VsfProgressLinear className="w-12 !text-cyan-700" value={60} size="lg" />
      <VsfProgressLinear className="w-12" size="lg" value={60} />
      <VsfProgressLinear className="w-12 !bg-yellow-200" value={60} size="lg" />
    </div>
  );
}

Showcase.getLayout = ShowcasePageLayout;
export default Showcase;

// apps/preview/nuxt/pages/showcases/ProgressLinear/ProgressLinearColors.vue
<template>
  <div class="flex gap-4 flex-wrap">
    <VsfProgressLinear class="w-12 !text-cyan-700" :value="60" size="lg" />
    <VsfProgressLinear class="w-12" size="lg" :value="60" />
    <VsfProgressLinear class="w-12 !bg-yellow-200" :value="60" size="lg" />
  </div>
</template>

<script lang="ts" setup>
import { VsfProgressLinear } from '@storefront-ui/vue/components/VsfProgressLinear/index';
</script>
