// packages/sfui/frameworks/vue/components/VsfFooter/VsfFooterLabel.vue
<script setup lang="ts">
import { PropType } from 'vue';
import { VsfFooterLabelType } from '@sfui/types/_components';

defineProps({
  type: {
    type: String as PropType<VsfFooterLabelType>,
    default: 'subcategory',
  },
});
</script>

<template>
  <span :class="`vsf-footer__label--${type}`"><slot /></span>
</template>

// packages/sfui/frameworks/react/components/VsfFooter/VsfFooterLabel.tsx
import classNames from 'classnames';
import { VsfFooterLabelType } from '@sfui/types/_components';
import { VsfFooterLabelProps } from './types';

export default function VsfFooterLabel({
  type = VsfFooterLabelType.subcategory,
  children,
  className,
}: VsfFooterLabelProps) {
  return <span className={classNames(`vsf-footer__label--${type}`, className)}>{children}</span>;
}
