// apps/preview/nuxt/pages/showcases/ProductListFilters/Checkbox.vue
<template>
  <VsfListItemMenu tag="label" :selected="selected">
    <template #prefix>
      <VsfCheckbox v-model="selected" label-tag="div" value="some-value" />
    </template>
    <span>{{ label }}</span>
    <p class="text-xs text-gray-500 break-words">{{ secondaryText }}</p>
  </VsfListItemMenu>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { VsfListItemMenu } from '@storefront-ui/vue/components/VsfListItemMenu/index';
import { VsfCheckbox } from '@storefront-ui/vue/components/VsfCheckbox/index';

const label = 'Lorem ipsum dolor amet';
const secondaryText = 'Secondary text';
const selected = ref(true);
</script>

// apps/preview/next/pages/showcases/ProductListFilters/Checkbox.tsx
import { VsfListItemMenu } from '@storefront-ui/react/components/VsfListItemMenu';
import { VsfCheckbox } from '@storefront-ui/react/components/VsfCheckbox';
import { useState } from 'react';
import { ShowcasePageLayout } from '../../showcases';

export function Showcase() {
  const [checkedState, setCheckedState] = useState(false);

  const label = 'Lorem ipsum dolor amet';
  const secondaryText = 'Secondary text';
  return (
    <VsfListItemMenu
      tag="label"
      selected={checkedState}
      slotPrefix={
        <VsfCheckbox
          value="some-value"
          onChange={(event) => {
            setCheckedState(event.target.checked);
          }}
        />
      }
    >
      <span>{label}</span>
      <p className="text-xs text-gray-500 break-words">{secondaryText}</p>
    </VsfListItemMenu>
  );
}

Showcase.getLayout = ShowcasePageLayout;
export default Showcase;
