// apps/preview/next/pages/showcases/Review/WithAvatar.tsx
import { VsfRating, VsfIconCheck } from '@storefront-ui/react';
import reviewAvatar from '@assets/review_avatar.png';
import { ShowcasePageLayout } from '../../showcases';

export function Showcase() {
  return (
    <article className="w-full p-4 border rounded-md">
      <header className="flex flex-col items-start pb-6 space-y-2 md:flex-row md:justify-between md:space-y-0">
        <div className="flex items-start">
          <img src={reviewAvatar.src} alt="Review avatar" className="p-0.5" />
          <div className="flex-col pl-2">
            <span className="text-sm text-neutral-900">Karla</span>
            <span className="flex items-center pr-2 text-xs text-neutral-500">
              <VsfRating value={5} max={5} size="xs" className="mr-2" />2 days ago
            </span>
          </div>
        </div>
        <p className="flex items-center text-xs truncate text-primary-700">
          <VsfIconCheck size="xs" className="mr-1" /> Verified purchase
        </p>
      </header>
      <div className="text-sm text-neutral-900">I love them</div>
    </article>
  );
}

Showcase.getLayout = ShowcasePageLayout;
export default Showcase;

// apps/preview/nuxt/pages/showcases/Review/WithAvatar.vue
<template>
  <article class="w-full p-4 border rounded-md">
    <header class="flex flex-col items-start pb-6 space-y-2 md:flex-row md:justify-between md:space-y-0">
      <div class="flex items-start">
        <img :src="reviewAvatar" alt="Review avatar" class="p-0.5" />
        <div class="flex-col pl-2">
          <span class="text-sm text-neutral-900">Karla</span>
          <span class="flex items-center pr-2 text-xs text-neutral-500">
            <VsfRating :value="5" :max="5" size="xs" class="mr-2" />
            2 days ago
          </span>
        </div>
      </div>
      <p class="flex items-center text-xs truncate text-primary-700">
        <VsfIconCheck size="xs" class="mr-1" /> Verified purchase
      </p>
    </header>
    <div class="text-sm text-neutral-900">I love them</div>
  </article>
</template>

<script lang="ts" setup>
import { VsfRating, VsfIconCheck } from '@storefront-ui/vue';
import reviewAvatar from '@assets/review_avatar.png';
</script>
