// apps/preview/next/pages/examplesOld/componentExample.tsx
import Button from '../../output/blocks/Button';
import { ExamplePageLayout } from '../examplesOld';

const Example = () => {
  return (
    <div className="e-page">
      <div className="e-page-component">
        Your component example here <Button text="yay my component has been mounted" />
      </div>
      <div className="e-page-controls">
        your controls here<br />
        your controls here<br />
        your controls here<br />
        your controls here<br />
        your controls here<br />
        your controls here<br />
        your controls here<br />
        your controls here<br />
        your controls here<br />
        your controls here<br />
        your controls here<br />
        your controls here<br />
        your controls here<br />
        your controls here<br />
        your controls here<br />
        your controls here
      </div>
    </div>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;

// apps/preview/nuxt/pages/examples/componentExample.vue
<template>
  <div class="e-page">
    <div class="e-page-component">
      Your component example here
      <Button text="yay my component has been mounted"/>
    </div>
    <div class="e-page-controls">
      your controls here<br>
      your controls here<br>
      your controls here<br>
      your controls here<br>
      your controls here<br>
      your controls here<br>
      your controls here<br>
      your controls here<br>
      your controls here<br>
      your controls here<br>
      your controls here<br>
      your controls here<br>
      your controls here<br>
      your controls here<br>
      your controls here<br>
      your controls here
    </div>
  </div>
</template>

<script>
import { defineComponent } from "vue";
import Button from '../../output/blocks/Button.vue'

export default defineComponent({
  name: 'ComponentExample',
  components: {
    Button
  }
});
</script>
