// apps/preview/next/pages/examples/SfSelect.tsx
import { SfSelect, SfSelectSize, SfSelectProps } from '@storefront-ui/react';
import classNames from 'classnames';
import { prepareControls } from '../../components/utils/Controls';
import ComponentExample from '../../components/utils/ComponentExample';
import { ExamplePageLayout } from '../examples';

function Example() {
  const { state, controls } = prepareControls<
    SfSelectProps & { label: string; options: { label: string; value: string }[] }
  >(
    [
      {
        type: 'json',
        propType: 'array',
        modelName: 'options',
        description: 'Elements displayed in select options',
      },
      {
        type: 'text',
        propType: 'string',
        modelName: 'value',
        description: 'Selected value',
      },
      {
        type: 'text',
        propType: 'string',
        modelName: 'placeholder',
        description: 'Placeholder for select',
      },
      {
        type: 'boolean',
        propType: 'boolean',
        modelName: 'disabled',
        description: 'Disabled state',
      },
      {
        type: 'boolean',
        propType: 'boolean',
        modelName: 'required',
        description: 'Required state',
      },
      {
        type: 'boolean',
        propType: 'boolean',
        modelName: 'invalid',
        description: 'Invalid state',
      },
      {
        type: 'text',
        propType: 'string',
        modelName: 'label',
        description: 'Label for select',
      },
      {
        type: 'select',
        modelName: 'size',
        options: Object.keys(SfSelectSize),
        description: 'Select can have 3 sizes: `sm`, `base` or `lg`',
      },
    ],
    {
      options: [
        { label: 'red', value: 'red' },
        { label: 'blue', value: 'blue' },
        { label: 'yellow', value: 'yellow' },
        { label: 'green', value: 'green' },
        { label: 'gray', value: 'gray' },
        { label: 'black', value: 'black' },
        { label: 'brown', value: 'brown' },
      ],
      value: '',
      placeholder: '-- Select --',
      disabled: false,
      required: false,
      invalid: false,
      label: 'Label',
      size: SfSelectSize.base,
    },
  );

  function onChange(event: React.ChangeEvent) {
    state.set({ ...state.get, value: (event.target as HTMLSelectElement).value });
  }
  return (
    <ComponentExample controls={{ state, controls }}>
      <label>
        <span
          className={classNames('pb-1 text-sm font-body font-medium', {
            "after:content-['*'] after:text-sm": state.get.required,
            'text-disabled-500 cursor-not-allowed': state.get.disabled,
          })}
        >
          {state.get.label}
        </span>
        <SfSelect {...state.get} onChange={onChange}>
          {state.get.options.map((option) => (
            <option value={option.value} key={option.value}>
              {option.label}
            </option>
          ))}
        </SfSelect>
      </label>
    </ComponentExample>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;

// apps/preview/nuxt/pages/examples/SfSelect.vue
<template>
  <ComponentExample :controls-attrs="controlsAttrs">
    {{ value }}
    <label>
      <span
        :class="[
          `pb-1 text-sm font-body font-medium`,
          required && `after:content-['*']`,
          {
            'text-disabled-500 cursor-not-allowed': disabled,
          },
        ]"
      >
        {{ label }}
      </span>
      <SfSelect v-bind="state" v-model="value">
        <option v-for="{ value, label } in options" :key="value" :value="value">
          {{ label }}
        </option>
      </SfSelect>
    </label>
  </ComponentExample>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import { SfSelect, SfSelectSize } from '@storefront-ui/vue';
import { prepareControls } from '../../components/utils/Controls.vue';
import ComponentExample from '../../components/utils/ComponentExample.vue';

export default defineComponent({
  name: 'SfSelectExample',
  components: {
    SfSelect,
    ComponentExample,
  },
  setup() {
    return {
      ...prepareControls(
        [
          {
            type: 'json',
            propType: 'array',
            modelName: 'options',
            description: 'Elements displayed in select options',
          },
          {
            type: 'text',
            propType: 'string',
            modelName: 'value',
            description: 'Selected value',
          },
          {
            type: 'text',
            propType: 'string',
            modelName: 'placeholder',
            description: 'Placeholder for select',
          },
          {
            type: 'boolean',
            propType: 'boolean',
            modelName: 'disabled',
            description: 'Disabled state',
          },
          {
            type: 'boolean',
            propType: 'boolean',
            modelName: 'required',
            description: 'Required state',
          },
          {
            type: 'boolean',
            propType: 'boolean',
            modelName: 'invalid',
            description: 'Invalid state',
          },
          {
            type: 'text',
            propType: 'string',
            modelName: 'label',
            description: 'Label for select',
          },
          {
            type: 'select',
            modelName: 'size',
            options: Object.keys(SfSelectSize),
            description: 'Select can have 3 sizes: `sm`, `base` or `lg`',
          },
        ],
        {
          options: ref([
            { label: 'red', value: 'red' },
            { label: 'blue', value: 'blue' },
            { label: 'yellow', value: 'yellow' },
            { label: 'green', value: 'green' },
            { label: 'gray', value: 'gray' },
            { label: 'black', value: 'black' },
            { label: 'brown', value: 'brown' },
          ]),
          value: ref(''),
          placeholder: ref('-- Select --'),
          disabled: ref(false),
          required: ref(false),
          invalid: ref(false),
          label: ref('Label'),
          size: ref(SfSelectSize.base),
        },
      ),
    };
  },
});
</script>
