// apps/preview/next/pages/examples/SfThumbnail.tsx
import { SfThumbnail, SfThumbnailSize } from '@storefront-ui/react';
import { prepareControls } from '../../components/utils/Controls';
import ComponentExample from '../../components/utils/ComponentExample';
import { ExamplePageLayout } from '../examples';

function Example() {
  const { state, controls } = prepareControls(
    [
      {
        type: 'select',
        modelName: 'size',
        options: Object.keys(SfThumbnailSize),
        propDefaultValue: SfThumbnailSize.base,
        description: 'Component size',
        propType: 'SfThumbnailSize',
      },
    ],
    {
      size: SfThumbnailSize.base,
    },
  );

  return (
    <ComponentExample controls={{ state, controls }}>
      <SfThumbnail {...state.get} className="bg-gradient-to-tr from-[#4ADE80] to-[#A78BFA]" />
    </ComponentExample>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;

// apps/preview/nuxt/pages/examples/SfThumbnail.vue
<template>
  <ComponentExample :controls-attrs="controlsAttrs">
    <SfThumbnail :size="size" class="bg-gradient-to-tr from-[#4ADE80] to-[#A78BFA]" />
  </ComponentExample>
</template>

<script lang="ts">
import { ref } from 'vue';
import { SfThumbnail, SfThumbnailSize } from '@storefront-ui/vue';
import { prepareControls } from '../../components/utils/Controls.vue';
import ComponentExample from '../../components/utils/ComponentExample.vue';

export default {
  name: 'SfThumbnailExample',
  components: {
    ComponentExample,
    SfThumbnail,
  },
  setup() {
    return {
      ...prepareControls(
        [
          {
            type: 'select',
            modelName: 'size',
            options: Object.keys(SfThumbnailSize),
            propDefaultValue: SfThumbnailSize.base,
            description: 'Component size',
            propType: 'SfThumbnailSize',
          },
        ],
        {
          size: ref(SfThumbnailSize.base),
        },
      ),
    };
  },
};
</script>
