// apps/preview/next/pages/examples/VsfLoaderCircular.tsx
import VsfLoaderCircular from '@sfui/sfui/frameworks/react/components/VsfLoaderCircular/VsfLoaderCircular';
import { VsfLoaderSizes } from '@sfui/shared/types';
import Controls, { prepareControls } from '../../components/utils/Controls';
import { ExamplePageLayout } from '../examples';

function Example() {
  const { state, controls } = prepareControls(
    [
      {
        type: 'select',
        modelName: 'size',
        propType: 'VsfLoaderSizes',
        options: [...Object.keys(VsfLoaderSizes)],
        description: 'sets sizes of components',
      },
      {
        type: 'text',
        modelName: 'screenReaderText',
        propType: 'string',
        propDefaultValue: 'loading',
        description: 'sets hidden text available for screen readers',
      },
    ],
    {
      size: VsfLoaderSizes.lg,
      screenReaderText: 'loading',
    },
  );

  return (
    <div className="e-page">
      <div className="e-page-component">
        <VsfLoaderCircular className="w-10" size={state.get.size} screenReaderText={state.get.screenReaderText} />
      </div>
      <div className="e-page-controls">
        <Controls {...{ state, controls }} />
      </div>
    </div>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;

// apps/preview/nuxt/pages/examples/VsfLoaderCircular.vue
<template>
  <div class="e-page">
    <div class="e-page-component">
      <VsfLoaderCircular class="w-10" :size="size" :screen-reader-text="screenReaderText" />
    </div>
    <div class="e-page-controls">
      <Controls v-bind="controlsAttrs" />
    </div>
  </div>
</template>

<script>
import { ref } from 'vue';
import VsfLoaderCircular from '@sfui/sfui/frameworks/vue/components/VsfLoaderCircular/VsfLoaderCircular.vue';
import { VsfLoaderSizes } from '@sfui/shared/types';
import Controls, { prepareControls } from '../../components/utils/Controls.vue';

export default {
  name: 'VsfLoaderCircularExample',
  components: {
    Controls,
    VsfLoaderCircular,
  },
  setup() {
    return {
      ...prepareControls(
        [
          {
            type: 'select',
            modelName: 'size',
            propType: 'VsfLoaderSizes',
            options: [...Object.keys(VsfLoaderSizes)],
            description: 'sets sizes of components',
          },
          {
            type: 'text',
            modelName: 'screenReaderText',
            propType: 'string',
            propDefaultValue: 'loading',
            description: 'sets hidden text available for screen readers',
          },
        ],
        {
          size: ref(VsfLoaderSizes.lg),
          screenReaderText: ref('loading'),
        },
      ),
    };
  },
};
</script>
