// apps/preview/next/pages/examples/VsfLink.tsx
import { VsfLink, VsfLinkVariant } from '@storefront-ui/react/components/VsfLink';
import Link from 'next/link';
import { prepareControls } from '../../components/utils/Controls';
import { ExamplePageLayout } from '../examples';
import ComponentExample from '../../components/utils/ComponentExample';

function Example() {
  const { state, controls } = prepareControls(
    [
      {
        type: 'text',
        modelName: 'link',
        propType: 'string',
      },
      {
        type: 'select',
        modelName: 'tag',
        propType: '"a" | typeof Link',
        propDefaultValue: 'Link | a',
        description:
          'At first component detect if Next env available and use NuxtLink, then priority takes if component has prop on itself, then VsfConfig "linkTag" setting. When tag = "a" page is reloading otherwise route change is within app',
        options: [
          {
            label: 'default(Link)',
            value: 'Link',
          },
          'a',
        ],
      },
      {
        type: 'select',
        modelName: 'variant',
        options: Object.keys(VsfLinkVariant),
      },
    ],
    {
      link: '/examples/VsfButton',
      variant: VsfLinkVariant.primary,
      tag: 'Link',
    },
  );

  return (
    <ComponentExample controls={{ state, controls }}>
      <VsfLink tag={state.get.tag === 'Link' ? Link : state.get.tag} link={state.get.link} variant={state.get.variant}>
        Link
      </VsfLink>
    </ComponentExample>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;

// apps/preview/nuxt/pages/examples/VsfLink.vue
<template>
  <ComponentExample :controls-attrs="controlsAttrs">
    <VsfLink v-bind="state" :tag="tag === 'NuxtLink' ? NuxtLink : tag"> Link </VsfLink>
  </ComponentExample>
</template>

<script lang="ts">
import { ref, defineComponent } from 'vue';
import { VsfLink, VsfLinkVariant } from '@storefront-ui/vue/components/VsfLink/index';
import { prepareControls } from '../../components/utils/Controls.vue';
import ComponentExample from '../../components/utils/ComponentExample.vue';

export default defineComponent({
  name: 'VsfLinkExample',
  components: {
    ComponentExample,
    VsfLink,
  },
  setup() {
    return {
      NuxtLink: resolveComponent('NuxtLink'),
      ...prepareControls(
        [
          {
            type: 'text',
            modelName: 'link',
            propType: 'string',
          },
          {
            type: 'select',
            modelName: 'tag',
            propType: '"a" | NuxtLink | RouterLink',
            propDefaultValue: 'NuxtLink | RouterLink | a',
            description:
              'At first component detect if Nuxt env available and use NuxtLink, then priority takes if component has prop on itself, then VsfConfig "linkTag" setting. When tag = "a" page is reloading otherwise route change is within app',
            options: [
              {
                label: 'default(NuxtLink)',
                value: 'NuxtLink',
              },
              'a',
            ],
          },
          {
            type: 'select',
            modelName: 'variant',
            propDefaultValue: 'primary',
            options: Object.keys(VsfLinkVariant),
          },
        ],
        {
          link: ref('/examples/VsfButton'),
          variant: ref(VsfLinkVariant.primary),
          tag: ref('NuxtLink'),
        },
      ),
    };
  },
});
</script>
