// apps/preview/nuxt/pages/examples/Checkbox.vue
<template>
  <div class="e-page">
    <div class="e-page-component">
      <Checkbox :name="'custom'" label="label" :rightCheckbox="true" :indeterminate="true"></Checkbox>
    </div>
    <div class="e-page-controls">
    </div>
  </div>
</template>

<script>
import Checkbox from '../../output/blocks/Checkbox.vue';
import { defineComponent } from "vue";

export default defineComponent({
  name: 'CheckboxExample',
  components: {
    Checkbox
  }
});
</script>

// apps/preview/remix/app/routes/examples/Checkbox.tsx
import Checkbox from '../../output/blocks/Checkbox.lite';

export default function Index() {
  return (
    <div className="e-page">
      <div className="e-page-component">
        <Checkbox
          name={'custom'}
          value={'value'}
          label={'label'}
          indeterminate={false}
          required={false}
          disabled={true}
          rightCheckbox={false}
          invalid={false}
          errorText={'Some error occured!'}
          helpText={'Help text!'}
        />
      </div>
      <div className="e-page-controls"></div>
    </div>
  );
}
