// apps/preview/next/pages/showcases/Chip/ChipWithThumbnail.tsx
import { VsfChip, VsfThumbnail } from '@storefront-ui/react';
import { ShowcasePageLayout } from '../../showcases';

export function Showcase() {
  return (
    <>
      <VsfChip size="sm" className="mr-2">
        <VsfThumbnail className="mr-2 bg-red-500" size="sm" />
        <span>Red</span>
      </VsfChip>
      <VsfChip>
        <VsfThumbnail className="mr-2 bg-blue-500" size="base" />
        <span>Blue</span>
      </VsfChip>
    </>
  );
}

Showcase.getLayout = ShowcasePageLayout;
export default Showcase;

// apps/preview/nuxt/pages/showcases/Chip/ChipWithThumbnail.vue
<template>
  <VsfChip v-model="chipRedActive" size="sm" class="mr-2">
    <VsfThumbnail class="bg-red-500" size="sm" />
    <span class="ml-2">Red</span>
  </VsfChip>
  <VsfChip v-model="chipBlueActive">
    <VsfThumbnail class="bg-blue-500" size="base" />
    <span class="ml-2">Blue</span>
  </VsfChip>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { VsfChip, VsfThumbnail } from '@storefront-ui/vue';

const chipRedActive = ref();
const chipBlueActive = ref();
</script>
