// apps/preview/nuxt/pages/showcases/ProgressLinear/ProgressLinearLabel.vue
<template>
  <div class="flex flex-col gap-4">
    <VsfProgressLinear size="lg" :value="value" class="w-24" :aria-label="`${value}%`" />
    <label class="inline-flex items-center gap-2">
      <VsfProgressLinear class="w-24" size="lg" :value="value" />
      <span class="font-medium text-lg">{{ value }}%</span>
    </label>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { VsfProgressLinear } from '@storefront-ui/vue/components/VsfProgressLinear/index';

const value = ref(70);
</script>

// apps/preview/next/pages/showcases/ProgressLinear/ProgressLinearLabel.tsx
import { VsfProgressLinear } from '@storefront-ui/react/components/VsfProgressLinear/index';
import { ShowcasePageLayout } from '../../showcases';

export function Showcase() {
  const value = 70;

  return (
    <div className="flex flex-col gap-4">
      <VsfProgressLinear size="lg" value={value} className="w-12" aria-label={`${value}%`} />
      <label className="inline-flex items-center gap-2">
        <VsfProgressLinear className="w-12" size="lg" value={value} />
        <span className="font-medium text-lg">{value}%</span>
      </label>
    </div>
  );
}

Showcase.getLayout = ShowcasePageLayout;
export default Showcase;
