// apps/preview/qwik-city/src/routes/showcases/Dropdown/BasicDropdown/index.tsx
import { component$, useSignal } from '@builder.io/qwik';
import { SfButton, SfDropdown } from '@storefront-ui/qwik';

export default component$(() => {
  const openSignal = useSignal(false);

  // TODO
  // const { isOpen, toggle, close } = useDisclosure();
  return (
    <SfDropdown
      open={openSignal.value}
      onClose$={() => {
        openSignal.value = false;
      }}
    >
      <div q:slot="trigger">
        <SfButton
          onClick$={() => {
            openSignal.value = !openSignal.value;
          }}
        >
          Toggle
        </SfButton>
      </div>
      <ul class="p-2 rounded bg-gray-100">
        <li>More</li>
        <li>About</li>
        <li>Settings</li>
      </ul>
    </SfDropdown>
  );
});

// apps/preview/nuxt/pages/showcases/Dropdown/BasicDropdown.vue
<template>
  <SfDropdown v-model="isOpen">
    <template #trigger>
      <SfButton @click="toggle()">Toggle</SfButton>
    </template>
    <ul class="p-2 rounded bg-gray-100">
      <li>More</li>
      <li>About</li>
      <li>Settings</li>
    </ul>
  </SfDropdown>
</template>

<script lang="ts" setup>
import { SfDropdown, useDisclosure, SfButton } from '@storefront-ui/vue';

const { isOpen, toggle } = useDisclosure();
</script>
