// apps/mitosis/output/react/src/blocks/VsfCounter/VsfCounter.js
import * as React from "react";

type VsfCounterVariantsKeys = keyof typeof VsfCounterVariants;
export interface VsfCounterProps {
  size?: VsfCounterVariantsKeys;
  pill?: boolean;
  className?: string;
  children?: any;
}

export const VsfCounterVariants = Object.freeze({
  xs: "xs",
  sm: "sm",
  base: "base",
  lg: "lg",
  xl: "xl",
  "2xl": "2xl",
});

export default function VsfCounter(props: VsfCounterProps) {
  function fontSizeClass() {
    switch (props.size) {
      case VsfCounterVariants.xs:
        return "text-3xs";

      case VsfCounterVariants.sm:
        return "text-2xs";

      case VsfCounterVariants.lg:
        return "text-sm";

      case VsfCounterVariants.xl:
        return "text-base";

      case VsfCounterVariants["2xl"]:
        return "text-lg";

      default:
        return "text-xs";
    }
  }

  function pillSpacingClass() {
    if (!props.pill) return "";

    switch (props.size) {
      case VsfCounterVariants.xs:
      case VsfCounterVariants.sm:
        return "px-1";

      case VsfCounterVariants.lg:
        return "px-2.5";

      case VsfCounterVariants.xl:
      case VsfCounterVariants["2xl"]:
        return "px-3";

      default:
        return "px-2";
    }
  }

  function fontWeightClass() {
    if (props.pill) return "font-medium";

    switch (props.size) {
      case VsfCounterVariants.xs:
      case VsfCounterVariants.sm:
        return "font-medium";

      default:
        return "font-normal";
    }
  }

  function pillClass() {
    return props.pill
      ? `${
          props.size === VsfCounterVariants.xs ||
          props.size === VsfCounterVariants.sm
            ? "ring-0"
            : "ring-1 ring-gray-200 ring-inset"
        } py-0.5 rounded-full text-gray-900`
      : `before:content-['('] after:content-[')'] text-gray-500`;
  }

  return (
    <span
      className={`inline-flex items-center font-body ${fontSizeClass()} ${pillClass()} ${pillSpacingClass()} ${fontWeightClass()} ${
        props.className || ""
      }`}
    >
      {props.children}
    </span>
  );
}

// apps/mitosis/output/vue/vue3/src/blocks/VsfCounter/VsfCounter.vue
<template>
  <span
    :class="
      _classStringToObject(
        `inline-flex items-center font-body ${fontSizeClass} ${pillClass} ${pillSpacingClass} ${fontWeightClass} ${
          className || ''
        }`
      )
    "
  >
    <slot />
  </span>
</template>

<script lang="ts">
type VsfCounterVariantsKeys = keyof typeof VsfCounterVariants;
export interface VsfCounterProps {
  size?: VsfCounterVariantsKeys;
  pill?: boolean;
  className?: string;
  children?: any;
}

export const VsfCounterVariants = Object.freeze({
  xs: "xs",
  sm: "sm",
  base: "base",
  lg: "lg",
  xl: "xl",
  "2xl": "2xl",
});

export default {
  name: "vsf-counter",

  props: ["size", "pill", "className"],

  computed: {
    fontSizeClass() {
      switch (this.size) {
        case VsfCounterVariants.xs:
          return "text-3xs";

        case VsfCounterVariants.sm:
          return "text-2xs";

        case VsfCounterVariants.lg:
          return "text-sm";

        case VsfCounterVariants.xl:
          return "text-base";

        case VsfCounterVariants["2xl"]:
          return "text-lg";

        default:
          return "text-xs";
      }
    },
    pillSpacingClass() {
      if (!this.pill) return "";

      switch (this.size) {
        case VsfCounterVariants.xs:
        case VsfCounterVariants.sm:
          return "px-1";

        case VsfCounterVariants.lg:
          return "px-2.5";

        case VsfCounterVariants.xl:
        case VsfCounterVariants["2xl"]:
          return "px-3";

        default:
          return "px-2";
      }
    },
    fontWeightClass() {
      if (this.pill) return "font-medium";

      switch (this.size) {
        case VsfCounterVariants.xs:
        case VsfCounterVariants.sm:
          return "font-medium";

        default:
          return "font-normal";
      }
    },
    pillClass() {
      return this.pill
        ? `${
            this.size === VsfCounterVariants.xs ||
            this.size === VsfCounterVariants.sm
              ? "ring-0"
              : "ring-1 ring-gray-200 ring-inset"
          } py-0.5 rounded-full text-gray-900`
        : `before:content-['('] after:content-[')'] text-gray-500`;
    },
  },

  methods: {
    _classStringToObject(str) {
      const obj = {};
      if (typeof str !== "string") {
        return obj;
      }
      const classNames = str.trim().split(/\s+/);
      for (const name of classNames) {
        obj[name] = true;
      }
      return obj;
    },
  },
};
</script>
