// apps/preview/next/pages/showcases/Tooltip/FocusableTooltip.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { useId } from 'react';
import { SfTooltip, useDisclosure } from '@storefront-ui/react';

export default function BasicTooltip() {
  const id = useId();
  const tooltipId = `${id}-tooltip`;
  const { isOpen, open, close } = useDisclosure();

  return (
    <SfTooltip label="This is a tooltip!" id={tooltipId} open={isOpen} showArrow placement="right">
      <span aria-describedby={tooltipId} onFocus={open} onBlur={close} tabIndex={0}>
        Hover or focus me!
      </span>
    </SfTooltip>
  );
}

// #endregion source
BasicTooltip.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Tooltip/FocusableTooltip.vue
<template>
  <SfTooltip :id="tooltipId" label="This is a tooltip!" show-arrow placement="right" v-model="isOpen">
    <span :aria-describedby="tooltipId" tabindex="0" @focus="open" @blur="close"> Hover or focus me! </span>
  </SfTooltip>
</template>

<script setup lang="ts">
import { useId } from 'vue';
import { SfTooltip, useDisclosure } from '@storefront-ui/vue';

const id = useId();
const tooltipId = `${id}-tooltip`;
const { isOpen, open, close } = useDisclosure();
</script>
