// apps/preview/qwik-city/src/routes/showcases/Alert/AlertError/index.tsx
import { component$ } from '@builder.io/qwik';
import { SfIconClose } from '@storefront-ui/qwik';

export default component$(() => {
  return (
    <div
      role="alert"
      class="flex items-start md:items-center max-w-[600px] shadow-md bg-negative-100 pr-2 pl-4 ring-1 ring-negative-300 typography-text-sm md:typography-text-base py-1 rounded-md"
    >
      <p class="py-2 mr-2">The password change was failed.</p>
      <button
        type="button"
        class="py-1.5 px-3 md:py-2 md:px-4 rounded-md text-negative-700 hover:bg-negative-200 active:bg-negative-300 hover:text-negative-800 active:text-negative-900 ml-auto font-medium focus-visible:outline focus-visible:outline-offset"
      >
        Retry
      </button>
      <button
        type="button"
        class="p-1.5 md:p-2 ml-2 rounded-md text-negative-700 hover:bg-negative-200 active:bg-negative-300 hover:text-negative-800 active:text-negative-900 focus-visible:outline focus-visible:outline-offset"
        aria-label="Close error alert"
      >
        <SfIconClose class="hidden md:block" />
        <SfIconClose size="sm" class="block md:hidden" />
      </button>
    </div>
  );
});

// apps/preview/nuxt/pages/showcases/Alert/AlertError.vue
<template>
  <div
    role="alert"
    class="flex items-start md:items-center max-w-[600px] shadow-md bg-negative-200 pr-2 pl-4 ring-1 ring-negative-200 typography-text-sm md:typography-text-base py-1 rounded-xl"
  >
    <p class="py-2 mr-2">The password change was failed.</p>
    <button
      type="button"
      class="py-1.5 px-3 md:py-2 md:px-4 rounded-md text-negative-700 hover:bg-negative-200 active:bg-negative-300 hover:text-negative-800 active:text-negative-900 ml-auto font-medium focus-visible:outline focus-visible:outline-offset"
    >
      Retry
    </button>
    <button
      type="button"
      class="p-1.5 md:p-2 ml-2 rounded-md text-negative-700 hover:bg-negative-200 active:bg-negative-300 hover:text-negative-800 active:text-negative-900 focus-visible:outline focus-visible:outline-offset"
      aria-label="Close error alert"
    >
      <SfIconClose class="hidden md:block" />
      <SfIconClose size="sm" class="block md:hidden" />
    </button>
  </div>
</template>
<script lang="ts" setup>
import { SfIconClose } from '@storefront-ui/vue';
</script>
