// apps/preview/nuxt/pages/showcases/NavbarTop/NavbarTopFilled.vue
<template>
  <div class="w-full h-full bg-neutral-50">
    <header class="flex justify-center w-full text-white border-0 bg-primary-700 h-14 md:h-20 border-neutral-200">
      <div class="flex items-center flex-row flex-nowrap justify-start h-full max-w-[1536px] w-full px-4 md:px-10">
        <a aria-label="SF Homepage" class="inline-block text-white md:h-10 lg:h-7">
          <img src="/vsf_logo_white.svg" alt="SF Logo" class="hidden lg:block mr-10 w-[12.5rem] h-[1.75rem]" />
          <img src="/vsf_logo_sign_white.svg" alt="Sf Logo" class="block w-8 h-8 mr-4 md:w-10 md:h-10 lg:hidden" />
        </a>
        <SfButton
          class="block !px-2 mr-auto text-white bg-transparent hover:bg-primary-800 hover:text-white active:bg-primary-900 active:text-white font-body"
          type="button"
          variant="tertiary"
        >
          <template #prefix>
            <SfIconMenu />
          </template>
          <span class="hidden md:inline-flex">Categories</span>
        </SfButton>
        <nav>
          <div class="flex flex-row flex-nowrap">
            <SfButton
              v-for="actionItem in actionItems"
              :key="actionItem.ariaLabel"
              :class="[
                'mr-2 -ml-0.5 text-white bg-transparent hover:bg-primary-800 hover:text-white active:bg-primary-900 active:text-white',
                { 'lg:hidden': actionItem.label === 'Log in' },
              ]"
              :aria-label="actionItem.ariaLabel"
              variant="tertiary"
              square
            >
              <template #prefix>
                <Component :is="actionItem.icon" />
              </template>
            </SfButton>
            <SfButton
              class="hidden lg:inline-flex mr-2 -ml-0.5 text-white bg-transparent hover:bg-primary-800 hover:text-white active:bg-primary-900 active:text-white"
              :aria-label="actionItems[2].ariaLabel"
              variant="tertiary"
            >
              <template #prefix>
                <Component :is="actionItems[2].icon" />
              </template>
              Log in
            </SfButton>
          </div>
        </nav>
      </div>
    </header>
  </div>
</template>
<script lang="ts" setup>
import { SfButton, SfIconShoppingCart, SfIconFavorite, SfIconPerson, SfIconMenu } from '@storefront-ui/vue';

const actionItems = [
  {
    icon: SfIconShoppingCart,
    ariaLabel: 'Cart',
  },
  {
    icon: SfIconFavorite,
    ariaLabel: 'Wishlist',
  },
  {
    label: 'Log in',
    icon: SfIconPerson,
    ariaLabel: 'Log in',
  },
];
</script>

// apps/preview/qwik-city/src/routes/showcases/NavbarTop/NavbarTopFilled/index.tsx
import { component$ } from '@builder.io/qwik';
import { SfButton, SfIconFavorite, SfIconMenu, SfIconPerson, SfIconShoppingCart } from '@storefront-ui/qwik';

export default component$(() => {
  const actionItems = [
    {
      icon: <SfIconShoppingCart />,
      label: '',
      ariaLabel: 'Cart',
      role: 'button',
    },
    {
      icon: <SfIconFavorite />,
      label: '',
      ariaLabel: 'Wishlist',
      role: 'button',
    },
    {
      label: 'Log in',
      icon: <SfIconPerson />,
      ariaLabel: 'Log in',
      role: 'login',
    },
  ];

  return (
    <div class="w-full h-full bg-neutral-50">
      <header class="flex justify-center w-full text-white border-0 bg-primary-700 h-14 md:h-20 border-neutral-200">
        <div class="flex items-center flex-row flex-nowrap justify-start h-full max-w-[1536px] w-full px-4 md:px-10">
          <a href="/" aria-label="SF Homepage" class="inline-block text-white">
            <picture>
              <source srcSet={'/images/vsf_logo_white.svg'} media="(min-width: 767px)" />
              <img
                src={'/images/vsf_logo_sign_white.svg'}
                alt="Sf Logo"
                class="w-8 h-8 mr-4 md:w-[12.5rem] md:h-[1.75rem]"
              />
            </picture>
          </a>
          <SfButton
            class="block !px-2 mr-auto text-white bg-transparent hover:bg-primary-800 hover:text-white active:bg-primary-900 active:text-white font-body"
            type="button"
            variant="tertiary"
          >
            <div q:slot="prefix">
              <SfIconMenu />
            </div>
            <span class="hidden md:inline-flex">Categories</span>
          </SfButton>
          <nav class="flex flex-row flex-nowrap">
            {actionItems.map((actionItem) => (
              <SfButton
                class="mr-2 -ml-0.5 text-white bg-transparent hover:bg-primary-800 hover:text-white active:bg-primary-900 active:text-white"
                key={actionItem.ariaLabel}
                aria-label={actionItem.ariaLabel}
                variant="tertiary"
                square
              >
                <div q:slot="prefix">{actionItem.icon}</div>
                {actionItem.role === 'login' && <p class="hidden md:inline-flex">{actionItem.label}</p>}
              </SfButton>
            ))}
          </nav>
        </div>
      </header>
    </div>
  );
});
