// apps/preview/nuxt/legacy/examplesOld/VsfAlert.vue
<template>
  <div class="e-page">
    <div class="e-page-component">
      <VsfAlert
        :type="typeModel"
        :persistent="persistentModel"
        :header="headerModel"
        :description="descriptionModel"
        :default-icon="defaultIconModel"
        :default-button="defaultButtonModel"
        @close="closeClick"
      >
        <template v-if="slotIconModel" #icon>
          {{ slotIconModel }}
        </template>
        <template v-if="slotButtonModel" #button>
          {{ slotButtonModel }}
        </template>
      </VsfAlert>
    </div>
    <div class="e-page-controls">
      <Controls v-bind="controlsAttrs" />
    </div>
  </div>
</template>

<script>
import { ref } from 'vue';
import VsfAlert, { VsfAlertTypes } from '../../output/blocks/VsfAlert/VsfAlert.vue';
import Controls, { prepareControls } from '../../components/utils/Controls.vue';

export default {
  name: 'VsfAlertExample',
  components: {
    Controls,
    VsfAlert,
  },
  setup() {
    const closeClick = () => console.log('Clicked 🥳');

    return {
      closeClick,
      ...prepareControls(
        [
          {
            title: 'Type',
            type: 'select',
            modelName: 'typeModel',
            options: Object.keys(VsfAlertTypes),
            propDefaultValue: VsfAlertTypes.info,
            propType: 'VsfAlertTypes',
          },
          {
            title: 'Persistent',
            type: 'boolean',
            modelName: 'persistentModel',
            propDefaultValue: false,
            propType: 'boolean',
          },
          {
            title: 'Header',
            type: 'text',
            modelName: 'headerModel',
            propDefaultValue: 'Header',
            propType: 'string',
          },
          {
            title: 'Description',
            type: 'text',
            modelName: 'descriptionModel',
            propDefaultValue: 'Description',
            propType: 'string',
          },
          {
            title: 'SlotIcon',
            type: 'text',
            modelName: 'slotIconModel',
            propDefaultValue: '',
            propType: 'string',
          },
          {
            title: 'SlotButton',
            type: 'text',
            modelName: 'slotButtonModel',
            propDefaultValue: '',
            propType: 'string',
          },
        ],
        {
          typeModel: ref(VsfAlertTypes.info),
          persistentModel: ref(false),
          headerModel: ref('Header'),
          descriptionModel: ref('Description'),
          slotIconModel: ref(''),
          slotButtonModel: ref(''),
        },
      ),
    };
  },
};
</script>

// apps/preview/next/pages/examplesOld/VsfAlert.tsx
import VsfAlert, { VsfAlertTypes } from '../../output/blocks/VsfAlert/VsfAlert';
import Controls, { prepareControls } from '../../components/utils/Controls';
import { ExamplePageLayout } from '../examplesOld';

const Example = () => {
  const { state, controls } = prepareControls([
    {
      title: 'Type',
      type: 'select',
      modelName: 'typeModel',
      options: Object.keys(VsfAlertTypes),
      propDefaultValue: VsfAlertTypes.info,
      propType: 'VsfAlertTypes',
    },
    {
      title: 'Persistent',
      type: 'boolean',
      modelName: 'persistentModel',
      propDefaultValue: 'false',
      propType: 'boolean',
    },
    {
      title: 'Header',
      type: 'text',
      modelName: 'headerModel',
      propDefaultValue: 'Header',
      propType: 'string',
    },
    {
      title: 'Description',
      type: 'text',
      modelName: 'descriptionModel',
      propDefaultValue: 'Description',
      propType: 'string',
    },
    {
      title: 'SlotIcon',
      type: 'text',
      modelName: 'slotIconModel',
      propDefaultValue: '',
      propType: 'string',
    },
    {
      title: 'SlotButton',
      type: 'text',
      modelName: 'slotButtonModel',
      propDefaultValue: '',
      propType: 'string',
    },
  ], {
    typeModel: VsfAlertTypes.info,
    persistentModel: false,
    headerModel: 'Header',
    descriptionModel: 'Description',
    slotIconModel: '',
    slotButtonModel: '',
  });

  const closeClick = () => console.log('Clicked 🥳');

  return (
    <div className="e-page">
      <div className="e-page-component">
        <VsfAlert
          type={state.get.typeModel}
          persistent={state.get.persistentModel}
          header={state.get.headerModel}
          description={state.get.descriptionModel}
          slotIcon={state.get.slotIconModel}
          slotButton={state.get.slotButtonModel}
          handleCloseClick={closeClick}
        />
      </div>
      <div className="e-page-controls">
        <Controls {...{ state, controls }} />
      </div>
    </div>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;
