// apps/preview/nuxt/pages/examplesOld/VsfDivider.vue
<template>
  <div class="e-page">
    <div class="e-page-component">
      <VsfDivider />
    </div>
  </div>
</template>

<script>
import { defineComponent } from "vue";
import VsfDivider from '../../output/blocks/VsfDivider/VsfDivider.vue'

export default defineComponent({
  name: 'VsfDividerExample',
  components: {
    VsfDivider
  }
});
</script>

// apps/preview/next/pages/examplesOld/VsfDivider.tsx
import VsfDivider from '../../output/blocks/VsfDivider/VsfDivider';
import { ExamplePageLayout } from '../examplesOld';

const Example = () => {
  return (
    <div className="e-page">
      <div className="e-page-component">
        <VsfDivider />
      </div>
    </div>
  );
}

Example.getLayout = ExamplePageLayout;
export default Example;
