// packages/sfui/frameworks/react/components/VsfDisplayContent/VsfDisplayContent.tsx
import classNames from 'classnames';
import { VsfDisplayContentProps } from './types';

export default function Display({
  children,
  title,
  titleAs = 'h1',
  subtitle,
  description,
  className,
}: VsfDisplayContentProps) {
  const TitleTag = titleAs as keyof JSX.IntrinsicElements;
  return (
    <div className={classNames('vsf-display-content', className)} data-testid="display-c">
      <p className="vsf-display-content__subtitle">{subtitle}</p>
      <TitleTag className="vsf-display-content__title">{title}</TitleTag>
      <p className="vsf-display-content__description">{description}</p>
      {children}
    </div>
  );
}

// packages/sfui/frameworks/vue/components/VsfDisplayContent/VsfDisplayContent.vue
<script lang="ts" setup>
defineProps({
  subtitle: {
    type: String,
    default: '',
  },
  title: {
    type: String,
    default: '',
  },
  titleTag: {
    type: String,
    default: 'h1',
  },
  description: {
    type: String,
    default: '',
  },
});
</script>

<template>
  <div class="vsf-display-content" data-testid="display-content">
    <p class="vsf-display-content__subtitle">{{ subtitle }}</p>
    <component :is="titleTag" class="vsf-display-content__title">{{ title }}</component>
    <p class="vsf-display-content__description">{{ description }}</p>
    <slot />
  </div>
</template>
