// packages/sfui/frameworks/vue/components/VsfListItemMenu/VsfListItemMenu.vue
<script setup lang="ts">
import type { PropType } from 'vue';
import { computed, toRefs } from 'vue';
import { VsfListItemMenuSizes } from './types';
import { VsfCounter, VsfCounterSizes } from '../VsfCounter';

const props = defineProps({
  label: {
    type: String,
    default: '',
  },
  link: {
    type: String,
    default: undefined,
  },
  size: {
    type: String as PropType<VsfListItemMenuSizes>,
    default: VsfListItemMenuSizes.base,
  },
  secondaryText: {
    type: String,
    default: '',
  },
  counter: {
    type: Number,
    default: null,
  },
  disabled: {
    type: Boolean,
    default: undefined,
  },
  selected: {
    type: Boolean,
    default: false,
  },
  selectedBackground: {
    type: Boolean,
    default: false,
  },
  truncate: {
    type: Boolean,
    default: false,
  },
  tag: {
    type: String,
    default: undefined,
  },
});
const { tag, link, disabled } = toRefs(props);
// TODO: replace with link component when ready
const componentTag = computed(() => tag?.value ?? (link?.value ? 'a' : 'button'));
const componentType = computed(() => (tag?.value ? undefined : link?.value && 'button'));
const componentDisabled = computed(() => (!link?.value ? disabled?.value : undefined));
</script>

<template>
  <!-- TODO: Replace with Link component when ready -->
  <component
    :is="componentTag"
    :href="link"
    :class="[
      'vsf-list-item-menu peer',
      `vsf-list-item-menu--size-${size}`,
      {
        'vsf-list-item-menu--selected': selected,
        'vsf-list-item-menu--selected-bg': selected && selectedBackground,
        'vsf-list-item-menu--disabled': disabled,
      },
    ]"
    :type="componentType"
    :disabled="componentDisabled"
    data-testid="list-item-menu"
  >
    <div v-if="$slots.prefix" class="vsf-list-item-menu__icon vsf-list-item-menu__icon--prefix">
      <slot name="prefix" />
    </div>
    <div class="vsf-list-item-menu__content">
      <slot>
        <span class="vsf-list-item-menu__title">
          <span v-if="label" class="vsf-list-item-menu__label" data-testid="list-item-menu-label">{{ label }}</span>
          <VsfCounter
            v-if="counter"
            :size="VsfCounterSizes.xl"
            class="vsf-list-item-menu__counter"
            data-testid="list-item-menu-counter"
            >{{ counter }}</VsfCounter
          >
        </span>
      </slot>
      <slot name="secondaryText">
        <p
          v-if="secondaryText"
          :class="['vsf-list-item-menu__secondary-text', { 'vsf-list-item-menu__secondary-text--truncated': truncate }]"
          data-testid="list-item-menu-secondary-text"
        >
          {{ secondaryText }}
        </p>
      </slot>
    </div>
    <div v-if="$slots.suffix" class="vsf-list-item-menu__icon">
      <slot name="suffix" />
    </div>
  </component>
</template>

// packages/sfui/frameworks/react/components/VsfListItemMenu/VsfListItemMenu.tsx
import classNames from 'classnames';
import { VsfCounterSizes } from '../VsfCounter/types';
import { VsfListItemMenuProps, VsfListItemMenuSizes } from './types';
import VsfCounter from '../VsfCounter/VsfCounter';

export default function VsfListItemMenu({
  label,
  counter,
  secondaryText,
  link,
  size = VsfListItemMenuSizes.base,
  disabled,
  selected,
  selectedBackground,
  className,
  slotPrefix,
  slotSuffix,
  truncate,
  tag,
  onClick = () => ({}),
}: VsfListItemMenuProps): JSX.Element {
  //  TODO: Replace with Link component when its done
  const TagComponent = tag || (link ? 'a' : 'button');
  const componentType = !link ? 'button' : undefined;
  const componentDisabled = !link ? disabled : undefined;
  return (
    <TagComponent
      className={classNames(
        'vsf-list-item-menu peer',
        `vsf-list-item-menu--size-${size}`,
        {
          'vsf-list-item-menu--selected': selected,
          'vsf-list-item-menu--selected-bg': selected && selectedBackground,
          'vsf-list-item-menu--disabled': disabled,
        },
        className,
      )}
      href={link}
      type={componentType}
      disabled={componentDisabled}
      onClick={() => onClick(!selected)}
      data-testid="list-item-menu"
    >
      {slotPrefix && <div className="vsf-list-item-menu__icon vsf-list-item-menu__icon--prefix">{slotPrefix}</div>}
      <span className="vsf-list-item-menu__content">
        <span className="vsf-list-item-menu__title">
          {label ? (
            <span className="vsf-list-item-menu__label" data-testid="list-item-menu-label">
              {label}
            </span>
          ) : null}
          {counter ? (
            <VsfCounter
              size={VsfCounterSizes.xl}
              className="vsf-list-item-menu__counter"
              data-testid="list-item-menu-counter"
            >
              {counter}
            </VsfCounter>
          ) : null}
        </span>
        {secondaryText ? (
          <p
            className={classNames('vsf-list-item-menu__secondary-text', {
              'vsf-list-item-menu__secondary-text--truncated': truncate,
            })}
            data-testid="list-item-menu-secondary-text"
          >
            {secondaryText}
          </p>
        ) : null}
      </span>
      {slotSuffix && <div className="vsf-list-item-menu__icon">{slotSuffix}</div>}
    </TagComponent>
  );
}
