// apps/preview/next/pages/showcases/Textarea/TextareaInvalid.tsx
/* eslint-disable jsx-a11y/label-has-associated-control */
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { SfTextarea } from '@storefront-ui/react';

export default function InvalidTextarea() {
  return (
    <>
      <label>
        <span className="typography-text-sm font-medium">Description</span>
        <SfTextarea invalid placeholder="Write something about yourself..." className="w-full block" />
      </label>
      <div className="flex justify-between mt-0.5">
        <p className="typography-text-sm text-negative-700 font-medium">The field cannot be empty</p>
        <p className="typography-hint-xs text-neutral-500">Do not include personal or financial information.</p>
      </div>
    </>
  );
}

// #endregion source
InvalidTextarea.getLayout = ShowcasePageLayout;

// apps/preview/nuxt/pages/showcases/Textarea/TextareaInvalid.vue
<template>
  <label>
    <span class="text-sm font-medium">Description</span>
    <SfTextarea invalid placeholder="Write something about yourself..." class="w-full block" />
  </label>
  <div class="flex justify-between mt-0.5">
    <p class="typography-text-sm text-negative-700 font-medium">The field cannot be empty</p>
    <p class="typography-hint-xs text-neutral-500">Do not include personal or financial information.</p>
  </div>
</template>

<script lang="ts" setup>
import { SfTextarea } from '@storefront-ui/vue';
</script>
