// apps/preview/next/pages/showcases/Button/ButtonContent.tsx
import { VsfButton } from '@storefront-ui/react/components/VsfButton';
import { VsfIconHome, VsfIconStar, VsfIconShoppingCart } from '@storefront-ui/react/components/VsfIcons';
import { ShowcasePageLayout } from '../../showcases';

export function Showcase() {
  return (
    <div className="flex flex-col items-center space-y-4 extra-small:flex-row extra-small:space-y-0 extra-small:space-x-4">
      <VsfButton slotPrefix={<VsfIconHome />}>Home</VsfButton>

      <VsfButton slotSuffix={<VsfIconStar />}>Hello</VsfButton>

      <VsfButton type="button" square aria-label="Add to cart">
        <VsfIconShoppingCart />
      </VsfButton>
    </div>
  );
}

Showcase.getLayout = ShowcasePageLayout;
export default Showcase;

// apps/preview/nuxt/pages/showcases/Button/ButtonContent.vue
<template>
  <div class="flex flex-col items-center space-y-4 extra-small:flex-row extra-small:space-y-0 extra-small:space-x-4">
    <VsfButton>
      <template #prefix>
        <VsfIconHome />
      </template>
      Home
    </VsfButton>

    <VsfButton>
      <template #suffix>
        <VsfIconStar />
      </template>
      Hello
    </VsfButton>

    <VsfButton type="button" :square="true" aria-label="Add to cart">
      <VsfIconAdd />
    </VsfButton>
  </div>
</template>

<script lang="ts" setup>
import { VsfButton } from '@storefront-ui/vue/components/VsfButton/index';
import { VsfIconHome, VsfIconStar, VsfIconAdd } from '@storefront-ui/vue/components/VsfIcons/index';
</script>
