// apps/preview/nuxt/pages/showcases/Badge/BadgeBasic.vue
<template>
  <div class="flex gap-3">
    <SfButton class="relative" square variant="tertiary">
      <SfIconShoppingCart />
      <SfBadge :content="content" />
    </SfButton>

    <SfButton class="relative" square variant="tertiary">
      <SfIconShoppingCart />
      <SfBadge :content="maxContent" />
    </SfButton>

    <SfButton class="relative" square variant="tertiary">
      <SfIconShoppingCart />
      <SfBadge :content="textContent" />
    </SfButton>

    <SfButton class="relative" square variant="tertiary">
      <SfIconShoppingCart />
      <SfBadge variant="dot" />
    </SfButton>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { SfBadge, SfButton, SfIconShoppingCart } from '@storefront-ui/vue';

const content = ref(10);
const maxContent = ref(10000);
const textContent = ref('New');
</script>

// apps/preview/next/pages/showcases/Badge/BadgeBasic.tsx
import { ShowcasePageLayout } from '../../showcases';
// #region source
import { SfBadge, SfButton, SfIconShoppingCart } from '@storefront-ui/react';

export default function BadgeBasic() {
  return (
    <div className="flex gap-3">
      <SfButton className="relative" square variant="tertiary">
        <SfIconShoppingCart />
        <SfBadge content={10} />
      </SfButton>

      <SfButton className="relative" square variant="tertiary">
        <SfIconShoppingCart />
        <SfBadge content={10000} />
      </SfButton>

      <SfButton className="relative" square variant="tertiary">
        <SfIconShoppingCart />
        <SfBadge variant="dot" />
      </SfButton>

      <SfButton className="relative" square variant="tertiary">
        <SfIconShoppingCart />
        <SfBadge content="NEW" />
      </SfButton>
    </div>
  );
}

// #endregion source
BadgeBasic.getLayout = ShowcasePageLayout;
