// apps/preview/nuxt/pages/showcases/QuantitySelector/QuantitySelector.vue
<template>
  <div class="inline-flex flex-col items-center">
    <div class="flex">
      <VsfButton
        type="button"
        variant="tertiary"
        :disabled="count <= min"
        square
        class="border-l border-y border-neutral-300 rounded-r-none"
        :aria-controls="inputId"
        aria-label="Decrease value"
        @click="dec()"
      >
        <VsfIconRemove />
      </VsfButton>
      <input
        :id="inputId"
        v-model="count"
        type="number"
        role="spinbutton"
        class="appearance-none px-2 border-y border-neutral-300 rounded-none text-center [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:m-0 [&::-webkit-outer-spin-button]:appearance-none"
        :min="min"
        :max="max"
        @input="handleOnChange"
      />
      <VsfButton
        type="button"
        variant="tertiary"
        :disabled="count >= max"
        square
        class="border-r border-y border-neutral-300 rounded-l-none"
        :aria-controls="inputId"
        aria-label="Increase value"
        @click="inc()"
      >
        <VsfIconAdd />
      </VsfButton>
    </div>
    <p class="text-xs mt-2 text-neutral-500">
      <strong class="text-neutral-900">{{ max }}</strong> in stock
    </p>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import { clamp } from '@storefront-ui/shared';
import { useCounter } from '@vueuse/core';
import { VsfButton, VsfIconAdd, VsfIconRemove, useId } from '@storefront-ui/vue';

const min = ref(1);
const max = ref(10);
const inputId = useId;
const { count, inc, dec, set } = useCounter(1, { min: min.value, max: max.value });

function handleOnChange(event: Event) {
  const currentValue = (event.target as HTMLInputElement)?.value;
  const nextValue = parseFloat(currentValue);
  set(clamp(nextValue, min.value, max.value));
}
</script>

// apps/preview/next/pages/showcases/QuantitySelector/QuantitySelector.tsx
import { VsfButton, VsfIconAdd, VsfIconRemove } from '@storefront-ui/react';
import { useCounter } from 'react-use';
import { useId, ChangeEvent } from 'react';
import { clamp } from '@storefront-ui/shared';
import { ShowcasePageLayout } from '../../showcases';

export function Showcase() {
  const inputId = useId();
  const min = 1;
  const max = 10;
  const [value, { inc, dec, set }] = useCounter(min);
  function handleOnChange(event: ChangeEvent<HTMLInputElement>) {
    const { value: currentValue } = event.target;
    const nextValue = parseFloat(currentValue);
    set(clamp(nextValue, min, max));
  }
  return (
    <div className="inline-flex flex-col items-center">
      <div className="flex">
        <VsfButton
          type="button"
          variant="tertiary"
          square
          className="border-l border-y border-neutral-300 rounded-r-none"
          disabled={value <= min}
          aria-controls={inputId}
          aria-label="Decrease value"
          onClick={() => dec()}
        >
          <VsfIconRemove />
        </VsfButton>
        <input
          id={inputId}
          type="number"
          role="spinbutton"
          className="appearance-none px-2 border-y border-neutral-300 text-center [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:m-0 [&::-webkit-outer-spin-button]:appearance-none"
          min={min}
          max={max}
          value={value}
          onChange={handleOnChange}
        />
        <VsfButton
          type="button"
          variant="tertiary"
          square
          className="border-r border-y border-neutral-300 rounded-l-none"
          disabled={value >= max}
          aria-controls={inputId}
          aria-label="Increase value"
          onClick={() => inc()}
        >
          <VsfIconAdd />
        </VsfButton>
      </div>
      <p className="text-xs mt-2 text-neutral-500">
        <strong className="text-neutral-900">{max}</strong> in stock
      </p>
    </div>
  );
}

Showcase.getLayout = ShowcasePageLayout;
export default Showcase;
